// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0d2be16cf4ecf57c "Anker (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Loading' | 'Disabled' | 'Success' | 'Error' // Variant
}} Props

 */
import { className, css, fonts } from "../chunks/chunk-BRGTNG7B.js";
import { routes } from "../chunks/chunk-QR7ZKMZ2.js";

// virtual:buttons/form
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/ktYjUP30qEcJYpbaZ6jM/DpK0pThZS38YEn4H53Pq/Mo6nJOlmg.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var enabledGestures = {
	NC44_gCXq: {
		hover: true,
		pressed: true,
	},
};
var cycleOrder = [
	"NC44_gCXq",
	"KnD2nQ68i",
	"IDfdD9jR7",
	"iWe_DABvo",
	"V7CMZLThb",
];
var serializationHash = "framer-klY14";
var variantClassNames = {
	IDfdD9jR7: "framer-v-1ssq7j3",
	iWe_DABvo: "framer-v-14c8wow",
	KnD2nQ68i: "framer-v-1gfk0fo",
	NC44_gCXq: "framer-v-18xs4i3",
	V7CMZLThb: "framer-v-z55x4y",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.2,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var transition2 = {
	delay: 0,
	duration: 1,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "NC44_gCXq",
	Disabled: "IDfdD9jR7",
	Error: "V7CMZLThb",
	Loading: "KnD2nQ68i",
	Success: "iWe_DABvo",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "NC44_gCXq",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "NC44_gCXq",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "KnD2nQ68i") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "KnD2nQ68i") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.button
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-18xs4i3",
							className2,
							classNames,
						)}
						data-framer-name={"Default"}
						data-reset={"button"}
						layoutDependency={layoutDependency}
						layoutId={"NC44_gCXq"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "0px",
							"--border-color": "rgba(0, 0, 0, 0)",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "0px",
							backgroundColor: "rgba(255, 255, 255, 0.2)",
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							opacity: 1,
							...style,
						}}
						variants={{
							"NC44_gCXq-hover": {
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-0bf52c79-aecd-4909-9221-bc9ee5507e5d, rgb(194, 194, 194))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor: "rgba(255, 255, 255, 0.35)",
								opacity: 1,
							},
							"NC44_gCXq-pressed": {
								"--border-bottom-width": "0px",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-top-width": "0px",
								backgroundColor: "rgba(255, 255, 255, 0.35)",
								opacity: 1,
							},
							IDfdD9jR7: {
								opacity: 0.5,
							},
							iWe_DABvo: {
								opacity: 1,
							},
							V7CMZLThb: {
								backgroundColor: "rgba(255, 34, 68, 0.15)",
								opacity: 1,
							},
						}}
						{...addPropertyOverrides(
							{
								"NC44_gCXq-hover": {
									"data-border": true,
									"data-framer-name": void 0,
								},
								"NC44_gCXq-pressed": {
									"data-framer-name": void 0,
								},
								IDfdD9jR7: {
									"data-framer-name": "Disabled",
								},
								iWe_DABvo: {
									"data-framer-name": "Success",
								},
								KnD2nQ68i: {
									"data-framer-name": "Loading",
								},
								V7CMZLThb: {
									"data-framer-name": "Error",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<RichText
								__fromCanvasComponent={true}
								className={"framer-11gycud"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Yse8ezSeR"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-0bf52c79-aecd-4909-9221-bc9ee5507e5d, rgb(194, 194, 194))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								variants={{
									"NC44_gCXq-hover": {
										"--extracted-r6o4lv":
											"var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255))",
									},
									IDfdD9jR7: {
										"--extracted-r6o4lv":
											"var(--token-8d839ec5-2551-4c63-8fc1-0d549252d6d5, rgb(191, 191, 191))",
									},
									V7CMZLThb: {
										"--extracted-r6o4lv": "rgb(255, 34, 68)",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										"NC44_gCXq-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-cpwznz"}
														data-styles-preset={"ls_KuhAAC"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255)))",
														}}
													>
														{"Submit"}
													</motion.p>
												</React.Fragment>
											),
										},
										IDfdD9jR7: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-cpwznz"}
														data-styles-preset={"ls_KuhAAC"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-8d839ec5-2551-4c63-8fc1-0d549252d6d5, rgb(191, 191, 191)))",
														}}
													>
														{"Submit"}
													</motion.p>
												</React.Fragment>
											),
										},
										V7CMZLThb: {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7R2Vpc3QtNTAw",
															"--framer-font-family":
																'"Geist", "Geist Placeholder", sans-serif',
															"--framer-font-size": "14px",
															"--framer-font-weight": "500",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(255, 34, 68))",
														}}
													>
														{"Something went wrong"}
													</motion.p>
												</React.Fragment>
											),
											fonts: ["GF;Geist-500"],
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-cpwznz"}
										data-styles-preset={"ls_KuhAAC"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-0bf52c79-aecd-4909-9221-bc9ee5507e5d, rgb(194, 194, 194)))",
										}}
									>
										{"Submit"}
									</motion.p>
								</React.Fragment>
							</RichText>
						)}
						{isDisplayed1() && (
							<motion.div
								className={"framer-vdt17o"}
								data-framer-name={"Spinner"}
								layoutDependency={layoutDependency}
								layoutId={"NZ_2jvwet"}
								style={{
									mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
									WebkitMask:
										"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
								}}
							>
								<MotionDivWithFX
									__framer__loop={animation}
									__framer__loopEffectEnabled={true}
									__framer__loopRepeatDelay={0}
									__framer__loopRepeatType={"loop"}
									__framer__loopTransition={transition2}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-10ef29"}
									data-framer-name={"Conic"}
									layoutDependency={layoutDependency}
									layoutId={"pEkt0tdyx"}
									style={{
										background:
											"conic-gradient(from 0deg at 50% 50%, var(--token-992d3a9c-930b-401c-972e-d2075121c037, rgb(30, 30, 31)) 7.208614864864882deg, rgb(255, 255, 255) 342deg)",
										mask: "none",
										WebkitMask: "none",
									}}
									variants={{
										KnD2nQ68i: {
											mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
											WebkitMask:
												"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
										},
									}}
								>
									<motion.div
										className={"framer-klmcxa"}
										data-framer-name={"Rounding"}
										layoutDependency={layoutDependency}
										layoutId={"KUIXSz0GU"}
										style={{
											backgroundColor: "rgb(255, 255, 255)",
											borderBottomLeftRadius: 1,
											borderBottomRightRadius: 1,
											borderTopLeftRadius: 1,
											borderTopRightRadius: 1,
										}}
										transformTemplate={transformTemplate1}
									/>
								</MotionDivWithFX>
							</motion.div>
						)}
					</motion.button>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-klY14.framer-15q63le, .framer-klY14 .framer-15q63le { display: block; }",
	".framer-klY14.framer-18xs4i3 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 40px; justify-content: center; overflow: visible; padding: 8px 16px 8px 16px; position: relative; width: min-content; }",
	".framer-klY14 .framer-11gycud { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-klY14 .framer-vdt17o { aspect-ratio: 1 / 1; flex: none; gap: 10px; height: var(--framer-aspect-ratio-supported, 20px); overflow: hidden; position: relative; width: 20px; }",
	".framer-klY14 .framer-10ef29 { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	".framer-klY14 .framer-klmcxa { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 2px); left: 50%; overflow: visible; position: absolute; top: 0px; width: 2px; }",
	".framer-klY14.framer-v-1gfk0fo.framer-18xs4i3, .framer-klY14.framer-v-1ssq7j3.framer-18xs4i3, .framer-klY14.framer-v-14c8wow.framer-18xs4i3, .framer-klY14.framer-v-z55x4y.framer-18xs4i3 { cursor: unset; }",
	".framer-klY14.framer-v-1gfk0fo .framer-10ef29 { overflow: hidden; }",
	...css,
	'.framer-klY14[data-border="true"]::after, .framer-klY14 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerMo6nJOlmg = withCSS(Component, css2, "framer-klY14");
var stdin_default = FramerMo6nJOlmg;
FramerMo6nJOlmg.displayName = "Buttons/Form";
FramerMo6nJOlmg.defaultProps = {
	height: 40,
	width: 81,
};
addPropertyControls(FramerMo6nJOlmg, {
	variant: {
		options: ["NC44_gCXq", "KnD2nQ68i", "IDfdD9jR7", "iWe_DABvo", "V7CMZLThb"],
		optionTitles: ["Default", "Loading", "Disabled", "Success", "Error"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerMo6nJOlmg,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Geist",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/geist/v4/gyBhhwUxId8gMGYQMKR3pzfaWI_RruM4mJPby1QNtA.woff2",
					weight: "500",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:buttons/form
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "NC44_gCXq",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FormFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var form_default = ComponentWithRoot;
export { form_default as default };
