// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0d2be16cf4ecf57c "Anker (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Hover In' | 'Mobile' // Variant
 * link?: string // Link
}} Props

 */
import { routes } from "../chunks/chunk-QR7ZKMZ2.js";

// virtual:buttons/go-back
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/iEM9YVfq4yz13TnYi8gw/hf1FeiYEx1hVyy2pan2d/ShlWQkRDF.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Link,
	SVG,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["NBo503jZa", "Vjig9rPRZ", "jSWuJLagz"];
var serializationHash = "framer-jdREK";
var variantClassNames = {
	jSWuJLagz: "framer-v-1n2r5cb",
	NBo503jZa: "framer-v-ift5qp",
	Vjig9rPRZ: "framer-v-ftx5zh",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.6,
	ease: [0.08, 0.78, 0.56, 1],
	type: "tween",
};
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Hover In": "Vjig9rPRZ",
	Desktop: "NBo503jZa",
	Mobile: "jSWuJLagz",
};
var getProps = ({ height, id, link, width, ...props }) => {
	return {
		...props,
		F3zKmwx_W: link ?? props.F3zKmwx_W,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "NBo503jZa",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, F3zKmwx_W, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "NBo503jZa",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnter14t1l3n = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		setVariant("Vjig9rPRZ");
	});
	const onMouseLeaveenh470 = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("NBo503jZa");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						motionChild={true}
						nodeId={"NBo503jZa"}
						scopeId={"ShlWQkRDF"}
						{...addPropertyOverrides(
							{
								jSWuJLagz: {
									href: F3zKmwx_W,
								},
								Vjig9rPRZ: {
									href: F3zKmwx_W,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-ift5qp", className, classNames)} framer-1yairxq`}
							data-framer-name={"Desktop"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"NBo503jZa"}
							onMouseEnter={onMouseEnter14t1l3n}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									jSWuJLagz: {
										"data-framer-name": "Mobile",
										"data-highlight": void 0,
										onMouseEnter: void 0,
									},
									Vjig9rPRZ: {
										"data-framer-name": "Hover In",
										onMouseLeave: onMouseLeaveenh470,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-nz8wa2"}
								data-border={true}
								data-framer-name={"Button Wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"bf0ycXYnd"}
								style={{
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-aa4b05ac-cb0a-4952-a6ee-9d49e45f217d, rgb(92, 92, 92))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									borderBottomLeftRadius: "100%",
									borderBottomRightRadius: "100%",
									borderTopLeftRadius: "100%",
									borderTopRightRadius: "100%",
									scale: 1,
								}}
								variants={{
									jSWuJLagz: {
										scale: 1,
									},
									Vjig9rPRZ: {
										scale: 1.2,
									},
								}}
							>
								<motion.div
									className={"framer-b3wdmh"}
									data-framer-name={"Clip"}
									layoutDependency={layoutDependency}
									layoutId={"QIe50egQM"}
								>
									<motion.div
										className={"framer-4ibz1a"}
										data-framer-name={"Arrow Wrapper"}
										layoutDependency={layoutDependency}
										layoutId={"F21Dqctvn"}
										style={{
											rotate: 180,
										}}
										transformTemplate={transformTemplate1}
									>
										<SVG
											className={"framer-1hhwurc"}
											data-framer-name={"Icon"}
											layout={"position"}
											layoutDependency={layoutDependency}
											layoutId={"aQpdYBnqA"}
											opacity={1}
											svg={
												'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 14 14.97"><path d="M 1.288 6.678 L 0.563 6.678 L 0.563 8.126 L 1.288 8.126 Z M 12.552 8.126 C 12.952 8.126 13.276 7.802 13.276 7.402 C 13.276 7.002 12.952 6.678 12.552 6.678 Z M 1.288 8.126 L 12.552 8.126 L 12.552 6.678 L 1.288 6.678 Z" fill="var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255))"></path><path d="M 6.919 1.77 L 12.552 7.402 L 6.919 13.034" fill="transparent" stroke-width="1.45" stroke="var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255))" stroke-linecap="square" stroke-linejoin="round" stroke-dasharray=""></path></svg>'
											}
											svgContentId={12651661979}
											withExternalLayout={true}
										/>
										<SVG
											className={"framer-108o2u8"}
											data-framer-name={"Icon"}
											layout={"position"}
											layoutDependency={layoutDependency}
											layoutId={"TIUwgy2fo"}
											opacity={1}
											svg={
												'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 14 14.97"><path d="M 1.288 6.678 L 0.563 6.678 L 0.563 8.126 L 1.288 8.126 Z M 12.552 8.126 C 12.952 8.126 13.276 7.802 13.276 7.402 C 13.276 7.002 12.952 6.678 12.552 6.678 Z M 1.288 8.126 L 12.552 8.126 L 12.552 6.678 L 1.288 6.678 Z" fill="var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255))"></path><path d="M 6.919 1.77 L 12.552 7.402 L 6.919 13.034" fill="transparent" stroke-width="1.45" stroke="var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255))" stroke-linecap="square" stroke-linejoin="round" stroke-dasharray=""></path></svg>'
											}
											svgContentId={12651661979}
											withExternalLayout={true}
										/>
									</motion.div>
								</motion.div>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-jdREK.framer-1yairxq, .framer-jdREK .framer-1yairxq { display: block; }",
	".framer-jdREK.framer-ift5qp { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 12px; position: relative; width: min-content; }",
	".framer-jdREK .framer-nz8wa2 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 24px; position: relative; width: min-content; z-index: 1; }",
	".framer-jdREK .framer-b3wdmh { flex: none; gap: 10px; height: 20px; overflow: hidden; position: relative; width: 20px; z-index: 2; }",
	".framer-jdREK .framer-4ibz1a { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; left: 2px; overflow: visible; padding: 0px; position: absolute; top: 50%; width: min-content; }",
	".framer-jdREK .framer-1hhwurc, .framer-jdREK .framer-108o2u8 { flex: none; height: 15px; position: relative; width: 14px; }",
	".framer-jdREK.framer-v-ftx5zh.framer-ift5qp, .framer-jdREK.framer-v-1n2r5cb.framer-ift5qp { text-decoration: none; }",
	".framer-jdREK.framer-v-ftx5zh .framer-4ibz1a { left: -24px; }",
	'.framer-jdREK[data-border="true"]::after, .framer-jdREK [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerShlWQkRDF = withCSS(Component, css, "framer-jdREK");
var stdin_default = FramerShlWQkRDF;
FramerShlWQkRDF.displayName = "Buttons/Go Back";
FramerShlWQkRDF.defaultProps = {
	height: 92,
	width: 92,
};
addPropertyControls(FramerShlWQkRDF, {
	variant: {
		options: ["NBo503jZa", "Vjig9rPRZ", "jSWuJLagz"],
		optionTitles: ["Desktop", "Hover In", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	F3zKmwx_W: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerShlWQkRDF,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:buttons/go-back
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "jSWuJLagz",
	xl: "NBo503jZa",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders GoBackFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var go_back_default = ComponentWithRoot;
export { go_back_default as default };
