/**
 * Anker AI Assistant — agentic loop.
 *
 * A ReAct-style JSON tool loop on the local AI provider (Ollama / Anthropic
 * via lib/ai/provider). The model is asked to either call one tool or return
 * a final answer, one JSON object per step. Tools (lib/assistant/tools.ts)
 * give it the same powers used to run the Decile test: web research +
 * crawling, LP matchmaking, investor-profile building, DB query, and
 * spreadsheet / document generation.
 *
 * Local models are weak at strict tool-calling, so parsing is lenient and the
 * loop is bounded; if the model never emits a final answer we force a
 * synthesis step from the transcript.
 */

import { generate } from "@/lib/ai/provider";
import { TOOLS, toolCatalog, type ToolArtifact } from "./tools";
import { DB_SCHEMA_NOTE } from "./db-schema";

export interface AssistantStep {
  thought?: string;
  tool?: string;
  input?: any;
  observation?: string;
  artifact?: ToolArtifact;
  error?: string;
}
export interface AssistantResult {
  answer: string;
  steps: AssistantStep[];
  artifacts: ToolArtifact[];
  provider: "ok" | "no-ai";
}

const SYSTEM = `You are Anker AI, an autonomous venture/fundraising analyst assistant.
You can RESEARCH the web, CRAWL pages, MATCHMAKE LPs against a fund profile,
SCORE/QUALIFY firms against a thesis, ENRICH thin firm records, BUILD investor
profiles, QUERY the firm/LP database, BATCH-DRAFT outreach, and GENERATE
spreadsheets and Word documents — the same workflow (discovery → enrich →
qualify → draft) used to build investor shortlists and deal memos.

Work in steps. At EACH step reply with EXACTLY ONE JSON object and nothing else.

To use a tool:
{"thought": "<short reasoning>", "action": "<tool_name>", "action_input": { ... }}

When you have finished the user's request (including creating any files they
asked for), reply:
{"thought": "<short reasoning>", "final": "<concise answer; mention any files you generated by their download link>"}

Rules:
- Use real data from tools; never invent firms, people, or numbers.
- When the user wants a shortlist/pipeline of LPs, use matchmake_lps (it also
  produces the XLSX). To thesis-score a set, use score_investors. For arbitrary
  tables use generate_spreadsheet; for written deliverables (memos) use
  generate_document (Markdown).
- BATCH, don't loop. To score / draft / enrich MANY investors, call
  score_investors, draft_outreach_batch, or enrich_firms ONCE with a bounded
  limit — each runs the whole batch internally with rate-limiting and failover.
  NEVER issue one AI/tool call per investor; that exhausts the API quota.
- Respect caps: score_investors limit<=40, draft_outreach_batch<=25,
  enrich_firms<=10. If the user needs more, run successive bounded batches.
- Prefer at most 6 tool calls. Be decisive.
- Output ONLY the single JSON object, no prose around it.

Available tools:
`;

function extractJson(text: string): any | null {
  if (!text) return null;
  const start = text.indexOf("{");
  if (start < 0) return null;
  let depth = 0, inStr = false, esc = false;
  for (let i = start; i < text.length; i++) {
    const c = text[i];
    if (inStr) {
      if (esc) esc = false;
      else if (c === "\\") esc = true;
      else if (c === '"') inStr = false;
    } else {
      if (c === '"') inStr = true;
      else if (c === "{") depth++;
      else if (c === "}") { depth--; if (depth === 0) {
        const slice = text.slice(start, i + 1);
        try { return JSON.parse(slice); } catch { return null; }
      } }
    }
  }
  return null;
}

/** Call the model, preferring the deep-research tier but falling back to the
 *  default model if that task is disabled (returns ""). */
async function llm(prompt: string, maxTokens: number): Promise<string> {
  let out = await generate(prompt, { task: "deep_research" as any, json: true, maxTokens, temperature: 0.2 });
  if (!out) out = await generate(prompt, { json: true, maxTokens, temperature: 0.2 });
  return out;
}



/** Resolve `<<IMG1>>` placeholders in tool action_input back to actual
 *  base64 strings before invoking the tool.  Walks objects deeply. */
function resolveImageRefs(value: any, refs?: Array<{ id: string; name: string; base64: string }>): any {
  if (!refs?.length || value == null) return value;
  if (typeof value === "string") {
    return value.replace(/<<(IMG\d+)>>/g, (_, id) => {
      const r = refs.find((x) => x.id === id);
      return r ? r.base64 : `<<${id}-not-found>>`;
    });
  }
  if (Array.isArray(value)) return value.map((v) => resolveImageRefs(v, refs));
  if (typeof value === "object") {
    const out: any = {};
    for (const k of Object.keys(value)) out[k] = resolveImageRefs(value[k], refs);
    return out;
  }
  return value;
}

export async function runAssistant(
  userTask: string,
  opts: { maxSteps?: number; imageRefs?: Array<{ id: string; name: string; base64: string }> } = {},
): Promise<AssistantResult> {
  const maxSteps = Math.min(opts.maxSteps ?? 6, 10);
  const steps: AssistantStep[] = [];
  const artifacts: ToolArtifact[] = [];
  const transcript: string[] = [`USER REQUEST: ${userTask}`];

  // Bail early if there's no AI provider at all.
  console.log("[v0] agent: running probe...")
  const probe = await generate("Reply with the single token: ok", { maxTokens: 5 });
  console.log("[v0] agent: probe result:", probe ? "ok" : "empty")
  if (!probe) {
    return {
      answer:
        "No local AI provider is reachable, so the assistant can't reason through tools right now. " +
        "Start Ollama (`ollama serve` + pull a model) or set ANTHROPIC_API_KEY, then retry. " +
        "The underlying tools (matchmaking, web search, doc generation) still work from their own pages.",
      steps, artifacts, provider: "no-ai",
    };
  }

  let lastSig = "";
  for (let i = 0; i < maxSteps; i++) {
    const prompt =
      SYSTEM + toolCatalog() +
      `\n\n${DB_SCHEMA_NOTE}\n` +
      `\n--- transcript so far ---\n${transcript.join("\n")}\n\n` +
      `Respond with the next single JSON object now.`;
    const raw = await llm(prompt, 800);
    const obj = extractJson(raw);

    if (!obj) {
      // Couldn't parse — treat any prose as the final answer.
      const answer = raw.trim() || "I wasn't able to produce a structured result.";
      steps.push({ thought: "(unstructured model output treated as final)", observation: raw.slice(0, 200) });
      return { answer, steps, artifacts, provider: "ok" };
    }

    if (obj.final || obj.answer) {
      return { answer: String(obj.final ?? obj.answer), steps, artifacts, provider: "ok" };
    }

    const toolName = String(obj.action ?? obj.tool ?? "");
    const input = obj.action_input ?? obj.input ?? obj.args ?? {};
    const tool = TOOLS[toolName];
    if (!tool) {
      const obs = `Unknown tool "${toolName}". Valid tools: ${Object.keys(TOOLS).join(", ")}.`;
      steps.push({ thought: obj.thought, tool: toolName, input, error: obs });
      transcript.push(`STEP ${i + 1}: tried unknown tool "${toolName}". ${obs}`);
      continue;
    }

    // Loop guard: same tool+input twice in a row → stop and synthesize.
    const sig = toolName + JSON.stringify(input);
    if (sig === lastSig) {
      transcript.push(`STEP ${i + 1}: repeated identical call — stopping to synthesize.`);
      break;
    }
    lastSig = sig;

    try {
      const res = await tool.run(input);
      const step: AssistantStep = { thought: obj.thought, tool: toolName, input, observation: res.observation };
      if (res.artifact) { step.artifact = res.artifact; artifacts.push(res.artifact); }
      steps.push(step);
      transcript.push(`STEP ${i + 1}: ${toolName}(${JSON.stringify(input).slice(0, 200)})\nOBSERVATION: ${res.observation}${res.artifact ? `\nFILE: ${res.artifact.url}` : ""}`);
    } catch (e: any) {
      const err = `Tool ${toolName} failed: ${e?.message ?? "error"}`;
      steps.push({ thought: obj.thought, tool: toolName, input, error: err });
      transcript.push(`STEP ${i + 1}: ${err}`);
    }
  }

  // Forced synthesis from the transcript.
  const synth = await llm(
    `You are Anker AI. Based on the transcript below, write a concise final answer for the user. ` +
    `Mention any files generated by their /generated/... link. Reply as JSON {"final": "..."}.\n\n${transcript.join("\n")}`,
    600,
  );
  const obj = extractJson(synth);
  const answer = (obj?.final && String(obj.final)) ||
    synth.trim() ||
    (artifacts.length
      ? `Done. Generated: ${artifacts.map((a) => a.url).join(", ")}.`
      : "I gathered information but couldn't finalize a written answer — see the steps above.");
  return { answer, steps, artifacts, provider: "ok" };
}
