/**
 * Anker AI Assistant — tool registry.
 *
 * Exposes the same capabilities used to run the Decile Capital test as
 * agent-callable tools: web search, web crawling, LP matchmaking,
 * investor-profile building, spreadsheet + document generation, and a
 * read-only investor database query. The agent loop (lib/assistant/agent.ts)
 * drives these via a JSON protocol on the local AI provider.
 *
 * Each tool returns a compact string `observation` (fed back to the model)
 * and optionally an `artifact` (a generated file the user can download).
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import * as XLSX from "xlsx";

import { sql } from "@/lib/db";
import { search as webSearch } from "@/lib/agents/web-search";
import { crawl } from "@/lib/admin/web-crawler";
import { runLpMatching, type FundProfile } from "@/lib/matching/lp-matchmaking";
import { generateLpPipelineXlsx } from "@/lib/matching/xlsx-generator";
import { markdownToDocxBuffer } from "@/lib/ai/docx-export";
import { buildInvestorProfile } from "@/lib/agents/profile-builder";

export interface ToolArtifact { name: string; url: string; kind: "xlsx" | "docx" | "csv" }
export interface ToolResult { observation: string; artifact?: ToolArtifact }
export interface ToolDef {
  name: string;
  description: string;
  /** Human-readable parameter hints shown to the model. */
  params: string;
  run: (input: any) => Promise<ToolResult>;
}

// ── artifact output dir (served from /generated by next start) ───────────────
const OUT_DIR = path.join(process.cwd(), "public", "generated");
async function saveArtifact(buf: Buffer, base: string, kind: ToolArtifact["kind"]): Promise<ToolArtifact> {
  await fs.mkdir(OUT_DIR, { recursive: true });
  const safe = base.replace(/[^a-z0-9_-]+/gi, "_").slice(0, 60) || "output";
  const file = `${safe}_${randomUUID().slice(0, 8)}.${kind}`;
  await fs.writeFile(path.join(OUT_DIR, file), buf);
  return { name: file, url: `/generated/${file}`, kind };
}

function clip(s: string, n = 1500): string {
  s = (s ?? "").replace(/\s+/g, " ").trim();
  return s.length > n ? s.slice(0, n) + " …[truncated]" : s;
}

// ── tools ────────────────────────────────────────────────────────────────────
export const TOOLS: Record<string, ToolDef> = {
  web_search: {
    name: "web_search",
    description: "Search the web (via SearXNG) for current information, companies, people, or facts.",
    params: `{ "query": string, "limit"?: number }`,
    async run({ query, limit }) {
      const hits = await webSearch(String(query ?? ""), { limit: Math.min(Number(limit) || 6, 10) });
      if (!hits.length) return { observation: `No results for "${query}". SearXNG may be offline (SEARXNG_URL).` };
      const lines = hits.map((h, i) => `${i + 1}. ${h.title}\n   ${h.url}\n   ${clip(h.snippet, 220)}`);
      return { observation: `Top results for "${query}":\n` + lines.join("\n") };
    },
  },

  web_crawl: {
    name: "web_crawl",
    description: "Fetch and extract the clean main text of a single web page (use a URL from web_search).",
    params: `{ "url": string }`,
    async run({ url }) {
      const u = String(url ?? "");
      if (!/^https?:\/\//.test(u)) return { observation: "Provide a full http(s) URL." };
      try {
        const page = await crawl(u);
        const title = (page as any).title || (page as any).metadata?.title || u;
        const text = (page as any).text || (page as any).content || "";
        return { observation: `Page: ${title}\nURL: ${u}\n\n${clip(text, 2500)}` };
      } catch (e: any) {
        return { observation: `Failed to crawl ${u}: ${e?.message ?? "error"}` };
      }
    },
  },

  matchmake_lps: {
    name: "matchmake_lps",
    description: "Score the investor database for LP fit against a fund's profile and produce a ranked pipeline + an XLSX. Use for fundraising / finding family offices, funds-of-funds, and other LPs.",
    params: `{ "fundName": string, "targetRaiseUsd"?: number, "sectors"?: string[], "geographicFocus"?: string[], "headquarters"?: string, "thesisKeywords"?: string[], "preferLesserKnown"?: boolean, "rightSizeToTarget"?: boolean, "excludeHouseholdNames"?: boolean, "top"?: number }`,
    async run(inp) {
      const profile: FundProfile = {
        id: `assistant_${Date.now()}`,
        name: String(inp.fundName ?? "Fund"),
        targetRaise: Number(inp.targetRaiseUsd) || null,
        sectors: Array.isArray(inp.sectors) ? inp.sectors : [],
        geographicFocus: Array.isArray(inp.geographicFocus) ? inp.geographicFocus : [],
        headquartersLocation: inp.headquarters ?? null,
        thesisKeywords: Array.isArray(inp.thesisKeywords) ? inp.thesisKeywords : [],
        preferLesserKnown: !!inp.preferLesserKnown,
        rightSizeToTarget: inp.rightSizeToTarget !== false,
        excludeHouseholdNames: !!inp.excludeHouseholdNames,
      };
      const top = Math.min(Number(inp.top) || 10, 50);
      const result = await runLpMatching(profile, { maxFirms: 500, maxContacts: 500 });
      const firms = result.firms.slice(0, top);
      const contacts = result.contacts.slice(0, top);
      const xlsx = generateLpPipelineXlsx(result);
      const artifact = await saveArtifact(xlsx, `LP_Pipeline_${profile.name}`, "xlsx");
      const fLines = firms.map((f, i) => `${i + 1}. ${f.name} — ${f.score} (${f.tier}) ${f.tags.join(",")} | ${f.location} | ${f.aum}`);
      const cLines = contacts.map((c, i) => `${i + 1}. ${c.name} (${c.title}) @ ${c.type} — ${c.score} ${c.email ? "✉" : ""}`);
      return {
        observation:
          `Scored ${result.totalFirmsScored} firms + ${result.totalContactsScored} investors for "${profile.name}".\n` +
          `Qualified: ${result.qualifiedFirms} firms, ${result.qualifiedContacts} contacts; ${result.anchorCandidates} anchors; ${result.contactsWithEmail} with email.\n\n` +
          `Top firms:\n${fLines.join("\n") || "(none)"}\n\nTop contacts:\n${cLines.join("\n") || "(none)"}`,
        artifact,
      };
    },
  },

  build_investor_profile: {
    name: "build_investor_profile",
    description: "Build an enriched profile (thesis, hooks, recent signals) for one investor or firm, by id or name. Used to prep tailored outreach.",
    params: `{ "investorId"?: string, "firmId"?: string }`,
    async run(inp) {
      try {
        const p: any = await buildInvestorProfile({ investorId: inp.investorId, firmId: inp.firmId });
        return {
          observation:
            `Profile: ${p.headline ?? ""}\n` +
            `Primary hook: ${p.primaryHook?.text ?? p.talkingPoints?.[0] ?? "n/a"}\n` +
            `Fund thesis: ${p.fundThesis ?? "n/a"}\n` +
            `Talking points: ${(p.talkingPoints ?? []).slice(0, 4).join(" | ")}\n` +
            `Urgency: ${p.urgency ?? "n/a"}`,
        };
      } catch (e: any) {
        return { observation: `Profile build failed: ${e?.message ?? "error"}` };
      }
    },
  },

  query_investors: {
    name: "query_investors",
    description: "Read-only search of the Anker firm/LP database (table: investment_firms — family offices, VCs, funds-of-funds, accelerators, corporates, PE). Filter by type and/or a keyword (matched on name, description, sectors, industry, location). Note: the 'investors' table is PEOPLE (first_name/last_name); firm-type LPs like family offices live in investment_firms.",
    params: `{ "type"?: "family-office"|"vc"|"accelerator"|"corporate"|"angel"|"private-equity", "keyword"?: string, "limit"?: number }`,
    async run(inp) {
      const limit = Math.min(Number(inp.limit) || 15, 50);
      const kwRaw = inp.keyword ? String(inp.keyword).toLowerCase().trim() : "";
      const kw = kwRaw ? `%${kwRaw}%` : null;
      const typeRaw = inp.type ? String(inp.type).toLowerCase().trim() : "";
      // The firm `type` column is free-text and inconsistent ("VC", "VC Firm",
      // "Venture Capital", "Family Office"...). Match on a punctuation-stripped
      // normalized form against a set of known variants for each requested type.
      const TYPE_PATTERNS: Record<string, string[]> = {
        "family-office": ["familyoffice", "wealth", "multifamilyoffice", "singlefamilyoffice"],
        "vc": ["vc", "venturecapital", "venture"],
        "accelerator": ["accelerator", "incubator"],
        "corporate": ["corporate", "cvc"],
        "angel": ["angel"],
        "private-equity": ["privateequity", "growthequity"],
      };
      const patterns = typeRaw
        ? (TYPE_PATTERNS[typeRaw] ?? [typeRaw.replace(/[^a-z0-9]/g, "")]).map((p) => `%${p}%`)
        : null;
      // keyword condition reused across branches (built inline per the sql tag).
      let rows: any[];
      if (patterns && kw) {
        rows = await sql`SELECT name, type, coalesce(hq_location, location) AS location, website, emails
          FROM investment_firms
          WHERE regexp_replace(lower(coalesce(type,'')), '[^a-z0-9]', '', 'g') LIKE ANY(${patterns})
            AND (lower(coalesce(name,'')) LIKE ${kw} OR lower(coalesce(description,'')) LIKE ${kw}
                 OR lower(coalesce(sectors::text,'')) LIKE ${kw} OR lower(coalesce(industry,'')) LIKE ${kw}
                 OR lower(coalesce(hq_location,'') || ' ' || coalesce(location,'')) LIKE ${kw})
          ORDER BY portfolio_count DESC NULLS LAST LIMIT ${limit}`;
      } else if (patterns) {
        rows = await sql`SELECT name, type, coalesce(hq_location, location) AS location, website, emails
          FROM investment_firms
          WHERE regexp_replace(lower(coalesce(type,'')), '[^a-z0-9]', '', 'g') LIKE ANY(${patterns})
          ORDER BY portfolio_count DESC NULLS LAST LIMIT ${limit}`;
      } else if (kw) {
        rows = await sql`SELECT name, type, coalesce(hq_location, location) AS location, website, emails
          FROM investment_firms
          WHERE (lower(coalesce(name,'')) LIKE ${kw} OR lower(coalesce(description,'')) LIKE ${kw}
                 OR lower(coalesce(sectors::text,'')) LIKE ${kw} OR lower(coalesce(industry,'')) LIKE ${kw}
                 OR lower(coalesce(hq_location,'') || ' ' || coalesce(location,'')) LIKE ${kw})
          ORDER BY portfolio_count DESC NULLS LAST LIMIT ${limit}`;
      } else {
        rows = await sql`SELECT name, type, coalesce(hq_location, location) AS location, website, emails
          FROM investment_firms ORDER BY portfolio_count DESC NULLS LAST LIMIT ${limit}`;
      }
      if (!rows.length) return { observation: "No matching firms in investment_firms for those filters." };
      const fmtEmail = (e: any): string => {
        if (Array.isArray(e)) { const s = e.find((x) => typeof x === "string"); return s ?? ""; }
        return typeof e === "string" ? e : "";
      };
      return {
        observation: rows.map((r: any, i: number) =>
          `${i + 1}. ${r.name} [${r.type ?? "—"}] ${r.location ?? ""} ${fmtEmail(r.emails)}`.trim()).join("\n"),
      };
    },
  },

  generate_spreadsheet: {
    name: "generate_spreadsheet",
    description: "Create an .xlsx file from a header row and data rows. Returns a download link.",
    params: `{ "title": string, "columns": string[], "rows": (string|number)[][] }`,
    async run(inp) {
      const columns: string[] = Array.isArray(inp.columns) ? inp.columns.map(String) : [];
      const rows: any[][] = Array.isArray(inp.rows) ? inp.rows : [];
      if (!columns.length) return { observation: "Provide a non-empty 'columns' array." };
      const ws = XLSX.utils.aoa_to_sheet([columns, ...rows]);
      ws["!cols"] = columns.map(() => ({ wch: 22 }));
      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
      const buf = XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) as Buffer;
      const artifact = await saveArtifact(buf, String(inp.title ?? "spreadsheet"), "xlsx");
      return { observation: `Spreadsheet created with ${rows.length} rows × ${columns.length} cols → ${artifact.url}`, artifact };
    },
  },

  generate_document: {
    name: "generate_document",
    description: "Create a formatted .docx from Markdown (use # / ## headings, **bold**, - bullets). Returns a download link.",
    params: `{ "title": string, "markdown": string }`,
    async run(inp) {
      const md = String(inp.markdown ?? "");
      if (!md.trim()) return { observation: "Provide non-empty 'markdown'." };
      const buf = await markdownToDocxBuffer(md, inp.title ? String(inp.title) : undefined);
      const artifact = await saveArtifact(buf, String(inp.title ?? "document"), "docx");
      return { observation: `Document created (${md.length} chars of Markdown) → ${artifact.url}`, artifact };
    },
  },
};

export function toolCatalog(): string {
  return Object.values(TOOLS)
    .map((t) => `- ${t.name}: ${t.description}\n  input: ${t.params}`)
    .join("\n");
}
