/**
 * Newsroom slug helpers.
 *
 * Two responsibilities:
 *
 *   1. slugify(text)           — deterministic, URL-safe slug from a headline.
 *                                Matches the SQL backfill in
 *                                scripts/migrations/2026-06-20-newsroom-polish.sql
 *                                so a slug computed in TS for a newly-created
 *                                article looks the same as one generated by
 *                                the migration for legacy rows.
 *
 *   2. isLikelyUuid(s)         — cheap shape-check used by the public
 *                                /newsroom/[slug] route to decide whether to
 *                                lookup by id (legacy UUID URL still alive
 *                                in someone's bookmarks) or by slug.
 *                                We use shape rather than a DB round-trip
 *                                because slugs never contain a hyphen-separated
 *                                hex group structure.
 *
 *   3. ensureUniqueSlug(base, existsFn) — when the API creates a new article,
 *                                give it a base slug and a probe; if the base
 *                                is taken, append -2, -3, … until clean.
 *                                Avoids the migration's "-<first-6-of-id>"
 *                                suffix which would leak the UUID into the URL.
 */

const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

export function isLikelyUuid(s: string): boolean {
  return UUID_RE.test(s.trim())
}

/**
 * Lowercase the headline, strip apostrophes/quotes, collapse any run of
 * non-alphanumerics to a single hyphen, trim leading/trailing hyphens, and
 * cap length at 70 chars at the nearest word boundary.
 *
 * Mirrors the SQL recipe in 2026-06-20-newsroom-polish.sql, minus the
 * "-<first-6-of-id>" suffix (TS callers should pass the result through
 * ensureUniqueSlug before insert).
 */
export function slugify(input: string): string {
  if (!input) return ""
  const lowered = input.toLowerCase()
  const stripped = lowered.replace(/[''"`]/g, "")
  const hyphenated = stripped.replace(/[^a-z0-9]+/g, "-")
  const trimmed = hyphenated.replace(/^-+|-+$/g, "")
  if (trimmed.length <= 70) return trimmed
  // Cap at 70 chars but back off to the previous word boundary (if any).
  const cut = trimmed.slice(0, 70)
  const lastHyphen = cut.lastIndexOf("-")
  return lastHyphen > 40 ? cut.slice(0, lastHyphen) : cut
}

/**
 * Given a base slug and a probe that returns true when a slug is already
 * taken, return a slug that's free.  Walks "base", "base-2", "base-3", …
 * up to a small cap to avoid pathological loops.
 */
export async function ensureUniqueSlug(
  base: string,
  existsFn: (slug: string) => Promise<boolean>,
): Promise<string> {
  const cleaned = base || "article"
  if (!(await existsFn(cleaned))) return cleaned
  for (let i = 2; i < 50; i++) {
    const candidate = `${cleaned}-${i}`
    if (!(await existsFn(candidate))) return candidate
  }
  // Fallback: timestamp tail — extremely unlikely to collide.
  return `${cleaned}-${Date.now().toString(36).slice(-6)}`
}
