// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0d2be16cf4ecf57c "Anker (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Closed' | 'Opened' // Variant
 * question?: string // Question
 * answer?: string // Answer
 * click?: Function // Click
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-OCTLECST.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-BRGTNG7B.js";
import { routes } from "./chunks/chunk-QR7ZKMZ2.js";

// virtual:accordion
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/Aisl2HhBFUSEBqCJSKyf/Eb3Tlewt2mys3FRX4qCk/EkfhhiLCf.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["KJk8QbTmY", "vZ5WwwktB"];
var serializationHash = "framer-ZlKTN";
var variantClassNames = {
	KJk8QbTmY: "framer-v-1w45l6n",
	vZ5WwwktB: "framer-v-o96l8",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.7,
	ease: [0.14, 0.87, 0.56, 1],
	type: "tween",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Closed: "KJk8QbTmY",
	Opened: "vZ5WwwktB",
};
var getProps = ({ answer, click, height, id, question, width, ...props }) => {
	return {
		...props,
		DR_6QqGeh:
			answer ??
			props.DR_6QqGeh ??
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
		qQefXa5XK: question ?? props.qQefXa5XK ?? "Lorem Ipsum",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "KJk8QbTmY",
		Z3jnJDFUJ: click ?? props.Z3jnJDFUJ,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		qQefXa5XK,
		DR_6QqGeh,
		Z3jnJDFUJ,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "KJk8QbTmY",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1d62nly = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (Z3jnJDFUJ) {
			const res = await Z3jnJDFUJ(...args);
			if (res === false) return false;
		}
		setVariant("vZ5WwwktB");
	});
	const onTap18nrmvm = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (Z3jnJDFUJ) {
			const res = await Z3jnJDFUJ(...args);
			if (res === false) return false;
		}
		setVariant("KJk8QbTmY");
	});
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Image
						{...restProps}
						{...gestureHandlers}
						background={{
							alt: "",
							backgroundSize: 1,
							fit: "tile",
							loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
							pixelHeight: 320,
							pixelWidth: 500,
							positionX: "left",
							positionY: "top",
							src: "https://framerusercontent.com/images/0Ca9IKq34gDgncIgBLTqeKyuFB8.png?width=500&height=320",
						}}
						className={cx(
							scopingClassNames,
							"framer-1w45l6n",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Closed"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"KJk8QbTmY"}
						onTap={onTap1d62nly}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-2af2796e-c98f-415f-bfdd-4cf975fb4b80, rgb(43, 43, 43))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							...style,
						}}
						{...addPropertyOverrides(
							{
								vZ5WwwktB: {
									"data-framer-name": "Opened",
									onTap: onTap18nrmvm,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1ya0de7"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"fkk0lsI8L"}
						>
							<motion.div
								className={"framer-130q6ld"}
								data-framer-name={"Question"}
								layoutDependency={layoutDependency}
								layoutId={"ZDtlsjUlP"}
							>
								<motion.div
									className={"framer-163bkls"}
									data-framer-name={"Text"}
									layoutDependency={layoutDependency}
									layoutId={"chVlr9i6x"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1br8y94"}
										data-framer-name={"Question"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"WsLaTtias"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={qQefXa5XK}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.h5
												className={"framer-styles-preset-v2uh97"}
												data-styles-preset={"hgRR2OlAI"}
											>
												{"What is Framer?"}
											</motion.h5>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.button
									className={"framer-k17afw"}
									data-framer-name={"Icon"}
									data-reset={"button"}
									layoutDependency={layoutDependency}
									layoutId={"crCaaLdIR"}
									style={{
										backgroundColor:
											"var(--token-2af2796e-c98f-415f-bfdd-4cf975fb4b80, rgb(43, 43, 43))",
										borderBottomLeftRadius: 6,
										borderBottomRightRadius: 6,
										borderTopLeftRadius: 6,
										borderTopRightRadius: 6,
									}}
								>
									<motion.div
										className={"framer-s9bebu"}
										data-framer-name={"Horizontal"}
										layoutDependency={layoutDependency}
										layoutId={"kLhaxAgU0"}
										style={{
											backgroundColor:
												"var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255))",
											rotate: -90,
										}}
										variants={{
											vZ5WwwktB: {
												rotate: 90,
											},
										}}
									/>
									<motion.div
										className={"framer-1fylgxb"}
										data-framer-name={"Vertical"}
										layoutDependency={layoutDependency}
										layoutId={"SZ8w5RwJy"}
										style={{
											backgroundColor:
												"var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255))",
											rotate: -180,
										}}
										variants={{
											vZ5WwwktB: {
												rotate: 90,
											},
										}}
									/>
								</motion.button>
							</motion.div>
							<motion.div
								className={"framer-acfnx3"}
								data-framer-name={"Answer"}
								layoutDependency={layoutDependency}
								layoutId={"KwIjA3YzW"}
								style={{
									opacity: 0,
								}}
								transformTemplate={transformTemplate1}
								variants={{
									vZ5WwwktB: {
										opacity: 1,
									},
								}}
								{...addPropertyOverrides(
									{
										vZ5WwwktB: {
											transformTemplate: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-4w0lur"}
									data-framer-name={"Answer"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"aMHHisiHX"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={DR_6QqGeh}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											vZ5WwwktB: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-cpwznz"}
															data-styles-preset={"ls_KuhAAC"}
														>
															{
																"Framer is a design tool that allows you to design websites on a freeform canvas, and then publish them as websites with a single click."
															}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--framer-letter-spacing": "-0.04em",
												"--framer-line-height": "140%",
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255)))",
											}}
										>
											{
												"Framer is a design tool that allows you to design websites on a freeform canvas, and then publish them as websites with a single click."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
					</Image>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ZlKTN.framer-108siq8, .framer-ZlKTN .framer-108siq8 { display: block; }",
	".framer-ZlKTN.framer-1w45l6n { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 24px; position: relative; width: 391px; will-change: var(--framer-will-change-override, transform); }",
	".framer-ZlKTN .framer-1ya0de7 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-ZlKTN .framer-130q6ld { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-ZlKTN .framer-163bkls { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-ZlKTN .framer-1br8y94, .framer-ZlKTN .framer-4w0lur { -webkit-user-select: none; flex: 1 0 0px; height: auto; position: relative; user-select: none; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-ZlKTN .framer-k17afw { aspect-ratio: 1 / 1; cursor: pointer; flex: none; height: var(--framer-aspect-ratio-supported, 28px); overflow: hidden; position: relative; width: 28px; will-change: var(--framer-will-change-override, transform); }",
	".framer-ZlKTN .framer-s9bebu, .framer-ZlKTN .framer-1fylgxb { flex: none; height: 12px; left: calc(50.00000000000002% - 1px / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 12px / 2); width: 1px; }",
	".framer-ZlKTN .framer-acfnx3 { align-content: center; align-items: center; bottom: -120px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; left: 50%; overflow: hidden; padding: 0px; pointer-events: none; position: absolute; width: 100%; z-index: 1; }",
	".framer-ZlKTN.framer-v-o96l8 .framer-acfnx3 { bottom: unset; left: unset; position: relative; }",
	...css,
	...css2,
	'.framer-ZlKTN[data-border="true"]::after, .framer-ZlKTN [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerEkfhhiLCf = withCSS(Component, css3, "framer-ZlKTN");
var stdin_default = FramerEkfhhiLCf;
FramerEkfhhiLCf.displayName = "Accordion";
FramerEkfhhiLCf.defaultProps = {
	height: 76,
	width: 391,
};
addPropertyControls(FramerEkfhhiLCf, {
	variant: {
		options: ["KJk8QbTmY", "vZ5WwwktB"],
		optionTitles: ["Closed", "Opened"],
		title: "Variant",
		type: ControlType.Enum,
	},
	qQefXa5XK: {
		defaultValue: "Lorem Ipsum",
		displayTextArea: false,
		title: "Question",
		type: ControlType.String,
	},
	DR_6QqGeh: {
		defaultValue:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
		displayTextArea: true,
		title: "Answer",
		type: ControlType.String,
	},
	Z3jnJDFUJ: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramerEkfhhiLCf,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:accordion
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "KJk8QbTmY",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AccordionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var accordion_default = ComponentWithRoot;
export { accordion_default as default };
