// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0d2be16cf4ecf57c "Anker (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * category?: string // Category
 * border?: undefined // Border
 * fill?: string // Fill
 * description?: string // Description
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-CY3UIAJF.js";
import { className, css, fonts } from "./chunks/chunk-BRGTNG7B.js";
import { routes } from "./chunks/chunk-QR7ZKMZ2.js";

// virtual:category-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/dootQHE1f7BmOEsM6ItL/aOg34qGLZ3XGx3WpdNja/RtW0fnac_.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-OGsJU";
var variantClassNames = {
	ZWHqSVJuD: "framer-v-1us2rix",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	border,
	category,
	description,
	fill,
	height,
	id,
	width,
	...props
}) => {
	return {
		...props,
		eWMB84p69:
			description ??
			props.eWMB84p69 ??
			"Hydra is a pioneering clean energy company that delivers innovative infrastructure ",
		hCJoLic6r: border ??
			props.hCJoLic6r ?? {
				borderBottomWidth: 0,
				borderColor:
					'var(--token-fc93a552-c67c-4656-b24f-43dbc72778fe, rgb(255, 0, 191)) /* {"name":"Pink"} */',
				borderLeftWidth: 0,
				borderRightWidth: 0,
				borderStyle: "solid",
				borderTopWidth: 1,
			},
		ve2zGc6au: category ?? props.ve2zGc6au ?? "Cyrpto",
		y9G8u5K8C:
			fill ??
			props.y9G8u5K8C ??
			"var(--token-fc93a552-c67c-4656-b24f-43dbc72778fe, rgb(255, 0, 191))",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		ve2zGc6au,
		hCJoLic6r,
		y9G8u5K8C,
		eWMB84p69,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "ZWHqSVJuD",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Image
						{...restProps}
						{...gestureHandlers}
						background={{
							alt: "",
							fit: "fill",
							loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
							pixelHeight: 320,
							pixelWidth: 500,
							src: "https://framerusercontent.com/images/0Ca9IKq34gDgncIgBLTqeKyuFB8.png?width=500&height=320",
						}}
						className={cx(
							scopingClassNames,
							"framer-1us2rix",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"ZWHqSVJuD"}
						ref={refBinding}
						style={{
							"--border-bottom-width":
								(hCJoLic6r.borderBottomWidth ?? hCJoLic6r.borderWidth) + "px",
							"--border-color": hCJoLic6r.borderColor,
							"--border-left-width":
								(hCJoLic6r.borderLeftWidth ?? hCJoLic6r.borderWidth) + "px",
							"--border-right-width":
								(hCJoLic6r.borderRightWidth ?? hCJoLic6r.borderWidth) + "px",
							"--border-style": hCJoLic6r.borderStyle,
							"--border-top-width":
								(hCJoLic6r.borderTopWidth ?? hCJoLic6r.borderWidth) + "px",
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							...style,
						}}
					>
						<motion.div
							className={"framer-14pw7xi"}
							data-framer-name={"Overlay Full"}
							layoutDependency={layoutDependency}
							layoutId={"VN_s3CIxZ"}
							style={{
								backgroundColor: y9G8u5K8C,
								opacity: 0.03,
							}}
						/>
						<motion.div
							className={"framer-ob7nfk"}
							data-framer-name={"Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"AOERHBney"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-hg89bn"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"DeHU6FymG"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={ve2zGc6au}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h3
										className={"framer-styles-preset-lt59i6"}
										data-styles-preset={"FC2ASH74m"}
									>
										{"Cyrpto"}
									</motion.h3>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							className={"framer-zu6t8w"}
							data-framer-name={"Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"Ve04Sx37S"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1kchwvv"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"m_15URuNr"}
								text={eWMB84p69}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-cpwznz"}
										data-styles-preset={"ls_KuhAAC"}
										style={{
											"--framer-text-alignment": "left",
										}}
									>
										{
											"Hydra is a pioneering clean energy company that delivers innovative infrastructure "
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</Image>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-OGsJU.framer-1eod52, .framer-OGsJU .framer-1eod52 { display: block; }",
	".framer-OGsJU.framer-1us2rix { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; height: 338px; justify-content: space-between; overflow: var(--overflow-clip-fallback, clip); padding: 24px; position: relative; width: 295px; will-change: var(--framer-will-change-override, transform); }",
	".framer-OGsJU .framer-14pw7xi { bottom: 0px; flex: none; left: 0px; overflow: hidden; pointer-events: none; position: absolute; right: 0px; top: 0px; }",
	".framer-OGsJU .framer-ob7nfk { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-OGsJU .framer-hg89bn { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-OGsJU .framer-zu6t8w { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-OGsJU .framer-1kchwvv { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	...css2,
	...css,
	'.framer-OGsJU[data-border="true"]::after, .framer-OGsJU [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerRtW0fnac_ = withCSS(Component, css3, "framer-OGsJU");
var stdin_default = FramerRtW0fnac_;
FramerRtW0fnac_.displayName = "Category Card";
FramerRtW0fnac_.defaultProps = {
	height: 338,
	width: 295,
};
addPropertyControls(FramerRtW0fnac_, {
	ve2zGc6au: {
		defaultValue: "Cyrpto",
		displayTextArea: false,
		title: "Category",
		type: ControlType.String,
	},
	hCJoLic6r: {
		defaultValue: {
			borderBottomWidth: 0,
			borderColor:
				'var(--token-fc93a552-c67c-4656-b24f-43dbc72778fe, rgb(255, 0, 191)) /* {"name":"Pink"} */',
			borderLeftWidth: 0,
			borderRightWidth: 0,
			borderStyle: "solid",
			borderTopWidth: 1,
		},
		title: "Border",
		type: ControlType.Border,
	},
	y9G8u5K8C: {
		defaultValue:
			'var(--token-fc93a552-c67c-4656-b24f-43dbc72778fe, rgb(255, 0, 191)) /* {"name":"Pink"} */',
		title: "Fill",
		type: ControlType.Color,
	},
	eWMB84p69: {
		defaultValue:
			"Hydra is a pioneering clean energy company that delivers innovative infrastructure ",
		displayTextArea: false,
		title: "Description",
		type: ControlType.String,
	},
});
addFonts(
	FramerRtW0fnac_,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:category-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CategoryCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var category_card_default = ComponentWithRoot;
export { category_card_default as default };
