// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0d2be16cf4ecf57c "Anker (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'All closed' | 'Question 1 / Opened' | 'Question 2 / Opened' | 'Question 3 / Opened' | 'Question 4 / Opened' | 'Question 5 / Opened' | 'Question 6 / Opened' // Variant
 * question1?: string // Question 1
 * answer1?: string // Answer 1
 * question2?: string // Question 2
 * answer2?: string // Answer 2
 * question3?: string // Question 3
 * answer3?: string // Answer 3
 * question4?: string // Question 4
 * answer4?: string // Answer 4
 * question5?: string // Question 5
 * answer5?: string // Answer 5
 * question6?: string // Question 6
 * answer6?: string // Answer 6
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-OCTLECST.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-BRGTNG7B.js";
import { routes } from "./chunks/chunk-QR7ZKMZ2.js";

// virtual:faq
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/vikFeKSKDrU6r5u6ANbn/RUiGKwy5iRJlkOkmYvdp/kAuAu8IYD.js
import { jsx as _jsx3, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider,
	ControlType as ControlType3,
	cx as cx2,
	getFonts,
	SmartComponentScopedContainer,
	useActiveVariantCallback as useActiveVariantCallback2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/h8ioHyt4BUxuvVCE1Q10/aTM6mEMGlM19JjX8exDe/AvoidLayoutJumping_Prod.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
import { useEffect, useRef } from "react";
function AvoidLayoutJumping({ direction, style }) {
	const isCanvas = RenderTarget.current() === RenderTarget.canvas;
	const ref = useRef(null);
	const rafId = useRef();
	const vertical = direction === "vertical" || direction === "both";
	const horizontal = direction === "horizontal" || direction === "both";
	useEffect(() => {
		if (isCanvas) return;
		const parent = ref.current?.parentElement?.parentElement;
		if (!parent) return;
		const container = parent.parentElement;
		if (!container) return;
		const updateSize = () => {
			const rect = parent.getBoundingClientRect();
			if (horizontal) {
				container.style.width = `${rect.width}px`;
			}
			if (vertical) {
				container.style.height = `${rect.height}px`;
			}
			rafId.current = requestAnimationFrame(updateSize);
		};
		rafId.current = requestAnimationFrame(updateSize);
		return () => {
			if (rafId.current) {
				cancelAnimationFrame(rafId.current);
			}
			if (container) {
				if (horizontal) {
					container.style.width = "";
				}
				if (vertical) {
					container.style.height = "";
				}
			}
		};
	}, [direction]);
	return (
		<div
			ref={ref}
			style={{
				...style,
			}}
		/>
	);
}
AvoidLayoutJumping.displayName = "Layout Jump Preventer";
addPropertyControls(AvoidLayoutJumping, {
	direction: {
		type: ControlType.Enum,
		defaultValue: "vertical",
		options: ["vertical", "horizontal", "both"],
		optionTitles: ["Vertical", "Horizontal", "Both"],
		displaySegmentedControl: true,
		segmentedControlDirection: "vertical",
		// @ts-ignore
		optionIcons: [
			"direction-vertical",
			"direction-horizontal",
			"direction-all",
		],
		description:
			"More components at [Framer University](https://frameruni.link/cc).",
	},
});

// /:https://framerusercontent.com/modules/VNzFffVgCBdwmdqW4x7S/IM3n0KKJkqSfif1XXMtY/EkfhhiLCf.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";
var cycleOrder = ["KJk8QbTmY", "vZ5WwwktB"];
var serializationHash = "framer-ZlKTN";
var variantClassNames = {
	KJk8QbTmY: "framer-v-1w45l6n",
	vZ5WwwktB: "framer-v-o96l8",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.7,
	ease: [0.14, 0.87, 0.56, 1],
	type: "tween",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Closed: "KJk8QbTmY",
	Opened: "vZ5WwwktB",
};
var getProps = ({ answer, click, height, id, question, width, ...props }) => {
	return {
		...props,
		DR_6QqGeh:
			answer ??
			props.DR_6QqGeh ??
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
		qQefXa5XK: question ?? props.qQefXa5XK ?? "Lorem Ipsum",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "KJk8QbTmY",
		Z3jnJDFUJ: click ?? props.Z3jnJDFUJ,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		qQefXa5XK,
		DR_6QqGeh,
		Z3jnJDFUJ,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "KJk8QbTmY",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1d62nly = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (Z3jnJDFUJ) {
			const res = await Z3jnJDFUJ(...args);
			if (res === false) return false;
		}
		setVariant("vZ5WwwktB");
	});
	const onTap18nrmvm = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (Z3jnJDFUJ) {
			const res = await Z3jnJDFUJ(...args);
			if (res === false) return false;
		}
		setVariant("KJk8QbTmY");
	});
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Image
						{...restProps}
						{...gestureHandlers}
						background={{
							alt: "",
							backgroundSize: 1,
							fit: "tile",
							loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
							pixelHeight: 320,
							pixelWidth: 500,
							positionX: "left",
							positionY: "top",
							src: "https://framerusercontent.com/images/0Ca9IKq34gDgncIgBLTqeKyuFB8.png?width=500&height=320",
						}}
						className={cx(
							scopingClassNames,
							"framer-1w45l6n",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Closed"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"KJk8QbTmY"}
						onTap={onTap1d62nly}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-2af2796e-c98f-415f-bfdd-4cf975fb4b80, rgb(43, 43, 43))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							...style,
						}}
						{...addPropertyOverrides(
							{
								vZ5WwwktB: {
									"data-framer-name": "Opened",
									onTap: onTap18nrmvm,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1ya0de7"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"fkk0lsI8L"}
						>
							<motion.div
								className={"framer-130q6ld"}
								data-framer-name={"Question"}
								layoutDependency={layoutDependency}
								layoutId={"ZDtlsjUlP"}
							>
								<motion.div
									className={"framer-163bkls"}
									data-framer-name={"Text"}
									layoutDependency={layoutDependency}
									layoutId={"chVlr9i6x"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1br8y94"}
										data-framer-name={"Question"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"WsLaTtias"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={qQefXa5XK}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.h5
												className={"framer-styles-preset-v2uh97"}
												data-styles-preset={"hgRR2OlAI"}
											>
												{"What is Framer?"}
											</motion.h5>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.button
									className={"framer-k17afw"}
									data-framer-name={"Icon"}
									data-reset={"button"}
									layoutDependency={layoutDependency}
									layoutId={"crCaaLdIR"}
									style={{
										backgroundColor:
											"var(--token-2af2796e-c98f-415f-bfdd-4cf975fb4b80, rgb(43, 43, 43))",
										borderBottomLeftRadius: 6,
										borderBottomRightRadius: 6,
										borderTopLeftRadius: 6,
										borderTopRightRadius: 6,
									}}
								>
									<motion.div
										className={"framer-s9bebu"}
										data-framer-name={"Horizontal"}
										layoutDependency={layoutDependency}
										layoutId={"kLhaxAgU0"}
										style={{
											backgroundColor:
												"var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255))",
											rotate: -90,
										}}
										variants={{
											vZ5WwwktB: {
												rotate: 90,
											},
										}}
									/>
									<motion.div
										className={"framer-1fylgxb"}
										data-framer-name={"Vertical"}
										layoutDependency={layoutDependency}
										layoutId={"SZ8w5RwJy"}
										style={{
											backgroundColor:
												"var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255))",
											rotate: -180,
										}}
										variants={{
											vZ5WwwktB: {
												rotate: 90,
											},
										}}
									/>
								</motion.button>
							</motion.div>
							<motion.div
								className={"framer-acfnx3"}
								data-framer-name={"Answer"}
								layoutDependency={layoutDependency}
								layoutId={"KwIjA3YzW"}
								style={{
									opacity: 0,
								}}
								transformTemplate={transformTemplate1}
								variants={{
									vZ5WwwktB: {
										opacity: 1,
									},
								}}
								{...addPropertyOverrides(
									{
										vZ5WwwktB: {
											transformTemplate: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-4w0lur"}
									data-framer-name={"Answer"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"aMHHisiHX"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={DR_6QqGeh}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											vZ5WwwktB: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-cpwznz"}
															data-styles-preset={"ls_KuhAAC"}
														>
															{
																"Framer is a design tool that allows you to design websites on a freeform canvas, and then publish them as websites with a single click."
															}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--framer-letter-spacing": "-0.04em",
												"--framer-line-height": "140%",
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255)))",
											}}
										>
											{
												"Framer is a design tool that allows you to design websites on a freeform canvas, and then publish them as websites with a single click."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
					</Image>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ZlKTN.framer-108siq8, .framer-ZlKTN .framer-108siq8 { display: block; }",
	".framer-ZlKTN.framer-1w45l6n { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 24px; position: relative; width: 391px; will-change: var(--framer-will-change-override, transform); }",
	".framer-ZlKTN .framer-1ya0de7 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-ZlKTN .framer-130q6ld { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-ZlKTN .framer-163bkls { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-ZlKTN .framer-1br8y94, .framer-ZlKTN .framer-4w0lur { -webkit-user-select: none; flex: 1 0 0px; height: auto; position: relative; user-select: none; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-ZlKTN .framer-k17afw { aspect-ratio: 1 / 1; cursor: pointer; flex: none; height: var(--framer-aspect-ratio-supported, 28px); overflow: hidden; position: relative; width: 28px; will-change: var(--framer-will-change-override, transform); }",
	".framer-ZlKTN .framer-s9bebu, .framer-ZlKTN .framer-1fylgxb { flex: none; height: 12px; left: calc(50.00000000000002% - 1px / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 12px / 2); width: 1px; }",
	".framer-ZlKTN .framer-acfnx3 { align-content: center; align-items: center; bottom: -120px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; left: 50%; overflow: hidden; padding: 0px; pointer-events: none; position: absolute; width: 100%; z-index: 1; }",
	".framer-ZlKTN.framer-v-o96l8 .framer-acfnx3 { bottom: unset; left: unset; position: relative; }",
	...css,
	...css2,
	'.framer-ZlKTN[data-border="true"]::after, .framer-ZlKTN [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerEkfhhiLCf = withCSS(Component, css3, "framer-ZlKTN");
var stdin_default = FramerEkfhhiLCf;
FramerEkfhhiLCf.displayName = "Accordion";
FramerEkfhhiLCf.defaultProps = {
	height: 76,
	width: 391,
};
addPropertyControls2(FramerEkfhhiLCf, {
	variant: {
		options: ["KJk8QbTmY", "vZ5WwwktB"],
		optionTitles: ["Closed", "Opened"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	qQefXa5XK: {
		defaultValue: "Lorem Ipsum",
		displayTextArea: false,
		title: "Question",
		type: ControlType2.String,
	},
	DR_6QqGeh: {
		defaultValue:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
		displayTextArea: true,
		title: "Answer",
		type: ControlType2.String,
	},
	Z3jnJDFUJ: {
		title: "Click",
		type: ControlType2.EventHandler,
	},
});
addFonts(
	FramerEkfhhiLCf,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/vikFeKSKDrU6r5u6ANbn/RUiGKwy5iRJlkOkmYvdp/kAuAu8IYD.js
var AccordionFonts = getFonts(stdin_default);
var LayoutJumpPreventerFonts = getFonts(AvoidLayoutJumping);
var cycleOrder2 = [
	"Yi3RUASHS",
	"oPJYsHsBu",
	"m8vEzMbTz",
	"VlENs5cEa",
	"oAc5p5A5g",
	"tf8lL9hsw",
	"hY14th8Nl",
];
var serializationHash2 = "framer-MwyJB";
var variantClassNames2 = {
	hY14th8Nl: "framer-v-vcvu6j",
	m8vEzMbTz: "framer-v-12mpnm5",
	oAc5p5A5g: "framer-v-14lnp4c",
	oPJYsHsBu: "framer-v-5gywmc",
	tf8lL9hsw: "framer-v-8cxj1g",
	VlENs5cEa: "framer-v-w9kjsf",
	Yi3RUASHS: "framer-v-1p7gtwp",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	delay: 0,
	duration: 0.7,
	ease: [0.16, 0.86, 0.56, 1],
	type: "tween",
};
var isSet = (value) => {
	if (Array.isArray(value)) return value.length > 0;
	return value !== void 0 && value !== null && value !== "";
};
var transformTemplate12 = (_, t) => `translateX(-50%) ${t}`;
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	"All closed": "Yi3RUASHS",
	"Question 1 / Opened": "oPJYsHsBu",
	"Question 2 / Opened": "m8vEzMbTz",
	"Question 3 / Opened": "VlENs5cEa",
	"Question 4 / Opened": "oAc5p5A5g",
	"Question 5 / Opened": "tf8lL9hsw",
	"Question 6 / Opened": "hY14th8Nl",
};
var getProps2 = ({
	answer1,
	answer2,
	answer3,
	answer4,
	answer5,
	answer6,
	height,
	id,
	question1,
	question2,
	question3,
	question4,
	question5,
	question6,
	width,
	...props
}) => {
	return {
		...props,
		ApkKi7SYs:
			question4 ??
			props.ApkKi7SYs ??
			"How do I add this FAQ component to my project?",
		IdiX4w72s: question3 ?? props.IdiX4w72s ?? "What is this FAQ component?",
		j_EfdrGoD:
			answer2 ??
			props.j_EfdrGoD ??
			"Framer is fully visual with no code needed, but you can still add custom code and components for more control if you're a designer or developer.",
		rV343XnZp:
			answer4 ??
			props.rV343XnZp ??
			"After duplicating, copy and paste the component into your Framer project. Then edit the questions, answers, styles, and animations as needed.",
		svZsCKZ7a: question1 ?? props.svZsCKZ7a ?? "What is Framer?",
		SZGafHI2T:
			answer5 ??
			props.SZGafHI2T ??
			"Yes, absolutely. The component is built using native Framer tools, so you can tweak fonts, colors, spacing, animations, and layout however you like.",
		UV7N3G2yB:
			question2 ??
			props.UV7N3G2yB ??
			"Do I need to know how to code to use Framer?",
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "Yi3RUASHS",
		Wb41KwT0B:
			answer6 ??
			props.Wb41KwT0B ??
			"Yes, the FAQ component is fully responsive and adapts seamlessly to desktop, tablet, and mobile screen sizes.",
		xHGoJVa3_:
			answer1 ??
			props.xHGoJVa3_ ??
			"Framer is a no-code tool for building and publishing responsive websites\u2014perfect for anyone creating modern, high-performance pages without coding.",
		yIgVEHYaT:
			answer3 ??
			props.yIgVEHYaT ??
			"This is a free, responsive FAQ section for Framer. Drop it into any project, customize styles and text, and use it to save time on support or info pages.",
		yKqHH3CY6: question6 ?? props.yKqHH3CY6 ?? "Is this component responsive?",
		Yp26WXhzg:
			question5 ??
			props.Yp26WXhzg ??
			"Can I customize the design of this component?",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		svZsCKZ7a,
		xHGoJVa3_,
		UV7N3G2yB,
		j_EfdrGoD,
		IdiX4w72s,
		yIgVEHYaT,
		ApkKi7SYs,
		rV343XnZp,
		Yp26WXhzg,
		SZGafHI2T,
		yKqHH3CY6,
		Wb41KwT0B,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "Yi3RUASHS",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback2(baseVariant);
	const Z3jnJDFUJ1t9n3r = activeVariantCallback(async (...args) => {
		setVariant("oPJYsHsBu");
	});
	const Z3jnJDFUJfevnt2 = activeVariantCallback(async (...args) => {
		setVariant("m8vEzMbTz");
	});
	const Z3jnJDFUJ1p9eupe = activeVariantCallback(async (...args) => {
		setVariant("VlENs5cEa");
	});
	const Z3jnJDFUJw19rlf = activeVariantCallback(async (...args) => {
		setVariant("oAc5p5A5g");
	});
	const Z3jnJDFUJxxnbrm = activeVariantCallback(async (...args) => {
		setVariant("tf8lL9hsw");
	});
	const Z3jnJDFUJgatxoc = activeVariantCallback(async (...args) => {
		setVariant("hY14th8Nl");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const visible = isSet(svZsCKZ7a);
	const visible1 = isSet(UV7N3G2yB);
	const visible2 = isSet(IdiX4w72s);
	const visible3 = isSet(ApkKi7SYs);
	const visible4 = isSet(Yp26WXhzg);
	const visible5 = isSet(yKqHH3CY6);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1p7gtwp",
							className3,
							classNames,
						)}
						data-framer-name={"All closed"}
						layoutDependency={layoutDependency}
						layoutId={"Yi3RUASHS"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-66cf77ff-0f3f-4e1d-acc4-caa0067c546a, rgba(255, 255, 255, 0.08))",
							borderBottomLeftRadius: 15,
							borderBottomRightRadius: 15,
							borderTopLeftRadius: 15,
							borderTopRightRadius: 15,
							...style,
						}}
						{...addPropertyOverrides2(
							{
								hY14th8Nl: {
									"data-framer-name": "Question 6 / Opened",
								},
								m8vEzMbTz: {
									"data-framer-name": "Question 2 / Opened",
								},
								oAc5p5A5g: {
									"data-framer-name": "Question 4 / Opened",
								},
								oPJYsHsBu: {
									"data-framer-name": "Question 1 / Opened",
								},
								tf8lL9hsw: {
									"data-framer-name": "Question 5 / Opened",
								},
								VlENs5cEa: {
									"data-framer-name": "Question 3 / Opened",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{visible && (
							<ComponentViewportProvider
								height={76}
								width={`calc(${componentViewport?.width || "100vw"} - 8px)`}
								y={
									(componentViewport?.y || 0) +
									4 +
									(((componentViewport?.height || 474) - 8 - -2) / 2 + 0 + 0)
								}
								{...addPropertyOverrides2(
									{
										hY14th8Nl: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										m8vEzMbTz: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										oAc5p5A5g: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										tf8lL9hsw: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										VlENs5cEa: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-ed0x8u-container"}
									layoutDependency={layoutDependency}
									layoutId={"aiCWVQ1AD-container"}
									nodeId={"aiCWVQ1AD"}
									rendersWithMotion={true}
									scopeId={"kAuAu8IYD"}
								>
									{_jsx3(stdin_default, {
										DR_6QqGeh: xHGoJVa3_,
										height: "100%",
										id: "aiCWVQ1AD",
										layoutId: "aiCWVQ1AD",
										qQefXa5XK: svZsCKZ7a,
										style: {
											width: "100%",
										},
										variant: "KJk8QbTmY",
										width: "100%",
										Z3jnJDFUJ: Z3jnJDFUJ1t9n3r,
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{visible1 && (
							<ComponentViewportProvider
								height={76}
								width={`calc(${componentViewport?.width || "100vw"} - 8px)`}
								y={
									(componentViewport?.y || 0) +
									4 +
									(((componentViewport?.height || 474) - 8 - -2) / 2 + 0 + 0)
								}
								{...addPropertyOverrides2(
									{
										hY14th8Nl: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										m8vEzMbTz: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										oAc5p5A5g: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										tf8lL9hsw: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										VlENs5cEa: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-1idi8gg-container"}
									layoutDependency={layoutDependency}
									layoutId={"hXhAPTYnA-container"}
									nodeId={"hXhAPTYnA"}
									rendersWithMotion={true}
									scopeId={"kAuAu8IYD"}
								>
									{_jsx3(stdin_default, {
										DR_6QqGeh: j_EfdrGoD,
										height: "100%",
										id: "hXhAPTYnA",
										layoutId: "hXhAPTYnA",
										qQefXa5XK: UV7N3G2yB,
										style: {
											width: "100%",
										},
										variant: "KJk8QbTmY",
										width: "100%",
										Z3jnJDFUJ: Z3jnJDFUJfevnt2,
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{visible2 && (
							<ComponentViewportProvider
								height={76}
								width={`calc(${componentViewport?.width || "100vw"} - 8px)`}
								y={
									(componentViewport?.y || 0) +
									4 +
									(((componentViewport?.height || 474) - 8 - -2) / 2 + 0 + 0)
								}
								{...addPropertyOverrides2(
									{
										hY14th8Nl: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										m8vEzMbTz: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										oAc5p5A5g: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										tf8lL9hsw: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										VlENs5cEa: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-907io0-container"}
									layoutDependency={layoutDependency}
									layoutId={"GIma32igA-container"}
									nodeId={"GIma32igA"}
									rendersWithMotion={true}
									scopeId={"kAuAu8IYD"}
								>
									{_jsx3(stdin_default, {
										DR_6QqGeh: yIgVEHYaT,
										height: "100%",
										id: "GIma32igA",
										layoutId: "GIma32igA",
										qQefXa5XK: IdiX4w72s,
										style: {
											width: "100%",
										},
										variant: "KJk8QbTmY",
										width: "100%",
										Z3jnJDFUJ: Z3jnJDFUJ1p9eupe,
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{visible3 && (
							<ComponentViewportProvider
								height={76}
								width={`calc(${componentViewport?.width || "100vw"} - 8px)`}
								y={
									(componentViewport?.y || 0) +
									4 +
									(((componentViewport?.height || 474) - 8 - -2) / 2 + 0 + 0)
								}
								{...addPropertyOverrides2(
									{
										hY14th8Nl: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										m8vEzMbTz: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										oAc5p5A5g: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										tf8lL9hsw: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										VlENs5cEa: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-ooewkz-container"}
									layoutDependency={layoutDependency}
									layoutId={"TE7jPc9Fl-container"}
									nodeId={"TE7jPc9Fl"}
									rendersWithMotion={true}
									scopeId={"kAuAu8IYD"}
								>
									{_jsx3(stdin_default, {
										DR_6QqGeh: rV343XnZp,
										height: "100%",
										id: "TE7jPc9Fl",
										layoutId: "TE7jPc9Fl",
										qQefXa5XK: ApkKi7SYs,
										style: {
											width: "100%",
										},
										variant: "KJk8QbTmY",
										width: "100%",
										Z3jnJDFUJ: Z3jnJDFUJw19rlf,
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{visible4 && (
							<ComponentViewportProvider
								height={76}
								width={`calc(${componentViewport?.width || "100vw"} - 8px)`}
								y={
									(componentViewport?.y || 0) +
									4 +
									(((componentViewport?.height || 474) - 8 - -2) / 2 + 0 + 0)
								}
								{...addPropertyOverrides2(
									{
										hY14th8Nl: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										m8vEzMbTz: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										oAc5p5A5g: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										tf8lL9hsw: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										VlENs5cEa: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-pgjj0k-container"}
									layoutDependency={layoutDependency}
									layoutId={"sUGyBsZ35-container"}
									nodeId={"sUGyBsZ35"}
									rendersWithMotion={true}
									scopeId={"kAuAu8IYD"}
								>
									{_jsx3(stdin_default, {
										DR_6QqGeh: SZGafHI2T,
										height: "100%",
										id: "sUGyBsZ35",
										layoutId: "sUGyBsZ35",
										qQefXa5XK: Yp26WXhzg,
										style: {
											width: "100%",
										},
										variant: "KJk8QbTmY",
										width: "100%",
										Z3jnJDFUJ: Z3jnJDFUJxxnbrm,
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{visible5 && (
							<ComponentViewportProvider
								height={76}
								width={`calc(${componentViewport?.width || "100vw"} - 8px)`}
								y={
									(componentViewport?.y || 0) +
									4 +
									(((componentViewport?.height || 474) - 8 - -2) / 2 + 0 + 0)
								}
								{...addPropertyOverrides2(
									{
										hY14th8Nl: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										m8vEzMbTz: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										oAc5p5A5g: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										tf8lL9hsw: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
										VlENs5cEa: {
											y:
												(componentViewport?.y || 0) +
												4 +
												(((componentViewport?.height || 200) - 8 - -2) / 2 +
													0 +
													0),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-11ni7rn-container"}
									data-framer-name={"Question 6"}
									layoutDependency={layoutDependency}
									layoutId={"HG_gJY_MZ-container"}
									name={"Question 6"}
									nodeId={"HG_gJY_MZ"}
									rendersWithMotion={true}
									scopeId={"kAuAu8IYD"}
								>
									{_jsx3(stdin_default, {
										DR_6QqGeh: Wb41KwT0B,
										height: "100%",
										id: "HG_gJY_MZ",
										layoutId: "HG_gJY_MZ",
										name: "Question 6",
										qQefXa5XK: yKqHH3CY6,
										style: {
											width: "100%",
										},
										variant: "KJk8QbTmY",
										width: "100%",
										Z3jnJDFUJ: Z3jnJDFUJgatxoc,
										...addPropertyOverrides2(
											{
												hY14th8Nl: {
													variant: "vZ5WwwktB",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-51di0r-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"cGkQCaJ98-container"}
								nodeId={"cGkQCaJ98"}
								rendersWithMotion={true}
								scopeId={"kAuAu8IYD"}
								transformTemplate={transformTemplate12}
							>
								<AvoidLayoutJumping
									direction={"vertical"}
									height={"100%"}
									id={"cGkQCaJ98"}
									layoutId={"cGkQCaJ98"}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-MwyJB.framer-1kbh5i8, .framer-MwyJB .framer-1kbh5i8 { display: block; }",
	".framer-MwyJB.framer-1p7gtwp { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 2px; height: min-content; justify-content: center; overflow: hidden; padding: 4px; position: relative; width: 800px; will-change: var(--framer-will-change-override, transform); }",
	".framer-MwyJB .framer-ed0x8u-container, .framer-MwyJB .framer-1idi8gg-container, .framer-MwyJB .framer-907io0-container, .framer-MwyJB .framer-ooewkz-container, .framer-MwyJB .framer-pgjj0k-container, .framer-MwyJB .framer-11ni7rn-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-MwyJB .framer-51di0r-container { flex: none; height: auto; left: 50%; position: absolute; top: 0px; width: auto; z-index: 1; }",
];
var FramerkAuAu8IYD = withCSS2(Component2, css4, "framer-MwyJB");
var stdin_default2 = FramerkAuAu8IYD;
FramerkAuAu8IYD.displayName = "FAQ";
FramerkAuAu8IYD.defaultProps = {
	height: 474,
	width: 800,
};
addPropertyControls3(FramerkAuAu8IYD, {
	variant: {
		options: [
			"Yi3RUASHS",
			"oPJYsHsBu",
			"m8vEzMbTz",
			"VlENs5cEa",
			"oAc5p5A5g",
			"tf8lL9hsw",
			"hY14th8Nl",
		],
		optionTitles: [
			"All closed",
			"Question 1 / Opened",
			"Question 2 / Opened",
			"Question 3 / Opened",
			"Question 4 / Opened",
			"Question 5 / Opened",
			"Question 6 / Opened",
		],
		title: "Variant",
		type: ControlType3.Enum,
	},
	svZsCKZ7a: {
		defaultValue: "What is Framer?",
		displayTextArea: false,
		title: "Question 1",
		type: ControlType3.String,
	},
	xHGoJVa3_: {
		defaultValue:
			"Framer is a no-code tool for building and publishing responsive websites\u2014perfect for anyone creating modern, high-performance pages without coding.",
		displayTextArea: true,
		title: "Answer 1",
		type: ControlType3.String,
	},
	UV7N3G2yB: {
		defaultValue: "Do I need to know how to code to use Framer?",
		displayTextArea: false,
		title: "Question 2",
		type: ControlType3.String,
	},
	j_EfdrGoD: {
		defaultValue:
			"Framer is fully visual with no code needed, but you can still add custom code and components for more control if you're a designer or developer.",
		displayTextArea: true,
		title: "Answer 2",
		type: ControlType3.String,
	},
	IdiX4w72s: {
		defaultValue: "What is this FAQ component?",
		displayTextArea: false,
		title: "Question 3",
		type: ControlType3.String,
	},
	yIgVEHYaT: {
		defaultValue:
			"This is a free, responsive FAQ section for Framer. Drop it into any project, customize styles and text, and use it to save time on support or info pages.",
		displayTextArea: true,
		title: "Answer 3",
		type: ControlType3.String,
	},
	ApkKi7SYs: {
		defaultValue: "How do I add this FAQ component to my project?",
		displayTextArea: false,
		title: "Question 4",
		type: ControlType3.String,
	},
	rV343XnZp: {
		defaultValue:
			"After duplicating, copy and paste the component into your Framer project. Then edit the questions, answers, styles, and animations as needed.",
		displayTextArea: true,
		title: "Answer 4",
		type: ControlType3.String,
	},
	Yp26WXhzg: {
		defaultValue: "Can I customize the design of this component?",
		displayTextArea: false,
		title: "Question 5",
		type: ControlType3.String,
	},
	SZGafHI2T: {
		defaultValue:
			"Yes, absolutely. The component is built using native Framer tools, so you can tweak fonts, colors, spacing, animations, and layout however you like.",
		displayTextArea: true,
		title: "Answer 5",
		type: ControlType3.String,
	},
	yKqHH3CY6: {
		defaultValue: "Is this component responsive?",
		displayTextArea: false,
		title: "Question 6",
		type: ControlType3.String,
	},
	Wb41KwT0B: {
		defaultValue:
			"Yes, the FAQ component is fully responsive and adapts seamlessly to desktop, tablet, and mobile screen sizes.",
		displayTextArea: true,
		title: "Answer 6",
		type: ControlType3.String,
	},
});
addFonts2(
	FramerkAuAu8IYD,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...AccordionFonts,
		...LayoutJumpPreventerFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "Yi3RUASHS",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaqFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var faq_default = ComponentWithRoot;
export { faq_default as default };
