// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0d2be16cf4ecf57c "Anker (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Active' | 'Inactive' | 'Active (Phone)' | 'Inactive (Phone)' // Variant
 * title?: string // Title
 * link?: string // Link
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-BRGTNG7B.js";
import { routes } from "./chunks/chunk-QR7ZKMZ2.js";

// virtual:filter-states
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/w7NFpnoN1TZHeN2rg81t/EkNWZWfjpp2tHr6ahH0y/trHLvt8km.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	nJaNAcrfK: {
		hover: true,
	},
};
var cycleOrder = ["z5wuxA7GC", "nJaNAcrfK", "NxiW6qyCb", "kK7NZp1NO"];
var serializationHash = "framer-bvjj7";
var variantClassNames = {
	kK7NZp1NO: "framer-v-1s8huod",
	nJaNAcrfK: "framer-v-qwmu7c",
	NxiW6qyCb: "framer-v-cm72a8",
	z5wuxA7GC: "framer-v-17xscag",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 24,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var transition2 = {
	delay: 0,
	duration: 0.7,
	ease: [0.08, 0.78, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Active (Phone)": "NxiW6qyCb",
	"Inactive (Phone)": "kK7NZp1NO",
	Active: "z5wuxA7GC",
	Inactive: "nJaNAcrfK",
};
var getProps = ({ height, id, link, title, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "z5wuxA7GC",
		vO9qDenF4: link ?? props.vO9qDenF4,
		YBPeTYkxW: title ?? props.YBPeTYkxW ?? "Title",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		YBPeTYkxW,
		vO9qDenF4,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "z5wuxA7GC",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							nJaNAcrfK: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-17xscag",
							className2,
							classNames,
						)}
						data-framer-name={"Active"}
						layoutDependency={layoutDependency}
						layoutId={"z5wuxA7GC"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								"nJaNAcrfK-hover": {
									"data-framer-name": void 0,
								},
								kK7NZp1NO: {
									"data-framer-name": "Inactive (Phone)",
								},
								nJaNAcrfK: {
									"data-framer-name": "Inactive",
								},
								NxiW6qyCb: {
									"data-framer-name": "Active (Phone)",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Link
							href={vO9qDenF4}
							motionChild={true}
							nodeId={"KFOkeHiWc"}
							scopeId={"trHLvt8km"}
						>
							<motion.a
								className={"framer-4qkhx9 framer-1f4vd0r"}
								data-framer-name={"Wrap"}
								layoutDependency={layoutDependency}
								layoutId={"KFOkeHiWc"}
							>
								<motion.div
									className={"framer-1elwpe2"}
									data-framer-name={"Top"}
									layoutDependency={layoutDependency}
									layoutId={"I1jCjJSyD"}
									{...addPropertyOverrides(
										{
											"nJaNAcrfK-hover": {
												tabIndex: -1,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1lj51fh"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"SUShtH3cU"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255))",
										}}
										text={YBPeTYkxW}
										variants={{
											kK7NZp1NO: {
												"--extracted-r6o4lv":
													"var(--token-aa4b05ac-cb0a-4952-a6ee-9d49e45f217d, rgb(122, 122, 122))",
											},
											nJaNAcrfK: {
												"--extracted-r6o4lv":
													"var(--token-aa4b05ac-cb0a-4952-a6ee-9d49e45f217d, rgb(122, 122, 122))",
											},
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												kK7NZp1NO: {
													children: (
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-cpwznz"}
																data-styles-preset={"ls_KuhAAC"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-aa4b05ac-cb0a-4952-a6ee-9d49e45f217d, rgb(122, 122, 122)))",
																}}
															>
																{"Title"}
															</motion.p>
														</React.Fragment>
													),
												},
												nJaNAcrfK: {
													children: (
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-cpwznz"}
																data-styles-preset={"ls_KuhAAC"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-aa4b05ac-cb0a-4952-a6ee-9d49e45f217d, rgb(122, 122, 122)))",
																}}
															>
																{"Title"}
															</motion.p>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-cpwznz"}
												data-styles-preset={"ls_KuhAAC"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255)))",
												}}
											>
												{"Title"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-i3diy1"}
									data-framer-name={"Bottom"}
									layoutDependency={layoutDependency}
									layoutId={"p2ax0ncpc"}
									tabIndex={-1}
									{...addPropertyOverrides(
										{
											"nJaNAcrfK-hover": {
												tabIndex: void 0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1soj3o"}
										fonts={["GF;Geist-500"]}
										layoutDependency={layoutDependency}
										layoutId={"D9iy0dKDK"}
										style={{
											"--extracted-a0htzi":
												"var(--token-252599bf-f36c-47e5-a651-baf5c3684530, rgb(30, 30, 31))",
										}}
										text={YBPeTYkxW}
										variants={{
											"nJaNAcrfK-hover": {
												"--extracted-a0htzi":
													"var(--token-aa4b05ac-cb0a-4952-a6ee-9d49e45f217d, rgb(122, 122, 122))",
											},
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												"nJaNAcrfK-hover": {
													children: (
														<React.Fragment>
															<motion.h3
																style={{
																	"--font-selector": "R0Y7R2Vpc3QtNTAw",
																	"--framer-font-family":
																		'"Geist", "Geist Placeholder", sans-serif',
																	"--framer-font-weight": "500",
																	"--framer-letter-spacing": "-0.04em",
																	"--framer-text-color":
																		"var(--extracted-a0htzi, var(--token-aa4b05ac-cb0a-4952-a6ee-9d49e45f217d, rgb(122, 122, 122)))",
																}}
															>
																{"Title"}
															</motion.h3>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.h3
												style={{
													"--font-selector": "R0Y7R2Vpc3QtNTAw",
													"--framer-font-family":
														'"Geist", "Geist Placeholder", sans-serif',
													"--framer-font-weight": "500",
													"--framer-letter-spacing": "-0.04em",
													"--framer-text-color":
														"var(--extracted-a0htzi, var(--token-252599bf-f36c-47e5-a651-baf5c3684530, rgb(30, 30, 31)))",
												}}
											>
												{"Title"}
											</motion.h3>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.a>
						</Link>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-bvjj7.framer-1f4vd0r, .framer-bvjj7 .framer-1f4vd0r { display: block; }",
	".framer-bvjj7.framer-17xscag { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 20px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-bvjj7 .framer-4qkhx9 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 100%; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-bvjj7 .framer-1elwpe2, .framer-bvjj7 .framer-i3diy1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 100%; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-bvjj7 .framer-1lj51fh, .framer-bvjj7 .framer-1soj3o { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-bvjj7.framer-v-qwmu7c.framer-17xscag { cursor: pointer; }",
	".framer-bvjj7.framer-v-qwmu7c.hover .framer-4qkhx9 { justify-content: flex-end; }",
	...css,
];
var FramertrHLvt8km = withCSS(Component, css2, "framer-bvjj7");
var stdin_default = FramertrHLvt8km;
FramertrHLvt8km.displayName = "Filter States";
FramertrHLvt8km.defaultProps = {
	height: 20,
	width: 29,
};
addPropertyControls(FramertrHLvt8km, {
	variant: {
		options: ["z5wuxA7GC", "nJaNAcrfK", "NxiW6qyCb", "kK7NZp1NO"],
		optionTitles: ["Active", "Inactive", "Active (Phone)", "Inactive (Phone)"],
		title: "Variant",
		type: ControlType.Enum,
	},
	YBPeTYkxW: {
		defaultValue: "Title",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	vO9qDenF4: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramertrHLvt8km,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Geist",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/geist/v4/gyBhhwUxId8gMGYQMKR3pzfaWI_RruM4mJPby1QNtA.woff2",
					weight: "500",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:filter-states
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "z5wuxA7GC",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FilterStatesFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var filter_states_default = ComponentWithRoot;
export { filter_states_default as default };
