// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0d2be16cf4ecf57c "Anker (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Hover In' | 'Mobile' // Variant
 * text?: string // Text
 * link?: string // Link
 * newTab?: boolean // New Tab
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-WJBYBRXL.js";
import { routes } from "./chunks/chunk-QR7ZKMZ2.js";

// virtual:footer-underline-link
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/4y3zoNLV5DF6zkutHG4b/s8JX9wdQz57J4B8HrcxP/fmsxoDX9g.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["VnuPRUN1L", "u8YXDWX5b", "PFuYwgIve"];
var serializationHash = "framer-USV5l";
var variantClassNames = {
	PFuYwgIve: "framer-v-29qnnc",
	u8YXDWX5b: "framer-v-162a87s",
	VnuPRUN1L: "framer-v-158xrt2",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.4,
	ease: [0.08, 0.78, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Hover In": "u8YXDWX5b",
	Default: "VnuPRUN1L",
	Mobile: "PFuYwgIve",
};
var getProps = ({ height, id, link, newTab, text, width, ...props }) => {
	return {
		...props,
		BYNIrUSxY: text ?? props.BYNIrUSxY ?? "Button Text",
		sfse768LG: link ?? props.sfse768LG,
		UXzOZZMPJ: newTab ?? props.UXzOZZMPJ,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "VnuPRUN1L",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		BYNIrUSxY,
		sfse768LG,
		UXzOZZMPJ,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "VnuPRUN1L",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnter16if02t = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		setVariant("u8YXDWX5b");
	});
	const onMouseLeavevk8s93 = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("VnuPRUN1L");
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						motionChild={true}
						nodeId={"VnuPRUN1L"}
						scopeId={"fmsxoDX9g"}
						{...addPropertyOverrides(
							{
								PFuYwgIve: {
									href: sfse768LG,
								},
								u8YXDWX5b: {
									href: sfse768LG,
									openInNewTab: UXzOZZMPJ,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-158xrt2", className2, classNames)} framer-1pjqrt7`}
							data-framer-name={"Default"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"VnuPRUN1L"}
							onMouseEnter={onMouseEnter16if02t}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									PFuYwgIve: {
										"data-framer-name": "Mobile",
										"data-highlight": void 0,
										onMouseEnter: void 0,
									},
									u8YXDWX5b: {
										"data-framer-name": "Hover In",
										onMouseLeave: onMouseLeavevk8s93,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-1d5p4fw"}
								data-framer-name={"Button Wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"RMPB6N7yF"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-ysgkri"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"d9pfSrufe"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={BYNIrUSxY}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-g8iro9"}
											data-styles-preset={"Ck1ubvtuS"}
										>
											{"Button Text"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<motion.div
									className={"framer-vhqrte"}
									data-framer-name={"Line"}
									layoutDependency={layoutDependency}
									layoutId={"pJ5qqayEn"}
									style={{
										backgroundColor:
											"var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255))",
									}}
								/>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-USV5l.framer-1pjqrt7, .framer-USV5l .framer-1pjqrt7 { display: block; }",
	".framer-USV5l.framer-158xrt2 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-USV5l .framer-1d5p4fw { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-USV5l .framer-ysgkri { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 2; }",
	".framer-USV5l .framer-vhqrte { bottom: 0px; flex: none; height: 1px; left: -60px; overflow: hidden; position: absolute; width: 53px; z-index: 2; }",
	".framer-USV5l.framer-v-162a87s.framer-158xrt2, .framer-USV5l.framer-v-29qnnc.framer-158xrt2 { text-decoration: none; }",
	".framer-USV5l.framer-v-162a87s .framer-vhqrte { left: 1px; right: 0px; width: unset; }",
	...css,
];
var FramerfmsxoDX9g = withCSS(Component, css2, "framer-USV5l");
var stdin_default = FramerfmsxoDX9g;
FramerfmsxoDX9g.displayName = "Footer Underline Link";
FramerfmsxoDX9g.defaultProps = {
	height: 20,
	width: 75,
};
addPropertyControls(FramerfmsxoDX9g, {
	variant: {
		options: ["VnuPRUN1L", "u8YXDWX5b", "PFuYwgIve"],
		optionTitles: ["Default", "Hover In", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	BYNIrUSxY: {
		defaultValue: "Button Text",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	sfse768LG: {
		title: "Link",
		type: ControlType.Link,
	},
	UXzOZZMPJ: {
		defaultValue: false,
		title: "New Tab",
		type: ControlType.Boolean,
	},
});
addFonts(
	FramerfmsxoDX9g,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:footer-underline-link
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "VnuPRUN1L",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterUnderlineLinkFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var footer_underline_link_default = ComponentWithRoot;
export { footer_underline_link_default as default };
