// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0d2be16cf4ecf57c "Anker (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone' | 'Phone Open' // Variant
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
	stdin_default,
	stdin_default2,
	stdin_default3,
} from "./chunks/chunk-YT5K5GDM.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-55EBAKF4.js";
import { className, css, fonts } from "./chunks/chunk-WJBYBRXL.js";
import { routes } from "./chunks/chunk-QR7ZKMZ2.js";

// virtual:nav-content
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/jFR49I8Lh7PClBt6tDMH/i0uNiRUQHwlcgD7fFYaj/PlccV7KaQ.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MinimalLinkFonts = getFonts(stdin_default);
var PrimaryFonts = getFonts(stdin_default2);
var HamburgerFonts = getFonts(stdin_default3);
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion.div),
);
var cycleOrder = ["yQcF0UXXQ", "KKdEHoWpz", "U0Jm9JqP3"];
var serializationHash = "framer-NGAAt";
var variantClassNames = {
	KKdEHoWpz: "framer-v-1mn2n7f",
	U0Jm9JqP3: "framer-v-1scwshe",
	yQcF0UXXQ: "framer-v-luk7l9",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.6,
	ease: [0.08, 0.78, 0.56, 1],
	type: "tween",
};
var transition2 = {
	delay: 0,
	duration: 0.7,
	ease: [0.08, 0.78, 0.56, 1],
	type: "tween",
};
var transition3 = {
	delay: 0.3,
	duration: 0.7,
	ease: [0.08, 0.78, 0.56, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 42,
};
var transition4 = {
	delay: 0.1,
	duration: 1.5,
	ease: [0.16, 1, 0.3, 1],
	type: "tween",
};
var animation2 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transformPerspective: 1200,
	transition: transition4,
	x: 0,
	y: 0,
};
var animation3 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transformPerspective: 1200,
	x: 0,
	y: 100,
};
var transition5 = {
	delay: 0.2,
	duration: 1.5,
	ease: [0.16, 1, 0.3, 1],
	type: "tween",
};
var animation4 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transformPerspective: 1200,
	transition: transition5,
	x: 0,
	y: 0,
};
var transition6 = {
	delay: 0.3,
	duration: 1.5,
	ease: [0.16, 1, 0.3, 1],
	type: "tween",
};
var animation5 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transformPerspective: 1200,
	transition: transition6,
	x: 0,
	y: 0,
};
var transition7 = {
	delay: 0.4,
	duration: 1.5,
	ease: [0.16, 1, 0.3, 1],
	type: "tween",
};
var animation6 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transformPerspective: 1200,
	transition: transition7,
	x: 0,
	y: 0,
};
var transition8 = {
	delay: 0.6,
	duration: 1.5,
	ease: [0.16, 1, 0.3, 1],
	type: "tween",
};
var animation7 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transformPerspective: 1200,
	transition: transition8,
	x: 0,
	y: 0,
};
var transition9 = {
	delay: 0.7,
	duration: 1.5,
	ease: [0.16, 1, 0.3, 1],
	type: "tween",
};
var animation8 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transformPerspective: 1200,
	transition: transition9,
	x: 0,
	y: 0,
};
var transition10 = {
	delay: 0.5,
	duration: 1.5,
	ease: [0.16, 1, 0.3, 1],
	type: "tween",
};
var animation9 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transformPerspective: 1200,
	transition: transition10,
	x: 0,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Phone Open": "U0Jm9JqP3",
	Desktop: "yQcF0UXXQ",
	Phone: "KKdEHoWpz",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "yQcF0UXXQ",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "yQcF0UXXQ",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTaphrczkb = activeVariantCallback(async (...args) => {
		setVariant("KKdEHoWpz");
	});
	const onTap1ehdcsd = activeVariantCallback(async (...args) => {
		setVariant("U0Jm9JqP3");
	});
	const onTap17yybqx = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("KKdEHoWpz"), 100);
	});
	const sharedStyleClassNames = [className3, className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["KKdEHoWpz", "U0Jm9JqP3"].includes(baseVariant)) return false;
		return true;
	};
	const router = useRouter();
	const isDisplayed1 = () => {
		if (["KKdEHoWpz", "U0Jm9JqP3"].includes(baseVariant)) return true;
		return false;
	};
	const isDisplayed2 = () => {
		if (baseVariant === "U0Jm9JqP3") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							KKdEHoWpz: {
								value: transition2,
							},
							U0Jm9JqP3: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.nav
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-luk7l9",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"yQcF0UXXQ"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								KKdEHoWpz: {
									"data-framer-name": "Phone",
								},
								U0Jm9JqP3: {
									"data-framer-name": "Phone Open",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1eq68fo"}
							data-framer-name={"Padding"}
							layoutDependency={layoutDependency}
							layoutId={"kQrSnQkaF"}
						>
							<motion.div
								className={"framer-t0jxjr"}
								data-framer-name={"Main Nav"}
								layoutDependency={layoutDependency}
								layoutId={"rZ5Jn6FkM"}
								style={{
									backgroundColor: "rgba(0, 0, 0, 0)",
								}}
								variants={{
									KKdEHoWpz: {
										backgroundColor: "rgba(255, 255, 255, 0)",
									},
									U0Jm9JqP3: {
										backgroundColor: "rgba(0, 0, 0, 0)",
									},
								}}
							>
								<Link
									href={{
										webPageId: "OqluLbhL2",
									}}
									motionChild={true}
									nodeId={"NcQSjBVUU"}
									openInNewTab={false}
									scopeId={"PlccV7KaQ"}
								>
									<motion.a
										className={"framer-12t9255 framer-144yhwp"}
										data-framer-name={"Logo"}
										layoutDependency={layoutDependency}
										layoutId={"NcQSjBVUU"}
									>
										<motion.div
											className={"framer-49xcz0"}
											data-framer-name={"Logo Wrap"}
											layoutDependency={layoutDependency}
											layoutId={"lGLIiKHAh"}
										>
											<Image
												background={{
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															0 +
															0 +
															16 +
															0 +
															11 +
															0 +
															0,
													),
													pixelHeight: 92,
													pixelWidth: 356,
													src: "https://framerusercontent.com/images/vzVeAmPSzV6Y3N9YYRtOgDxYw.svg?width=356&height=92",
												}}
												className={"framer-1jzozk3"}
												data-framer-name={"Logo SvG"}
												layoutDependency={layoutDependency}
												layoutId={"HWzt2jI5Q"}
												{...addPropertyOverrides(
													{
														KKdEHoWpz: {
															background: {
																alt: "",
																fit: "fill",
																loading: getLoadingLazyAtYPosition(
																	(componentViewport?.y || 0) +
																		16 +
																		0 +
																		0 +
																		0 +
																		5.5 +
																		0 +
																		0,
																),
																pixelHeight: 92,
																pixelWidth: 356,
																src: "https://framerusercontent.com/images/vzVeAmPSzV6Y3N9YYRtOgDxYw.svg?width=356&height=92",
															},
														},
														U0Jm9JqP3: {
															background: {
																alt: "",
																fit: "fill",
																loading: getLoadingLazyAtYPosition(
																	(componentViewport?.y || 0) +
																		0 +
																		0 +
																		16 +
																		0 +
																		5.5 +
																		0 +
																		0,
																),
																pixelHeight: 92,
																pixelWidth: 356,
																src: "https://framerusercontent.com/images/vzVeAmPSzV6Y3N9YYRtOgDxYw.svg?width=356&height=92",
															},
														},
													},
													baseVariant,
													gestureVariant,
												)}
											/>
										</motion.div>
									</motion.a>
								</Link>
								<motion.div
									className={"framer-1bzjg17"}
									data-framer-name={"Nav Items"}
									layoutDependency={layoutDependency}
									layoutId={"B44LYjl5v"}
								>
									{isDisplayed() && (
										<motion.div
											className={"framer-1hd35vz"}
											data-framer-name={"Nav Items Wrap"}
											layoutDependency={layoutDependency}
											layoutId={"kQfGWh1CM"}
										>
											<ResolveLinks
												links={[
													{
														href: {
															webPageId: "G4RcsBSLk",
														},
														implicitPathVariables: void 0,
													},
												]}
											>
												{(resolvedLinks) => (
													<ComponentViewportProvider
														height={22}
														y={
															(componentViewport?.y || 0) +
															0 +
															0 +
															16 +
															0 +
															0 +
															0 +
															10.5
														}
													>
														<SmartComponentScopedContainer
															className={"framer-bcze4r-container"}
															layoutDependency={layoutDependency}
															layoutId={"qcZqmVY3D-container"}
															nodeId={"qcZqmVY3D"}
															rendersWithMotion={true}
															scopeId={"PlccV7KaQ"}
														>
															{_jsx(stdin_default, {
																height: "100%",
																hSkZEIcAU: resolvedLinks[0],
																id: "qcZqmVY3D",
																layoutId: "qcZqmVY3D",
																width: "100%",
																zdrHC6AsK: "Portfolio",
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												)}
											</ResolveLinks>
											<ResolveLinks
												links={[
													{
														href: {
															webPageId: "K5gBqNy8l",
														},
														implicitPathVariables: void 0,
													},
												]}
											>
												{(resolvedLinks1) => (
													<ComponentViewportProvider
														height={22}
														y={
															(componentViewport?.y || 0) +
															0 +
															0 +
															16 +
															0 +
															0 +
															0 +
															10.5
														}
													>
														<SmartComponentScopedContainer
															className={"framer-1atvq5v-container"}
															layoutDependency={layoutDependency}
															layoutId={"jLNHqbDf5-container"}
															nodeId={"jLNHqbDf5"}
															rendersWithMotion={true}
															scopeId={"PlccV7KaQ"}
														>
															{_jsx(stdin_default, {
																height: "100%",
																hSkZEIcAU: resolvedLinks1[0],
																id: "jLNHqbDf5",
																layoutId: "jLNHqbDf5",
																width: "100%",
																zdrHC6AsK: "Vision",
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												)}
											</ResolveLinks>
											<ResolveLinks
												links={[
													{
														href: {
															webPageId: "jwo65cm92",
														},
														implicitPathVariables: void 0,
													},
												]}
											>
												{(resolvedLinks2) => (
													<ComponentViewportProvider
														height={22}
														y={
															(componentViewport?.y || 0) +
															0 +
															0 +
															16 +
															0 +
															0 +
															0 +
															10.5
														}
													>
														<SmartComponentScopedContainer
															className={"framer-1n3167m-container"}
															layoutDependency={layoutDependency}
															layoutId={"BjqK5aTxc-container"}
															nodeId={"BjqK5aTxc"}
															rendersWithMotion={true}
															scopeId={"PlccV7KaQ"}
														>
															{_jsx(stdin_default, {
																height: "100%",
																hSkZEIcAU: resolvedLinks2[0],
																id: "BjqK5aTxc",
																layoutId: "BjqK5aTxc",
																width: "100%",
																zdrHC6AsK: "Team",
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												)}
											</ResolveLinks>
											<ResolveLinks
												links={[
													{
														href: {
															pathVariables: {
																jg_uNk_rb: "all",
															},
															unresolvedPathSlugs: {
																jg_uNk_rb: {
																	collectionId: "pjV7ppLnx",
																	collectionItemId: "bIsWb0oys",
																},
															},
															webPageId: "BOK_Vkv81",
														},
														implicitPathVariables: void 0,
													},
												]}
											>
												{(resolvedLinks3) => (
													<ComponentViewportProvider
														height={22}
														y={
															(componentViewport?.y || 0) +
															0 +
															0 +
															16 +
															0 +
															0 +
															0 +
															10.5
														}
													>
														<SmartComponentScopedContainer
															className={"framer-1cl2you-container"}
															layoutDependency={layoutDependency}
															layoutId={"oILr14ugU-container"}
															nodeId={"oILr14ugU"}
															rendersWithMotion={true}
															scopeId={"PlccV7KaQ"}
														>
															{_jsx(stdin_default, {
																height: "100%",
																hSkZEIcAU: resolvedLinks3[0],
																id: "oILr14ugU",
																layoutId: "oILr14ugU",
																width: "100%",
																zdrHC6AsK: "Newsroom",
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												)}
											</ResolveLinks>
											<ResolveLinks
												links={[
													{
														href: {
															webPageId: "rE38NyvOx",
														},
														implicitPathVariables: void 0,
													},
												]}
											>
												{(resolvedLinks4) => (
													<ComponentViewportProvider
														height={22}
														y={
															(componentViewport?.y || 0) +
															0 +
															0 +
															16 +
															0 +
															0 +
															0 +
															10.5
														}
													>
														<SmartComponentScopedContainer
															className={"framer-rzejpt-container"}
															layoutDependency={layoutDependency}
															layoutId={"OVyjKpHZU-container"}
															nodeId={"OVyjKpHZU"}
															rendersWithMotion={true}
															scopeId={"PlccV7KaQ"}
														>
															{_jsx(stdin_default, {
																height: "100%",
																hSkZEIcAU: resolvedLinks4[0],
																id: "OVyjKpHZU",
																layoutId: "OVyjKpHZU",
																width: "100%",
																zdrHC6AsK: "FAQ",
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												)}
											</ResolveLinks>
											<ResolveLinks
												links={[
													{
														href: {
															webPageId: "zyOtqQTNK",
														},
														implicitPathVariables: void 0,
													},
												]}
											>
												{(resolvedLinks5) => (
													<ComponentViewportProvider
														height={43}
														y={
															(componentViewport?.y || 0) +
															0 +
															0 +
															16 +
															0 +
															0 +
															0 +
															0
														}
													>
														<SmartComponentScopedContainer
															className={"framer-10t98hw-container"}
															layoutDependency={layoutDependency}
															layoutId={"nzme6TJvY-container"}
															nodeId={"nzme6TJvY"}
															rendersWithMotion={true}
															scopeId={"PlccV7KaQ"}
														>
															{_jsx(stdin_default2, {
																height: "100%",
																id: "nzme6TJvY",
																jJSiQvJyC: "Contact",
																layoutId: "nzme6TJvY",
																variant: "WxMcWJOlZ",
																width: "100%",
																xKlNh7HCe: resolvedLinks5[0],
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												)}
											</ResolveLinks>
										</motion.div>
									)}
									{isDisplayed1() && (
										<motion.div
											className={"framer-16lx6jx"}
											data-framer-name={"Menu Wrap"}
											data-highlight={true}
											layoutDependency={layoutDependency}
											layoutId={"aeRLSWWGf"}
											onTap={onTaphrczkb}
											{...addPropertyOverrides(
												{
													KKdEHoWpz: {
														onTap: onTap1ehdcsd,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<ComponentViewportProvider
												height={32}
												width={"32px"}
												{...addPropertyOverrides(
													{
														KKdEHoWpz: {
															y:
																(componentViewport?.y || 0) +
																16 +
																0 +
																0 +
																0 +
																0 +
																0 +
																0,
														},
														U0Jm9JqP3: {
															y:
																(componentViewport?.y || 0) +
																0 +
																0 +
																16 +
																0 +
																0 +
																0 +
																0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-1nane18-container"}
													layoutDependency={layoutDependency}
													layoutId={"MCtGLp6hV-container"}
													nodeId={"MCtGLp6hV"}
													rendersWithMotion={true}
													scopeId={"PlccV7KaQ"}
												>
													{_jsx(stdin_default3, {
														height: "100%",
														id: "MCtGLp6hV",
														layoutId: "MCtGLp6hV",
														style: {
															height: "100%",
															width: "100%",
														},
														variant: "W1fnze36p",
														width: "100%",
														wYCFdsUbu: "MzBj6rqrX",
														...addPropertyOverrides(
															{
																U0Jm9JqP3: {
																	variant: "kQ4Aa81OK",
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										</motion.div>
									)}
								</motion.div>
							</motion.div>
							{isDisplayed2() && (
								<MotionDivWithFXWithOptimizedAppearEffect
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									animate={animation}
									className={"framer-13lhw0b"}
									data-framer-appear-id={"13lhw0b"}
									data-framer-name={"Phone Nav"}
									initial={animation1}
									layoutDependency={layoutDependency}
									layoutId={"jcpG2A3TJ"}
									optimized={true}
								>
									<motion.div
										className={"framer-j0t94i"}
										data-framer-name={"Menu"}
										layoutDependency={layoutDependency}
										layoutId={"yZcDvCfes"}
									>
										<Link
											href={{
												webPageId: "OqluLbhL2",
											}}
											motionChild={true}
											nodeId={"rYKfwgsW8"}
											openInNewTab={false}
											scopeId={"PlccV7KaQ"}
										>
											<motion.a
												className={"framer-1a1iit0 framer-144yhwp"}
												data-framer-name={"Link"}
												data-highlight={true}
												layoutDependency={layoutDependency}
												layoutId={"rYKfwgsW8"}
												onTap={onTaphrczkb}
											>
												<MotionDivWithFXWithOptimizedAppearEffect
													__perspectiveFX={false}
													__smartComponentFX={true}
													__targetOpacity={1}
													animate={animation2}
													className={"framer-mixzlz"}
													data-framer-appear-id={"mixzlz"}
													data-framer-name={"Wrap"}
													initial={animation3}
													layoutDependency={layoutDependency}
													layoutId={"DwWr1gpLR"}
													optimized={true}
													style={{
														transformPerspective: 1200,
													}}
												>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-x2f2r0"}
														data-framer-name={"Text"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"NNVyw8Ssp"}
														style={{
															"--framer-paragraph-spacing": "0px",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.h3
																className={"framer-styles-preset-pc4qxs"}
																data-styles-preset={"TwcPoWkXd"}
															>
																{"Home"}
															</motion.h3>
														</React.Fragment>
													</RichText>
												</MotionDivWithFXWithOptimizedAppearEffect>
											</motion.a>
										</Link>
										<Link
											href={{
												webPageId: "G4RcsBSLk",
											}}
											motionChild={true}
											nodeId={"QrqpcTlCm"}
											openInNewTab={false}
											scopeId={"PlccV7KaQ"}
										>
											<motion.a
												className={"framer-ayjy3x framer-144yhwp"}
												data-framer-name={"Link"}
												data-highlight={true}
												layoutDependency={layoutDependency}
												layoutId={"QrqpcTlCm"}
												onTap={onTap17yybqx}
											>
												<MotionDivWithFXWithOptimizedAppearEffect
													__perspectiveFX={false}
													__smartComponentFX={true}
													__targetOpacity={1}
													animate={animation4}
													className={"framer-i83ztx"}
													data-framer-appear-id={"i83ztx"}
													data-framer-name={"Wrap"}
													initial={animation3}
													layoutDependency={layoutDependency}
													layoutId={"Ue5ZMhtn9"}
													optimized={true}
													style={{
														transformPerspective: 1200,
													}}
												>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-4rlaci"}
														data-framer-name={"Text"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"llxKBy2TI"}
														style={{
															"--framer-paragraph-spacing": "0px",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.h3
																className={"framer-styles-preset-pc4qxs"}
																data-styles-preset={"TwcPoWkXd"}
															>
																{"Portfolio"}
															</motion.h3>
														</React.Fragment>
													</RichText>
												</MotionDivWithFXWithOptimizedAppearEffect>
											</motion.a>
										</Link>
										<Link
											href={{
												webPageId: "K5gBqNy8l",
											}}
											motionChild={true}
											nodeId={"RQWUZGYf1"}
											openInNewTab={false}
											scopeId={"PlccV7KaQ"}
										>
											<motion.a
												className={"framer-c8l9jk framer-144yhwp"}
												data-framer-name={"Link"}
												data-highlight={true}
												layoutDependency={layoutDependency}
												layoutId={"RQWUZGYf1"}
												onTap={onTaphrczkb}
											>
												<MotionDivWithFXWithOptimizedAppearEffect
													__perspectiveFX={false}
													__smartComponentFX={true}
													__targetOpacity={1}
													animate={animation5}
													className={"framer-19kcz6v"}
													data-framer-appear-id={"19kcz6v"}
													data-framer-name={"Wrap"}
													initial={animation3}
													layoutDependency={layoutDependency}
													layoutId={"fD83ic80S"}
													optimized={true}
													style={{
														transformPerspective: 1200,
													}}
												>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-1wb328p"}
														data-framer-name={"Text"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"ncl6VodNF"}
														style={{
															"--framer-paragraph-spacing": "0px",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.h3
																className={"framer-styles-preset-pc4qxs"}
																data-styles-preset={"TwcPoWkXd"}
															>
																{"Vision"}
															</motion.h3>
														</React.Fragment>
													</RichText>
												</MotionDivWithFXWithOptimizedAppearEffect>
											</motion.a>
										</Link>
										<Link
											href={{
												webPageId: "jwo65cm92",
											}}
											motionChild={true}
											nodeId={"FK0S9DNsT"}
											openInNewTab={false}
											scopeId={"PlccV7KaQ"}
										>
											<motion.a
												className={"framer-gfxtd3 framer-144yhwp"}
												data-framer-name={"Link"}
												data-highlight={true}
												layoutDependency={layoutDependency}
												layoutId={"FK0S9DNsT"}
												onTap={onTaphrczkb}
											>
												<MotionDivWithFXWithOptimizedAppearEffect
													__perspectiveFX={false}
													__smartComponentFX={true}
													__targetOpacity={1}
													animate={animation6}
													className={"framer-1himkcf"}
													data-framer-appear-id={"1himkcf"}
													data-framer-name={"Wrap"}
													initial={animation3}
													layoutDependency={layoutDependency}
													layoutId={"Ag2DUPkSU"}
													optimized={true}
													style={{
														transformPerspective: 1200,
													}}
												>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-1swrqrn"}
														data-framer-name={"Text"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"wG4wLwkaP"}
														style={{
															"--framer-paragraph-spacing": "0px",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.h3
																className={"framer-styles-preset-pc4qxs"}
																data-styles-preset={"TwcPoWkXd"}
															>
																{"Team"}
															</motion.h3>
														</React.Fragment>
													</RichText>
												</MotionDivWithFXWithOptimizedAppearEffect>
											</motion.a>
										</Link>
										<Link
											href={{
												webPageId: "rE38NyvOx",
											}}
											motionChild={true}
											nodeId={"NdVee5tmc"}
											openInNewTab={false}
											scopeId={"PlccV7KaQ"}
										>
											<motion.a
												className={"framer-139xtf8 framer-144yhwp"}
												data-framer-name={"Link"}
												data-highlight={true}
												layoutDependency={layoutDependency}
												layoutId={"NdVee5tmc"}
												onTap={onTaphrczkb}
											>
												<MotionDivWithFXWithOptimizedAppearEffect
													__perspectiveFX={false}
													__smartComponentFX={true}
													__targetOpacity={1}
													animate={animation7}
													className={"framer-3pzsx0"}
													data-framer-appear-id={"3pzsx0"}
													data-framer-name={"Wrap"}
													initial={animation3}
													layoutDependency={layoutDependency}
													layoutId={"nSninoqP1"}
													optimized={true}
													style={{
														transformPerspective: 1200,
													}}
												>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-1257ujl"}
														data-framer-name={"Text"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"yYWXrnPbH"}
														style={{
															"--framer-paragraph-spacing": "0px",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.h3
																className={"framer-styles-preset-pc4qxs"}
																data-styles-preset={"TwcPoWkXd"}
															>
																{"FAQ"}
															</motion.h3>
														</React.Fragment>
													</RichText>
												</MotionDivWithFXWithOptimizedAppearEffect>
											</motion.a>
										</Link>
										<Link
											href={{
												webPageId: "zyOtqQTNK",
											}}
											motionChild={true}
											nodeId={"RD773JoO7"}
											openInNewTab={false}
											scopeId={"PlccV7KaQ"}
										>
											<motion.a
												className={"framer-meym80 framer-144yhwp"}
												data-framer-name={"Link"}
												data-highlight={true}
												layoutDependency={layoutDependency}
												layoutId={"RD773JoO7"}
												onTap={onTaphrczkb}
											>
												<MotionDivWithFXWithOptimizedAppearEffect
													__perspectiveFX={false}
													__smartComponentFX={true}
													__targetOpacity={1}
													animate={animation8}
													className={"framer-1inoz4k"}
													data-framer-appear-id={"1inoz4k"}
													data-framer-name={"Wrap"}
													initial={animation3}
													layoutDependency={layoutDependency}
													layoutId={"wYdOjeN46"}
													optimized={true}
													style={{
														transformPerspective: 1200,
													}}
												>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-1elu7k4"}
														data-framer-name={"Text"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"E_815ehnr"}
														style={{
															"--extracted-a0htzi":
																"var(--token-fc7799b1-5dfe-4fa1-a9e8-833f81a6959a, rgb(142, 132, 247))",
															"--framer-paragraph-spacing": "0px",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.h3
																className={"framer-styles-preset-pc4qxs"}
																data-styles-preset={"TwcPoWkXd"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-a0htzi, var(--token-fc7799b1-5dfe-4fa1-a9e8-833f81a6959a, rgb(142, 132, 247)))",
																}}
															>
																{"Contact"}
															</motion.h3>
														</React.Fragment>
													</RichText>
												</MotionDivWithFXWithOptimizedAppearEffect>
											</motion.a>
										</Link>
										<Link
											href={{
												pathVariables: {
													jg_uNk_rb: "all",
												},
												unresolvedPathSlugs: {
													jg_uNk_rb: {
														collectionId: "pjV7ppLnx",
														collectionItemId: "bIsWb0oys",
													},
												},
												webPageId: "BOK_Vkv81",
											}}
											motionChild={true}
											nodeId={"z60w7LXcd"}
											openInNewTab={false}
											scopeId={"PlccV7KaQ"}
										>
											<motion.a
												className={"framer-1msws2u framer-144yhwp"}
												data-framer-name={"Link"}
												data-highlight={true}
												layoutDependency={layoutDependency}
												layoutId={"z60w7LXcd"}
												onTap={onTaphrczkb}
											>
												<MotionDivWithFXWithOptimizedAppearEffect
													__perspectiveFX={false}
													__smartComponentFX={true}
													__targetOpacity={1}
													animate={animation9}
													className={"framer-8n8815"}
													data-framer-appear-id={"8n8815"}
													data-framer-name={"Wrap"}
													initial={animation3}
													layoutDependency={layoutDependency}
													layoutId={"oqbw3_SlH"}
													optimized={true}
													style={{
														transformPerspective: 1200,
													}}
												>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-1rz2mha"}
														data-framer-name={"Text"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"cJqWpTrBn"}
														style={{
															"--framer-paragraph-spacing": "0px",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.h3
																className={"framer-styles-preset-pc4qxs"}
																data-styles-preset={"TwcPoWkXd"}
															>
																{"Newsroom"}
															</motion.h3>
														</React.Fragment>
													</RichText>
												</MotionDivWithFXWithOptimizedAppearEffect>
											</motion.a>
										</Link>
									</motion.div>
									{isDisplayed2() && (
										<motion.div
											className={"framer-1cyd6rs"}
											data-framer-name={"Socials"}
											layoutDependency={layoutDependency}
											layoutId={"oU_iL4Jan"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1grsuke"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"bTyT9L5cU"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-labdxo"}
														data-styles-preset={"CRmxFdPaP"}
													>
														{"Socials"}
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1vb3w92"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"z2PBC4ErR"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-g8iro9"}
														data-styles-preset={"Ck1ubvtuS"}
													>
														{"Facebook"}
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1ttk7j4"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"qs42lkbGd"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-g8iro9"}
														data-styles-preset={"Ck1ubvtuS"}
													>
														{"Instagram "}
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-2boec8"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"CcCWkt8tO"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-g8iro9"}
														data-styles-preset={"Ck1ubvtuS"}
													>
														{"Linkedin "}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
									)}
								</MotionDivWithFXWithOptimizedAppearEffect>
							)}
							{isDisplayed1() && (
								<motion.div
									className={"framer-10059vx"}
									data-framer-name={"Background"}
									layoutDependency={layoutDependency}
									layoutId={"WDbsmHXY_"}
									style={{
										backgroundColor:
											"var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255))",
									}}
									variants={{
										KKdEHoWpz: {
											backgroundColor:
												"var(--token-0cdad307-f7d4-4932-883c-e1621a2e3092, rgb(23, 23, 23))",
										},
										U0Jm9JqP3: {
											backgroundColor:
												"var(--token-0cdad307-f7d4-4932-883c-e1621a2e3092, rgb(23, 23, 23))",
										},
									}}
								/>
							)}
						</motion.div>
					</motion.nav>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-NGAAt.framer-144yhwp, .framer-NGAAt .framer-144yhwp { display: block; }",
	".framer-NGAAt.framer-luk7l9 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1200px; }",
	".framer-NGAAt .framer-1eq68fo { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; max-width: 1800px; overflow: visible; padding: 16px 24px 16px 24px; position: relative; width: 100%; }",
	".framer-NGAAt .framer-t0jxjr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 6; }",
	".framer-NGAAt .framer-12t9255 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-NGAAt .framer-49xcz0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-NGAAt .framer-1jzozk3 { align-content: center; align-items: center; aspect-ratio: 3.84 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 21px); justify-content: center; padding: 0px; position: relative; width: 82px; }",
	".framer-NGAAt .framer-1bzjg17 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 1px; z-index: 2; }",
	".framer-NGAAt .framer-1hd35vz { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-NGAAt .framer-bcze4r-container, .framer-NGAAt .framer-1atvq5v-container, .framer-NGAAt .framer-1n3167m-container, .framer-NGAAt .framer-1cl2you-container, .framer-NGAAt .framer-rzejpt-container, .framer-NGAAt .framer-10t98hw-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-NGAAt .framer-16lx6jx { cursor: pointer; flex: none; height: 32px; overflow: visible; position: relative; width: 32px; }",
	".framer-NGAAt .framer-1nane18-container { flex: none; height: 32px; left: calc(50.00000000000002% - 32px / 2); position: absolute; top: calc(50.00000000000002% - 32px / 2); width: 32px; }",
	".framer-NGAAt .framer-13lhw0b { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; height: 1px; justify-content: space-between; overflow: auto; padding: 24px 12px 24px 13px; position: relative; width: 100%; z-index: 5; }",
	".framer-NGAAt .framer-j0t94i { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-NGAAt .framer-1a1iit0, .framer-NGAAt .framer-ayjy3x, .framer-NGAAt .framer-c8l9jk, .framer-NGAAt .framer-gfxtd3, .framer-NGAAt .framer-139xtf8, .framer-NGAAt .framer-meym80, .framer-NGAAt .framer-1msws2u { align-content: flex-end; align-items: flex-end; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; text-decoration: none; width: 100%; }",
	".framer-NGAAt .framer-mixzlz, .framer-NGAAt .framer-i83ztx, .framer-NGAAt .framer-19kcz6v, .framer-NGAAt .framer-1himkcf, .framer-NGAAt .framer-3pzsx0, .framer-NGAAt .framer-1inoz4k, .framer-NGAAt .framer-8n8815 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-NGAAt .framer-x2f2r0, .framer-NGAAt .framer-4rlaci, .framer-NGAAt .framer-1wb328p, .framer-NGAAt .framer-1swrqrn, .framer-NGAAt .framer-1257ujl, .framer-NGAAt .framer-1elu7k4, .framer-NGAAt .framer-1rz2mha, .framer-NGAAt .framer-1grsuke, .framer-NGAAt .framer-1vb3w92, .framer-NGAAt .framer-1ttk7j4, .framer-NGAAt .framer-2boec8 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-NGAAt .framer-1cyd6rs { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-end; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-NGAAt .framer-10059vx { flex: none; gap: 24px; height: 100%; left: calc(50.00000000000002% - 100% / 2); overflow: hidden; position: absolute; top: 0px; width: 100%; z-index: 0; }",
	".framer-NGAAt.framer-v-1mn2n7f.framer-luk7l9 { padding: 16px 0px 16px 0px; width: 390px; }",
	".framer-NGAAt.framer-v-1mn2n7f .framer-1eq68fo { padding: 0px; }",
	".framer-NGAAt.framer-v-1mn2n7f .framer-t0jxjr { padding: 0px 12px 0px 12px; }",
	".framer-NGAAt.framer-v-1mn2n7f .framer-12t9255, .framer-NGAAt.framer-v-1scwshe .framer-12t9255 { justify-content: flex-start; }",
	".framer-NGAAt.framer-v-1mn2n7f .framer-10059vx { left: 0px; right: 0px; top: -72px; width: unset; }",
	".framer-NGAAt.framer-v-1scwshe.framer-luk7l9 { width: 390px; }",
	".framer-NGAAt.framer-v-1scwshe .framer-1eq68fo { align-content: flex-start; align-items: flex-start; height: calc(var(--framer-viewport-height, 100vh) * 1); overflow: hidden; padding: 16px 0px 16px 0px; }",
	".framer-NGAAt.framer-v-1scwshe .framer-t0jxjr { padding: 0px 12px 0px 12px; position: sticky; top: 0px; z-index: 4; }",
	".framer-NGAAt.framer-v-1scwshe .framer-1a1iit0 { order: 0; }",
	".framer-NGAAt.framer-v-1scwshe .framer-ayjy3x { order: 1; }",
	".framer-NGAAt.framer-v-1scwshe .framer-c8l9jk { order: 2; }",
	".framer-NGAAt.framer-v-1scwshe .framer-gfxtd3 { order: 3; }",
	".framer-NGAAt.framer-v-1scwshe .framer-139xtf8 { order: 5; }",
	".framer-NGAAt.framer-v-1scwshe .framer-meym80 { order: 6; }",
	".framer-NGAAt.framer-v-1scwshe .framer-1msws2u { order: 4; }",
	".framer-NGAAt.framer-v-1scwshe .framer-10059vx { left: 0px; overflow: visible; right: 0px; width: unset; }",
	...css3,
	...css2,
	...css,
];
var FramerPlccV7KaQ = withCSS(Component, css4, "framer-NGAAt");
var stdin_default4 = FramerPlccV7KaQ;
FramerPlccV7KaQ.displayName = "Nav Content";
FramerPlccV7KaQ.defaultProps = {
	height: 75,
	width: 1200,
};
addPropertyControls(FramerPlccV7KaQ, {
	variant: {
		options: ["yQcF0UXXQ", "KKdEHoWpz", "U0Jm9JqP3"],
		optionTitles: ["Desktop", "Phone", "Phone Open"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerPlccV7KaQ,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...MinimalLinkFonts,
		...PrimaryFonts,
		...HamburgerFonts,
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:nav-content
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavContentFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var nav_content_default = ComponentWithRoot;
export { nav_content_default as default };
