// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0d2be16cf4ecf57c "Anker (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone' // Variant
 * activePage?: string // Active Page
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-BRGTNG7B.js";
import { routes } from "./chunks/chunk-QR7ZKMZ2.js";

// virtual:newsroom-filters
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/bC1pJI0jRp0YhtujSpZ3/d65rE7YVUZanbETkLLOO/VoDsESTS8.js
import { jsx as _jsx2, Fragment as _Fragment } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ChildrenCanSuspend,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	PathVariablesContext,
	ResolveLinks,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useQueryData,
	useRouter,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/7e0n9T6r80ZEXPPxyWwA/DypHziQJhuCS8HxniPDh/pjV7ppLnx.js
import {
	addPropertyControls as e4,
	ControlType as t4,
	QueryCache as l2,
	QueryEngine as i3,
} from "unframer";

// /:https://framerusercontent.com/modules/7e0n9T6r80ZEXPPxyWwA/DypHziQJhuCS8HxniPDh/pjV7ppLnx-0.js
import { ControlType as v } from "unframer";
import { ControlType as P } from "unframer";
var t;
var e = Object.create;
var r = Object.defineProperty;
var n = Object.getOwnPropertyDescriptor;
var i = Object.getOwnPropertyNames;
var s = Object.getPrototypeOf;
var a = Object.prototype.hasOwnProperty;
var o = (t32, e42, n22) =>
	e42 in t32
		? r(t32, e42, {
				enumerable: true,
				configurable: true,
				writable: true,
				value: n22,
			})
		: (t32[e42] = n22);
var u = (t32, e42) =>
	function () {
		return (
			e42 ||
				(0, t32[i(t32)[0]])(
					(e42 = {
						exports: {},
					}).exports,
					e42,
				),
			e42.exports
		);
	};
var l = (t32, e42, s22, o22) => {
	if ((e42 && "object" == typeof e42) || "function" == typeof e42)
		for (let u22 of i(e42))
			a.call(t32, u22) ||
				u22 === s22 ||
				r(t32, u22, {
					get: () => e42[u22],
					enumerable: !(o22 = n(e42, u22)) || o22.enumerable,
				});
	return t32;
};
var h = (t32, n22, i22) => (
	(i22 = null != t32 ? e(s(t32)) : {}),
	l(
		// If the importer is in node compatibility mode or this is not an ESM
		// file that has been converted to a CommonJS file using a Babel-
		// compatible transform (i.e. "__esModule" has not been set), then set
		// "default" to the CommonJS "module.exports" for node compatibility.
		!n22 && t32 && t32.__esModule
			? i22
			: r(i22, "default", {
					value: t32,
					enumerable: true,
				}),
		t32,
	)
);
var c = (t32, e42, r22) => o(t32, "symbol" != typeof e42 ? e42 + "" : e42, r22);
var f = u({
	"../../../node_modules/dataloader/index.js"(t32, e42) {
		var r22,
			n22 = /* @__PURE__ */ (function () {
				function t42(t5, e6) {
					if ("function" != typeof t5)
						throw TypeError(
							"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but got: " +
								t5 +
								".",
						);
					(this._batchLoadFn = t5),
						(this._maxBatchSize = (function (t6) {
							if (!(!t6 || false !== t6.batch)) return 1;
							var e7 = t6 && t6.maxBatchSize;
							if (void 0 === e7) return 1 / 0;
							if ("number" != typeof e7 || e7 < 1)
								throw TypeError(
									"maxBatchSize must be a positive number: " + e7,
								);
							return e7;
						})(e6)),
						(this._batchScheduleFn = (function (t6) {
							var e7 = t6 && t6.batchScheduleFn;
							if (void 0 === e7) return i22;
							if ("function" != typeof e7)
								throw TypeError("batchScheduleFn must be a function: " + e7);
							return e7;
						})(e6)),
						(this._cacheKeyFn = (function (t6) {
							var e7 = t6 && t6.cacheKeyFn;
							if (void 0 === e7)
								return function (t7) {
									return t7;
								};
							if ("function" != typeof e7)
								throw TypeError("cacheKeyFn must be a function: " + e7);
							return e7;
						})(e6)),
						(this._cacheMap = (function (t6) {
							if (!(!t6 || false !== t6.cache)) return null;
							var e7 = t6 && t6.cacheMap;
							if (void 0 === e7) return /* @__PURE__ */ new Map();
							if (null !== e7) {
								var r3 = ["get", "set", "delete", "clear"].filter(
									function (t7) {
										return e7 && "function" != typeof e7[t7];
									},
								);
								if (0 !== r3.length)
									throw TypeError(
										"Custom cacheMap missing methods: " + r3.join(", "),
									);
							}
							return e7;
						})(e6)),
						(this._batch = null),
						(this.name = e6 && e6.name ? e6.name : null);
				}
				var e5 = t42.prototype;
				return (
					(e5.load = function (t5) {
						if (null == t5)
							throw TypeError(
								"The loader.load() function must be called with a value, but got: " +
									String(t5) +
									".",
							);
						var e6 = (function (t6) {
								var e7 = t6._batch;
								if (
									null !== e7 &&
									!e7.hasDispatched &&
									e7.keys.length < t6._maxBatchSize
								)
									return e7;
								var r4 = {
									hasDispatched: false,
									keys: [],
									callbacks: [],
								};
								return (
									(t6._batch = r4),
									t6._batchScheduleFn(function () {
										(function (t7, e8) {
											var r5;
											if (((e8.hasDispatched = true), 0 === e8.keys.length)) {
												a22(e8);
												return;
											}
											try {
												r5 = t7._batchLoadFn(e8.keys);
											} catch (r6) {
												return s22(
													t7,
													e8,
													TypeError(
														"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function errored synchronously: " +
															String(r6) +
															".",
													),
												);
											}
											if (!r5 || "function" != typeof r5.then)
												return s22(
													t7,
													e8,
													TypeError(
														"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise: " +
															String(r5) +
															".",
													),
												);
											r5.then(function (t8) {
												if (!o22(t8))
													throw TypeError(
														"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array: " +
															String(t8) +
															".",
													);
												if (t8.length !== e8.keys.length)
													throw TypeError(
														"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.\n\nKeys:\n" +
															String(e8.keys) +
															"\n\nValues:\n" +
															String(t8),
													);
												a22(e8);
												for (var r6 = 0; r6 < e8.callbacks.length; r6++) {
													var n4 = t8[r6];
													n4 instanceof Error
														? e8.callbacks[r6].reject(n4)
														: e8.callbacks[r6].resolve(n4);
												}
											}).catch(function (r6) {
												s22(t7, e8, r6);
											});
										})(t6, r4);
									}),
									r4
								);
							})(this),
							r3 = this._cacheMap,
							n32 = this._cacheKeyFn(t5);
						if (r3) {
							var i32 = r3.get(n32);
							if (i32) {
								var u22 = e6.cacheHits || (e6.cacheHits = []);
								return new Promise(function (t6) {
									u22.push(function () {
										t6(i32);
									});
								});
							}
						}
						e6.keys.push(t5);
						var l22 = new Promise(function (t6, r4) {
							e6.callbacks.push({
								resolve: t6,
								reject: r4,
							});
						});
						return r3 && r3.set(n32, l22), l22;
					}),
					(e5.loadMany = function (t5) {
						if (!o22(t5))
							throw TypeError(
								"The loader.loadMany() function must be called with Array<key> but got: " +
									t5 +
									".",
							);
						for (var e6 = [], r3 = 0; r3 < t5.length; r3++)
							e6.push(
								this.load(t5[r3]).catch(function (t6) {
									return t6;
								}),
							);
						return Promise.all(e6);
					}),
					(e5.clear = function (t5) {
						var e6 = this._cacheMap;
						if (e6) {
							var r3 = this._cacheKeyFn(t5);
							e6.delete(r3);
						}
						return this;
					}),
					(e5.clearAll = function () {
						var t5 = this._cacheMap;
						return t5 && t5.clear(), this;
					}),
					(e5.prime = function (t5, e6) {
						var r3 = this._cacheMap;
						if (r3) {
							var n32,
								i32 = this._cacheKeyFn(t5);
							void 0 === r3.get(i32) &&
								(e6 instanceof Error
									? (n32 = Promise.reject(e6)).catch(function () {})
									: (n32 = Promise.resolve(e6)),
								r3.set(i32, n32));
						}
						return this;
					}),
					t42
				);
			})(),
			i22 =
				"object" == typeof process && "function" == typeof process.nextTick
					? function (t42) {
							r22 || (r22 = Promise.resolve()),
								r22.then(function () {
									process.nextTick(t42);
								});
						}
					: "function" == typeof setImmediate
						? function (t42) {
								setImmediate(t42);
							}
						: function (t42) {
								setTimeout(t42);
							};
		function s22(t42, e5, r3) {
			a22(e5);
			for (var n32 = 0; n32 < e5.keys.length; n32++)
				t42.clear(e5.keys[n32]), e5.callbacks[n32].reject(r3);
		}
		function a22(t42) {
			if (t42.cacheHits)
				for (var e5 = 0; e5 < t42.cacheHits.length; e5++) t42.cacheHits[e5]();
		}
		function o22(t42) {
			return (
				"object" == typeof t42 &&
				null !== t42 &&
				"number" == typeof t42.length &&
				(0 === t42.length ||
					(t42.length > 0 &&
						Object.prototype.hasOwnProperty.call(t42, t42.length - 1)))
			);
		}
		e42.exports = n22;
	},
});
var d = h(f());
var g = {
	Uint8: 1,
	Uint16: 2,
	Uint32: 4,
	BigUint64: 8,
	Int8: 1,
	Int16: 2,
	Int32: 4,
	BigInt64: 8,
	Float32: 4,
	Float64: 8,
};
var y = class {
	getOffset() {
		return this.offset;
	}
	ensureLength(t32) {
		let e42 = this.bytes.length;
		if (!(this.offset + t32 <= e42)) throw Error("Reading out of bounds");
	}
	readUint8() {
		let t32 = g.Uint8;
		this.ensureLength(t32);
		let e42 = this.view.getUint8(this.offset);
		return (this.offset += t32), e42;
	}
	readUint16() {
		let t32 = g.Uint16;
		this.ensureLength(t32);
		let e42 = this.view.getUint16(this.offset);
		return (this.offset += t32), e42;
	}
	readUint32() {
		let t32 = g.Uint32;
		this.ensureLength(t32);
		let e42 = this.view.getUint32(this.offset);
		return (this.offset += t32), e42;
	}
	readUint64() {
		let t32 = this.readBigUint64();
		return Number(t32);
	}
	readBigUint64() {
		let t32 = g.BigUint64;
		this.ensureLength(t32);
		let e42 = this.view.getBigUint64(this.offset);
		return (this.offset += t32), e42;
	}
	readInt8() {
		let t32 = g.Int8;
		this.ensureLength(t32);
		let e42 = this.view.getInt8(this.offset);
		return (this.offset += t32), e42;
	}
	readInt16() {
		let t32 = g.Int16;
		this.ensureLength(t32);
		let e42 = this.view.getInt16(this.offset);
		return (this.offset += t32), e42;
	}
	readInt32() {
		let t32 = g.Int32;
		this.ensureLength(t32);
		let e42 = this.view.getInt32(this.offset);
		return (this.offset += t32), e42;
	}
	readInt64() {
		let t32 = this.readBigInt64();
		return Number(t32);
	}
	readBigInt64() {
		let t32 = g.BigInt64;
		this.ensureLength(t32);
		let e42 = this.view.getBigInt64(this.offset);
		return (this.offset += t32), e42;
	}
	readFloat32() {
		let t32 = g.Float32;
		this.ensureLength(t32);
		let e42 = this.view.getFloat32(this.offset);
		return (this.offset += t32), e42;
	}
	readFloat64() {
		let t32 = g.Float64;
		this.ensureLength(t32);
		let e42 = this.view.getFloat64(this.offset);
		return (this.offset += t32), e42;
	}
	readBytes(t32) {
		let e42 = this.offset,
			r22 = e42 + t32,
			n22 = this.bytes.subarray(e42, r22);
		return (this.offset = r22), n22;
	}
	readString() {
		let t32 = this.readUint32(),
			e42 = this.readBytes(t32);
		return this.decoder.decode(e42);
	}
	readJson() {
		let t32 = this.readString();
		return JSON.parse(t32);
	}
	constructor(t32) {
		(this.bytes = t32),
			c(this, "offset", 0),
			c(this, "view"),
			c(this, "decoder", new TextDecoder()),
			(this.view = p(this.bytes));
	}
};
function p(t32) {
	return new DataView(t32.buffer, t32.byteOffset, t32.byteLength);
}
var m = "undefined" != typeof window;
var w = m && "function" == typeof window.requestIdleCallback;
function I(t32, ...e42) {
	if (!t32)
		throw Error(
			"Assertion Error" + (e42.length > 0 ? ": " + e42.join(" ") : ""),
		);
}
function b(t32) {
	throw Error(`Unexpected value: ${t32}`);
}
var k = (t32) => 2 ** t32 - 1;
var L = (t32) => -(2 ** (t32 - 1));
var B = (t32) => 2 ** (t32 - 1) - 1;
var E = {
	Uint8: 0,
	Uint16: 0,
	Uint32: 0,
	Uint64: 0,
	BigUint64: 0,
	Int8: L(8),
	Int16: L(16),
	Int32: L(32),
	Int64: Number.MIN_SAFE_INTEGER,
	BigInt64: -(BigInt(2) ** BigInt(63)),
};
var M = {
	Uint8: k(8),
	Uint16: k(16),
	Uint32: k(32),
	Uint64: Number.MAX_SAFE_INTEGER,
	BigUint64: BigInt(2) ** BigInt(64) - BigInt(1),
	Int8: B(8),
	Int16: B(16),
	Int32: B(32),
	Int64: Number.MAX_SAFE_INTEGER,
	BigInt64: BigInt(2) ** BigInt(63) - BigInt(1),
};
function x(t32) {
	return "string" == typeof t32;
}
function N(t32) {
	return Number.isFinite(t32);
}
function A(t32) {
	return null === t32;
}
var O = class t2 {
	static fromString(e42) {
		let [r22, n22, i22] = e42.split("/").map(Number);
		return (
			I(N(r22), "Invalid chunkId"),
			I(N(n22), "Invalid offset"),
			I(N(i22), "Invalid length"),
			new t2(r22, n22, i22)
		);
	}
	toString() {
		return `${this.chunkId}/${this.offset}/${this.length}`;
	}
	static read(e42) {
		let r22 = e42.readUint16(),
			n22 = e42.readUint32(),
			i22 = e42.readUint32();
		return new t2(r22, n22, i22);
	}
	write(t32) {
		t32.writeUint16(this.chunkId),
			t32.writeUint32(this.offset),
			t32.writeUint32(this.length);
	}
	compare(t32) {
		return this.chunkId < t32.chunkId
			? -1
			: this.chunkId > t32.chunkId
				? 1
				: this.offset < t32.offset
					? -1
					: this.offset > t32.offset
						? 1
						: (I(this.length === t32.length), 0);
	}
	constructor(t32, e42, r22) {
		(this.chunkId = t32), (this.offset = e42), (this.length = r22);
	}
};
function R(t32) {
	if (A(t32)) return 0;
	switch (t32.type) {
		case P.Array:
			return 1;
		case P.Boolean:
			return 2;
		case P.Color:
			return 3;
		case P.Date:
			return 4;
		case P.Enum:
			return 5;
		case P.File:
			return 6;
		case P.ResponsiveImage:
			return 10;
		case P.Link:
			return 7;
		case P.Number:
			return 8;
		case P.Object:
			return 9;
		case P.RichText:
			return 11;
		case P.String:
			return 12;
		case P.VectorSetItem:
			return 13;
		default:
			b(t32);
	}
}
function q(e42) {
	let r22 = e42.readUint16(),
		n22 = [];
	for (let i22 = 0; i22 < r22; i22++) {
		let r3 = t.read(e42);
		n22.push(r3);
	}
	return {
		type: P.Array,
		value: n22,
	};
}
function _(e42, r22) {
	for (let n22 of (e42.writeUint16(r22.value.length), r22.value))
		t.write(e42, n22);
}
function D(e42, r22, n22) {
	let i22 = e42.value.length,
		s22 = r22.value.length;
	if (i22 < s22) return -1;
	if (i22 > s22) return 1;
	for (let s32 = 0; s32 < i22; s32++) {
		let i32 = e42.value[s32],
			a22 = r22.value[s32],
			o22 = t.compare(i32, a22, n22);
		if (0 !== o22) return o22;
	}
	return 0;
}
function j(t32) {
	return {
		type: P.Boolean,
		value: 0 !== t32.readUint8(),
	};
}
function C(t32, e42) {
	t32.writeUint8(e42.value ? 1 : 0);
}
function J(t32, e42) {
	return t32.value < e42.value ? -1 : t32.value > e42.value ? 1 : 0;
}
function V(t32) {
	return {
		type: P.Color,
		value: t32.readString(),
	};
}
function W(t32, e42) {
	t32.writeString(e42.value);
}
function $(t32, e42) {
	return t32.value < e42.value ? -1 : t32.value > e42.value ? 1 : 0;
}
function z(t32) {
	let e42 = t32.readInt64(),
		r22 = new Date(e42);
	return {
		type: P.Date,
		value: r22.toISOString(),
	};
}
function G(t32, e42) {
	let r22 = new Date(e42.value),
		n22 = r22.getTime();
	t32.writeInt64(n22);
}
function K(t32, e42) {
	let r22 = new Date(t32.value),
		n22 = new Date(e42.value);
	return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
}
function H(t32) {
	return {
		type: P.Enum,
		value: t32.readString(),
	};
}
function X(t32, e42) {
	t32.writeString(e42.value);
}
function Q(t32, e42) {
	return t32.value < e42.value ? -1 : t32.value > e42.value ? 1 : 0;
}
function Y(t32) {
	return {
		type: P.File,
		value: t32.readString(),
	};
}
function Z(t32, e42) {
	t32.writeString(e42.value);
}
function tt(t32, e42) {
	return t32.value < e42.value ? -1 : t32.value > e42.value ? 1 : 0;
}
function te(t32) {
	return {
		type: P.Link,
		value: t32.readJson(),
	};
}
function tr(t32, e42) {
	t32.writeJson(e42.value);
}
function tn(t32, e42) {
	let r22 = JSON.stringify(t32.value),
		n22 = JSON.stringify(e42.value);
	return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
}
function ti(t32) {
	return {
		type: P.Number,
		value: t32.readFloat64(),
	};
}
function ts(t32, e42) {
	t32.writeFloat64(e42.value);
}
function ta(t32, e42) {
	return t32.value < e42.value ? -1 : t32.value > e42.value ? 1 : 0;
}
function to(e42) {
	let r22 = e42.readUint16(),
		n22 = {};
	for (let i22 = 0; i22 < r22; i22++) {
		let r3 = e42.readString();
		n22[r3] = t.read(e42);
	}
	return {
		type: P.Object,
		value: n22,
	};
}
function tu(e42, r22) {
	let n22 = Object.entries(r22.value);
	for (let [r3, i22] of (e42.writeUint16(n22.length), n22))
		e42.writeString(r3), t.write(e42, i22);
}
function tl(e42, r22, n22) {
	let i22 = Object.keys(e42.value).sort(),
		s22 = Object.keys(r22.value).sort();
	if (i22.length < s22.length) return -1;
	if (i22.length > s22.length) return 1;
	for (let a22 = 0; a22 < i22.length; a22++) {
		let o22 = i22[a22],
			u22 = s22[a22];
		if (o22 < u22) return -1;
		if (o22 > u22) return 1;
		let l22 = e42.value[o22] ?? null,
			h2 = r22.value[u22] ?? null,
			c22 = t.compare(l22, h2, n22);
		if (0 !== c22) return c22;
	}
	return 0;
}
function th(t32) {
	return {
		type: P.ResponsiveImage,
		value: t32.readJson(),
	};
}
function tc(t32, e42) {
	t32.writeJson(e42.value);
}
function tf(t32, e42) {
	let r22 = JSON.stringify(t32.value),
		n22 = JSON.stringify(e42.value);
	return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
}
function td(t32) {
	let e42 = t32.readInt8();
	if (0 === e42)
		return {
			type: P.RichText,
			value: t32.readUint32(),
		};
	if (1 === e42)
		return {
			type: P.RichText,
			value: t32.readString(),
		};
	throw Error("Invalid rich text pointer");
}
function tg(t32, e42) {
	if (N(e42.value)) {
		t32.writeInt8(0), t32.writeUint32(e42.value);
		return;
	}
	if (x(e42.value)) {
		t32.writeInt8(1), t32.writeString(e42.value);
		return;
	}
	throw Error("Invalid rich text pointer");
}
function ty(t32, e42) {
	let r22 = t32.value,
		n22 = e42.value;
	if ((N(r22) && N(n22)) || (x(r22) && x(n22)))
		return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
	throw Error("Invalid rich text pointer");
}
function tp(t32) {
	return {
		type: P.String,
		value: t32.readString(),
	};
}
function tv(t32, e42) {
	t32.writeString(e42.value);
}
function tm(t32, e42, r22) {
	let n22 = t32.value,
		i22 = e42.value;
	return (0 === r22.type &&
		((n22 = t32.value.toLowerCase()), (i22 = e42.value.toLowerCase())),
	n22 < i22)
		? -1
		: n22 > i22
			? 1
			: 0;
}
function tw(t32) {
	return {
		type: P.VectorSetItem,
		value: t32.readUint32(),
	};
}
function tI(t32, e42) {
	t32.writeUint32(e42.value);
}
function tb(t32, e42) {
	let r22 = t32.value,
		n22 = e42.value;
	return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
}
((t32) => {
	(t32.read = function (t42) {
		let e42 = t42.readUint8();
		switch (e42) {
			case 0:
				return null;
			case 1:
				return q(t42);
			case 2:
				return j(t42);
			case 3:
				return V(t42);
			case 4:
				return z(t42);
			case 5:
				return H(t42);
			case 6:
				return Y(t42);
			case 7:
				return te(t42);
			case 8:
				return ti(t42);
			case 9:
				return to(t42);
			case 10:
				return th(t42);
			case 11:
				return td(t42);
			case 12:
				return tp(t42);
			case 13:
				return tw(t42);
			default:
				b(e42);
		}
	}),
		(t32.write = function (t42, e42) {
			let r22 = R(e42);
			if ((t42.writeUint8(r22), !A(e42)))
				switch (e42.type) {
					case P.Array:
						return _(t42, e42);
					case P.Boolean:
						return C(t42, e42);
					case P.Color:
						return W(t42, e42);
					case P.Date:
						return G(t42, e42);
					case P.Enum:
						return X(t42, e42);
					case P.File:
						return Z(t42, e42);
					case P.Link:
						return tr(t42, e42);
					case P.Number:
						return ts(t42, e42);
					case P.Object:
						return tu(t42, e42);
					case P.ResponsiveImage:
						return tc(t42, e42);
					case P.RichText:
						return tg(t42, e42);
					case P.VectorSetItem:
						return tI(t42, e42);
					case P.String:
						return tv(t42, e42);
					default:
						b(e42);
				}
		}),
		(t32.compare = function (t42, e42, r22) {
			let n22 = R(t42),
				i22 = R(e42);
			if (n22 < i22) return -1;
			if (n22 > i22) return 1;
			if (A(t42) || A(e42)) return 0;
			switch (t42.type) {
				case P.Array:
					return I(e42.type === P.Array), D(t42, e42, r22);
				case P.Boolean:
					return I(e42.type === P.Boolean), J(t42, e42);
				case P.Color:
					return I(e42.type === P.Color), $(t42, e42);
				case P.Date:
					return I(e42.type === P.Date), K(t42, e42);
				case P.Enum:
					return I(e42.type === P.Enum), Q(t42, e42);
				case P.File:
					return I(e42.type === P.File), tt(t42, e42);
				case P.Link:
					return I(e42.type === P.Link), tn(t42, e42);
				case P.Number:
					return I(e42.type === P.Number), ta(t42, e42);
				case P.Object:
					return I(e42.type === P.Object), tl(t42, e42, r22);
				case P.ResponsiveImage:
					return I(e42.type === P.ResponsiveImage), tf(t42, e42);
				case P.RichText:
					return I(e42.type === P.RichText), ty(t42, e42);
				case P.VectorSetItem:
					return I(e42.type === P.VectorSetItem), tb(t42, e42);
				case P.String:
					return I(e42.type === P.String), tm(t42, e42, r22);
				default:
					b(t42);
			}
		});
})(t || (t = {}));
var tS = 3;
var tk = 250;
var tL = [
	408,
	// Request Timeout
	429,
	// Too Many Requests
	500,
	// Internal Server Error
	502,
	// Bad Gateway
	503,
	// Service Unavailable
	504,
];
var tB = async (t32, e42) => {
	let r22 = 0;
	for (;;) {
		try {
			let n22 = await fetch(t32, e42);
			if (!tL.includes(n22.status) || ++r22 > tS) return n22;
		} catch (t42) {
			if (e42?.signal?.aborted || ++r22 > tS) throw t42;
		}
		await tE(r22);
	}
};
async function tE(t32) {
	let e42 = Math.floor(tk * (Math.random() + 1) * 2 ** (t32 - 1));
	await new Promise((t42) => {
		setTimeout(t42, e42);
	});
}
async function tM(t32, e42) {
	let r22 = tx(e42),
		n22 = [],
		i22 = 0;
	for (let t42 of r22)
		n22.push(`${t42.from}-${t42.to - 1}`), (i22 += t42.to - t42.from);
	let s22 = new URL(t32),
		a22 = n22.join(",");
	s22.searchParams.set("range", a22);
	let o22 = await tB(s22);
	if (200 !== o22.status)
		throw Error(`Request failed: ${o22.status} ${o22.statusText}`);
	let u22 = await o22.arrayBuffer(),
		l22 = new Uint8Array(u22);
	if (l22.length !== i22)
		throw Error("Request failed: Unexpected response length");
	let h2 = new tT(),
		c22 = 0;
	for (let t42 of r22) {
		let e5 = t42.to - t42.from,
			r3 = c22 + e5,
			n32 = l22.subarray(c22, r3);
		h2.write(t42.from, n32), (c22 = r3);
	}
	return e42.map((t42) => h2.read(t42.from, t42.to - t42.from));
}
var tT = class {
	read(t32, e42) {
		for (let r22 of this.chunks) {
			if (t32 < r22.start) break;
			if (t32 > r22.end) continue;
			if (t32 + e42 > r22.end) break;
			let n22 = t32 - r22.start,
				i22 = n22 + e42;
			return r22.data.slice(n22, i22);
		}
		throw Error("Missing data");
	}
	write(t32, e42) {
		let r22 = t32,
			n22 = r22 + e42.length,
			i22 = 0,
			s22 = this.chunks.length;
		for (; i22 < s22; i22++) {
			let t42 = this.chunks[i22];
			if ((I(t42, "Missing chunk"), !(r22 > t42.end))) {
				if (r22 > t42.start) {
					let n32 = r22 - t42.start,
						i32 = t42.data.subarray(0, n32);
					(e42 = tF(i32, e42)), (r22 = t42.start);
				}
				break;
			}
		}
		for (; s22 > i22; s22--) {
			let t42 = this.chunks[s22 - 1];
			if ((I(t42, "Missing chunk"), !(n22 < t42.start))) {
				if (n22 < t42.end) {
					let r3 = n22 - t42.start,
						i32 = t42.data.subarray(r3);
					(e42 = tF(e42, i32)), (n22 = t42.end);
				}
				break;
			}
		}
		let a22 = {
				start: r22,
				end: n22,
				data: e42,
			},
			o22 = s22 - i22;
		this.chunks.splice(i22, o22, a22);
	}
	constructor() {
		c(this, "chunks", []);
	}
};
function tF(t32, e42) {
	let r22 = t32.length + e42.length,
		n22 = new Uint8Array(r22);
	return n22.set(t32, 0), n22.set(e42, t32.length), n22;
}
function tx(t32) {
	I(t32.length > 0, "Must have at least one range");
	let e42 = [...t32].sort((t42, e5) => t42.from - e5.from),
		r22 = [];
	for (let t42 of e42) {
		let e5 = r22.length - 1,
			n22 = r22[e5];
		n22 && t42.from <= n22.to
			? (r22[e5] = {
					from: n22.from,
					to: Math.max(n22.to, t42.to),
				})
			: r22.push(t42);
	}
	return r22;
}
var tA = class e3 {
	static read(r22) {
		let n22 = new e3(),
			i22 = r22.readUint16();
		for (let e42 = 0; e42 < i22; e42++) {
			let e5 = r22.readString(),
				i32 = t.read(r22);
			n22.setField(e5, i32);
		}
		return n22;
	}
	write(e42) {
		for (let [r22, n22] of (e42.writeUint16(this.fields.size), this.fields))
			e42.writeString(r22), t.write(e42, n22);
	}
	getData() {
		let t32 = {};
		for (let [e42, r22] of this.fields) t32[e42] = r22;
		return t32;
	}
	setField(t32, e42) {
		this.fields.set(t32, e42);
	}
	getField(t32) {
		return this.fields.get(t32);
	}
	constructor() {
		c(this, "fields", /* @__PURE__ */ new Map());
	}
};
var tO = class {
	scanItems() {
		return (
			(this.itemsPromise ??= tB(this.url).then(async (t32) => {
				if (!t32.ok)
					throw Error(`Request failed: ${t32.status} ${t32.statusText}`);
				let e42 = await t32.arrayBuffer(),
					r22 = new Uint8Array(e42),
					n22 = new y(r22),
					i22 = [],
					s22 = n22.readUint32();
				for (let t42 = 0; t42 < s22; t42++) {
					let t5 = n22.getOffset(),
						e5 = tA.read(n22),
						r3 = n22.getOffset() - t5,
						s32 = new O(this.id, t5, r3),
						a22 = s32.toString(),
						o22 = {
							pointer: a22,
							data: e5.getData(),
						};
					this.itemLoader.prime(a22, o22), i22.push(o22);
				}
				return i22;
			})),
			this.itemsPromise
		);
	}
	resolveItem(t32) {
		return this.itemLoader.load(t32);
	}
	constructor(t32, e42) {
		(this.id = t32),
			(this.url = e42),
			c(this, "itemsPromise"),
			c(
				this,
				"itemLoader",
				new d.default(async (t42) => {
					let e5 = t42.map((t5) => {
							let e6 = O.fromString(t5);
							return {
								from: e6.offset,
								to: e6.offset + e6.length,
							};
						}),
						r22 = await tM(this.url, e5);
					return r22.map((e6, r3) => {
						let n22 = new y(e6),
							i22 = tA.read(n22),
							s22 = t42[r3];
						return (
							I(s22, "Missing pointer"),
							{
								pointer: s22,
								data: i22.getData(),
							}
						);
					});
				}),
			);
	}
};
var tP = class {
	async scanItems() {
		let t32 = await Promise.all(
			this.chunks.map(async (t42) => t42.scanItems()),
		);
		return t32.flat();
	}
	async resolveItems(t32) {
		return Promise.all(
			t32.map((t42) => {
				let e42 = O.fromString(t42),
					r22 = this.chunks[e42.chunkId];
				return I(r22, "Missing chunk"), r22.resolveItem(t42);
			}),
		);
	}
	compareItems(t32, e42) {
		let r22 = O.fromString(t32.pointer),
			n22 = O.fromString(e42.pointer);
		return r22.compare(n22);
	}
	compareValues(e42, r22, n22) {
		return t.compare(e42, r22, n22);
	}
	constructor(t32) {
		(this.options = t32),
			c(this, "schema"),
			c(this, "indexes"),
			c(this, "resolveRichText"),
			c(this, "resolveVectorSetItem"),
			c(this, "chunks"),
			(this.chunks = this.options.chunks.map((t42, e42) => new tO(e42, t42))),
			(this.schema = t32.schema),
			(this.indexes = t32.indexes),
			(this.resolveRichText = t32.resolveRichText),
			(this.resolveVectorSetItem = t32.resolveVectorSetItem);
	}
};

// /:https://framerusercontent.com/modules/7e0n9T6r80ZEXPPxyWwA/DypHziQJhuCS8HxniPDh/pjV7ppLnx-1.js
import { jsx as e2 } from "react/jsx-runtime";
import {
	ComponentPresetsConsumer as r2,
	Link as t3,
	motion as n2,
} from "unframer";
import { Fragment as o2, createElement as a2 } from "react";
function i2(e22, ...r22) {
	if (!e22)
		throw Error(
			"Assertion Error" + (r22.length > 0 ? ": " + r22.join(" ") : ""),
		);
}
var u2;
var s2 =
	(((u2 = s2 || {})[(u2.Fragment = 1)] = "Fragment"),
	(u2[(u2.Link = 2)] = "Link"),
	(u2[(u2.Module = 3)] = "Module"),
	(u2[(u2.Tag = 4)] = "Tag"),
	(u2[(u2.Text = 5)] = "Text"),
	u2);
function c2(u22) {
	let s22 = /* @__PURE__ */ new Map();
	return (c22) => {
		let l3 = s22.get(c22);
		if (l3) return l3;
		let m3 = JSON.parse(c22),
			f2 = (function s32(c3) {
				switch (c3[0]) {
					case 1: {
						let [, ...e22] = c3,
							r22 = e22.map(s32);
						return a2(o2, void 0, ...r22);
					}
					case 2: {
						let [, e22, ...r22] = c3,
							n22 = r22.map(s32);
						return a2(t3, e22, ...n22);
					}
					case 3: {
						let [, t22, n22] = c3,
							o22 = u22[t22];
						return (
							i2(o22, "Module not found"),
							e2(r2, {
								componentIdentifier: t22,
								children: (r22) =>
									e2(o22, {
										...r22,
										...n22,
									}),
							})
						);
					}
					case 4: {
						let [, e22, r22, ...t22] = c3,
							o22 = t22.map(s32);
						if ("a" === e22) return <n2.a />;
						return a2(e22, r22, ...o22);
					}
					case 5: {
						let [, e22] = c3;
						return e22;
					}
				}
			})(m3);
		return s22.set(c22, f2), f2;
	};
}

// /:https://framerusercontent.com/modules/7e0n9T6r80ZEXPPxyWwA/DypHziQJhuCS8HxniPDh/pjV7ppLnx.js
var n3 = {
	id: {
		isNullable: false,
		type: t4.String,
	},
	jg_uNk_rb: {
		isNullable: true,
		type: t4.String,
	},
	jGD_IK02W: {
		isNullable: true,
		type: t4.String,
	},
	nextItemId: {
		isNullable: true,
		type: t4.String,
	},
	previousItemId: {
		isNullable: true,
		type: t4.String,
	},
	StLmAHlOq: {
		isNullable: true,
		type: t4.Enum,
	},
};
var p2 = [];
var o3 = (e22) => {
	let t22 = p2[e22];
	if (t22) return t22().then((e32) => e32.default);
};
var u3 = {};
var m2 = c2(u3);
var s3 = new i3();
var y2 = new l2(s3);
var d2 = {
	collectionByLocaleId: {
		default: new tP({
			chunks: [
				new URL(
					"./pjV7ppLnx-chunk-default-0.framercms",
					"https://framerusercontent.com/modules/7e0n9T6r80ZEXPPxyWwA/DypHziQJhuCS8HxniPDh/pjV7ppLnx.js",
				).href.replace("/modules/", "/cms/"),
			],
			indexes: [],
			resolveRichText: m2,
			resolveVectorSetItem: o3,
			schema: n3,
		}),
	},
	displayName: "Filters",
};
var stdin_default = d2;
e4(d2, {
	jGD_IK02W: {
		defaultValue: "",
		title: "Title",
		type: t4.String,
	},
	jg_uNk_rb: {
		title: "Slug",
		type: t4.String,
	},
	StLmAHlOq: {
		defaultValue: "CHzWCaqWW",
		options: ["CHzWCaqWW", "JhszTXRTW"],
		optionTitles: ["All", "Blog Type"],
		title: "Option",
		type: t4.Enum,
	},
	previousItemId: {
		dataIdentifier: "local-module:collection/pjV7ppLnx:default",
		title: "Previous",
		type: t4.CollectionReference,
	},
	nextItemId: {
		dataIdentifier: "local-module:collection/pjV7ppLnx:default",
		title: "Next",
		type: t4.CollectionReference,
	},
});

// /:https://framerusercontent.com/modules/eGgyQxxM4sxvxke51ARw/W0TUcJzeFQmENZMh4nze/trHLvt8km.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	nJaNAcrfK: {
		hover: true,
	},
};
var cycleOrder = ["z5wuxA7GC", "nJaNAcrfK", "NxiW6qyCb", "kK7NZp1NO"];
var serializationHash = "framer-bvjj7";
var variantClassNames = {
	kK7NZp1NO: "framer-v-1s8huod",
	nJaNAcrfK: "framer-v-qwmu7c",
	NxiW6qyCb: "framer-v-cm72a8",
	z5wuxA7GC: "framer-v-17xscag",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 24,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var transition2 = {
	delay: 0,
	duration: 0.7,
	ease: [0.08, 0.78, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Active (Phone)": "NxiW6qyCb",
	"Inactive (Phone)": "kK7NZp1NO",
	Active: "z5wuxA7GC",
	Inactive: "nJaNAcrfK",
};
var getProps = ({ height, id, link, title, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "z5wuxA7GC",
		vO9qDenF4: link ?? props.vO9qDenF4,
		YBPeTYkxW: title ?? props.YBPeTYkxW ?? "Title",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		YBPeTYkxW,
		vO9qDenF4,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "z5wuxA7GC",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							nJaNAcrfK: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-17xscag",
							className2,
							classNames,
						)}
						data-framer-name={"Active"}
						layoutDependency={layoutDependency}
						layoutId={"z5wuxA7GC"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								"nJaNAcrfK-hover": {
									"data-framer-name": void 0,
								},
								kK7NZp1NO: {
									"data-framer-name": "Inactive (Phone)",
								},
								nJaNAcrfK: {
									"data-framer-name": "Inactive",
								},
								NxiW6qyCb: {
									"data-framer-name": "Active (Phone)",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Link
							href={vO9qDenF4}
							motionChild={true}
							nodeId={"KFOkeHiWc"}
							scopeId={"trHLvt8km"}
						>
							<motion.a
								className={"framer-4qkhx9 framer-1f4vd0r"}
								data-framer-name={"Wrap"}
								layoutDependency={layoutDependency}
								layoutId={"KFOkeHiWc"}
							>
								<motion.div
									className={"framer-1elwpe2"}
									data-framer-name={"Top"}
									layoutDependency={layoutDependency}
									layoutId={"I1jCjJSyD"}
									{...addPropertyOverrides(
										{
											"nJaNAcrfK-hover": {
												tabIndex: -1,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1lj51fh"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"SUShtH3cU"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255))",
										}}
										text={YBPeTYkxW}
										variants={{
											kK7NZp1NO: {
												"--extracted-r6o4lv":
													"var(--token-aa4b05ac-cb0a-4952-a6ee-9d49e45f217d, rgb(122, 122, 122))",
											},
											nJaNAcrfK: {
												"--extracted-r6o4lv":
													"var(--token-aa4b05ac-cb0a-4952-a6ee-9d49e45f217d, rgb(122, 122, 122))",
											},
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												kK7NZp1NO: {
													children: (
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-cpwznz"}
																data-styles-preset={"ls_KuhAAC"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-aa4b05ac-cb0a-4952-a6ee-9d49e45f217d, rgb(122, 122, 122)))",
																}}
															>
																{"Title"}
															</motion.p>
														</React.Fragment>
													),
												},
												nJaNAcrfK: {
													children: (
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-cpwznz"}
																data-styles-preset={"ls_KuhAAC"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-aa4b05ac-cb0a-4952-a6ee-9d49e45f217d, rgb(122, 122, 122)))",
																}}
															>
																{"Title"}
															</motion.p>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-cpwznz"}
												data-styles-preset={"ls_KuhAAC"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255)))",
												}}
											>
												{"Title"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-i3diy1"}
									data-framer-name={"Bottom"}
									layoutDependency={layoutDependency}
									layoutId={"p2ax0ncpc"}
									tabIndex={-1}
									{...addPropertyOverrides(
										{
											"nJaNAcrfK-hover": {
												tabIndex: void 0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1soj3o"}
										fonts={["GF;Geist-500"]}
										layoutDependency={layoutDependency}
										layoutId={"D9iy0dKDK"}
										style={{
											"--extracted-a0htzi":
												"var(--token-252599bf-f36c-47e5-a651-baf5c3684530, rgb(30, 30, 31))",
										}}
										text={YBPeTYkxW}
										variants={{
											"nJaNAcrfK-hover": {
												"--extracted-a0htzi":
													"var(--token-aa4b05ac-cb0a-4952-a6ee-9d49e45f217d, rgb(122, 122, 122))",
											},
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												"nJaNAcrfK-hover": {
													children: (
														<React.Fragment>
															<motion.h3
																style={{
																	"--font-selector": "R0Y7R2Vpc3QtNTAw",
																	"--framer-font-family":
																		'"Geist", "Geist Placeholder", sans-serif',
																	"--framer-font-weight": "500",
																	"--framer-letter-spacing": "-0.04em",
																	"--framer-text-color":
																		"var(--extracted-a0htzi, var(--token-aa4b05ac-cb0a-4952-a6ee-9d49e45f217d, rgb(122, 122, 122)))",
																}}
															>
																{"Title"}
															</motion.h3>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.h3
												style={{
													"--font-selector": "R0Y7R2Vpc3QtNTAw",
													"--framer-font-family":
														'"Geist", "Geist Placeholder", sans-serif',
													"--framer-font-weight": "500",
													"--framer-letter-spacing": "-0.04em",
													"--framer-text-color":
														"var(--extracted-a0htzi, var(--token-252599bf-f36c-47e5-a651-baf5c3684530, rgb(30, 30, 31)))",
												}}
											>
												{"Title"}
											</motion.h3>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.a>
						</Link>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-bvjj7.framer-1f4vd0r, .framer-bvjj7 .framer-1f4vd0r { display: block; }",
	".framer-bvjj7.framer-17xscag { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 20px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-bvjj7 .framer-4qkhx9 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 100%; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-bvjj7 .framer-1elwpe2, .framer-bvjj7 .framer-i3diy1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 100%; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-bvjj7 .framer-1lj51fh, .framer-bvjj7 .framer-1soj3o { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-bvjj7.framer-v-qwmu7c.framer-17xscag { cursor: pointer; }",
	".framer-bvjj7.framer-v-qwmu7c.hover .framer-4qkhx9 { justify-content: flex-end; }",
	...css,
];
var FramertrHLvt8km = withCSS(Component, css2, "framer-bvjj7");
var stdin_default2 = FramertrHLvt8km;
FramertrHLvt8km.displayName = "Filter States";
FramertrHLvt8km.defaultProps = {
	height: 20,
	width: 29,
};
addPropertyControls(FramertrHLvt8km, {
	variant: {
		options: ["z5wuxA7GC", "nJaNAcrfK", "NxiW6qyCb", "kK7NZp1NO"],
		optionTitles: ["Active", "Inactive", "Active (Phone)", "Inactive (Phone)"],
		title: "Variant",
		type: ControlType.Enum,
	},
	YBPeTYkxW: {
		defaultValue: "Title",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	vO9qDenF4: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramertrHLvt8km,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Geist",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/geist/v4/gyBhhwUxId8gMGYQMKR3pzfaWI_RruM4mJPby1QNtA.woff2",
					weight: "500",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/bC1pJI0jRp0YhtujSpZ3/d65rE7YVUZanbETkLLOO/VoDsESTS8.js
var FilterStatesFonts = getFonts(stdin_default2);
var cycleOrder2 = ["FfgJCjQvP", "O00jWJR0X"];
var serializationHash2 = "framer-i7DAA";
var variantClassNames2 = {
	FfgJCjQvP: "framer-v-1gr7ygb",
	O00jWJR0X: "framer-v-ig8275",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var equals = (a3, b2) => {
	return typeof a3 === "string" && typeof b2 === "string"
		? a3.toLowerCase() === b2.toLowerCase()
		: a3 === b2;
};
var convertFromBoolean = (value, activeLocale) => {
	if (value) {
		return "z5wuxA7GC";
	} else {
		return "nJaNAcrfK";
	}
};
var convertFromBoolean1 = (value, activeLocale) => {
	if (value) {
		return "z5wuxA7GC";
	} else {
		return "kK7NZp1NO";
	}
};
var QueryData = ({ query: query2, pageSize, children }) => {
	const data = useQueryData(query2);
	return children(data);
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	Desktop: "FfgJCjQvP",
	Phone: "O00jWJR0X",
};
var getProps2 = ({ activePage, height, id, width, ...props }) => {
	return {
		...props,
		bQoqqwmV9: activePage ?? props.bQoqqwmV9,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "FfgJCjQvP",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		bQoqqwmV9,
		jGD_IK02Wzmy1KCvO9,
		jg_uNk_rbzmy1KCvO9,
		idzmy1KCvO9,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "FfgJCjQvP",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1gr7ygb",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						data-hide-scrollbars={true}
						layoutDependency={layoutDependency}
						layoutId={"FfgJCjQvP"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								O00jWJR0X: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-1r24chj"}
							data-framer-name={"Wrap"}
							data-hide-scrollbars={true}
							layoutDependency={layoutDependency}
							layoutId={"ow7tMfA8a"}
						>
							<motion2.div
								className={"framer-1h5w115"}
								data-framer-name={"Wrap"}
								layoutDependency={layoutDependency}
								layoutId={"m6Cen_6Lx"}
							>
								<motion2.div
									className={"framer-32su1a"}
									layoutDependency={layoutDependency}
									layoutId={"zmy1KCvO9"}
								>
									<ChildrenCanSuspend>
										<QueryData
											query={{
												from: {
													alias: "zmy1KCvO9",
													data: stdin_default,
													type: "Collection",
												},
												limit: {
													type: "LiteralValue",
													value: 10,
												},
												select: [
													{
														collection: "zmy1KCvO9",
														name: "jGD_IK02W",
														type: "Identifier",
													},
													{
														collection: "zmy1KCvO9",
														name: "jg_uNk_rb",
														type: "Identifier",
													},
													{
														collection: "zmy1KCvO9",
														name: "id",
														type: "Identifier",
													},
												],
											}}
										>
											{(collection, paginationInfo, loadMore) => (
												<_Fragment>
													{collection?.map(
														(
															{
																id: idzmy1KCvO92,
																jg_uNk_rb: jg_uNk_rbzmy1KCvO92,
																jGD_IK02W: jGD_IK02Wzmy1KCvO92,
															},
															index,
														) => {
															jGD_IK02Wzmy1KCvO92 ??= "";
															jg_uNk_rbzmy1KCvO92 ??= "";
															return (
																<LayoutGroup2 id={`zmy1KCvO9-${idzmy1KCvO92}`}>
																	<PathVariablesContext.Provider
																		value={{
																			jg_uNk_rb: jg_uNk_rbzmy1KCvO92,
																		}}
																	>
																		<ResolveLinks
																			links={[
																				{
																					href: {
																						pathVariables: {
																							jg_uNk_rb: jg_uNk_rbzmy1KCvO92,
																						},
																						webPageId: "BOK_Vkv81",
																					},
																					implicitPathVariables: void 0,
																				},
																				{
																					href: {
																						pathVariables: {
																							jg_uNk_rb: jg_uNk_rbzmy1KCvO92,
																						},
																						webPageId: "BOK_Vkv81",
																					},
																					implicitPathVariables: void 0,
																				},
																			]}
																		>
																			{(resolvedLinks) => (
																				<ComponentViewportProvider
																					height={20}
																					y={
																						(componentViewport?.y || 0) +
																						(0 +
																							((componentViewport?.height ||
																								20) -
																								0 -
																								20) /
																								2) +
																						0 +
																						0 +
																						0 +
																						0
																					}
																					{...addPropertyOverrides2(
																						{
																							O00jWJR0X: {
																								y:
																									(componentViewport?.y || 0) +
																									(0 +
																										((componentViewport?.height ||
																											20) -
																											0 -
																											20) /
																											2) +
																									0 +
																									0 +
																									0,
																							},
																						},
																						baseVariant,
																						gestureVariant,
																					)}
																				>
																					<SmartComponentScopedContainer
																						className={
																							"framer-ycpp1r-container"
																						}
																						layoutDependency={layoutDependency}
																						layoutId={"su0KMqwNG-container"}
																						nodeId={"su0KMqwNG"}
																						rendersWithMotion={true}
																						scopeId={"VoDsESTS8"}
																					>
																						{_jsx2(stdin_default2, {
																							height: "100%",
																							id: "su0KMqwNG",
																							layoutId: "su0KMqwNG",
																							variant: convertFromBoolean(
																								equals(
																									jGD_IK02Wzmy1KCvO92,
																									bQoqqwmV9,
																								),
																								activeLocale,
																							),
																							vO9qDenF4: resolvedLinks[0],
																							width: "100%",
																							YBPeTYkxW: jGD_IK02Wzmy1KCvO92,
																							...addPropertyOverrides2(
																								{
																									O00jWJR0X: {
																										variant:
																											convertFromBoolean1(
																												equals(
																													jGD_IK02Wzmy1KCvO92,
																													bQoqqwmV9,
																												),
																												activeLocale,
																											),
																										vO9qDenF4: resolvedLinks[1],
																									},
																								},
																								baseVariant,
																								gestureVariant,
																							),
																						})}
																					</SmartComponentScopedContainer>
																				</ComponentViewportProvider>
																			)}
																		</ResolveLinks>
																	</PathVariablesContext.Provider>
																</LayoutGroup2>
															);
														},
													)}
												</_Fragment>
											)}
										</QueryData>
									</ChildrenCanSuspend>
								</motion2.div>
							</motion2.div>
						</motion2.div>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-i7DAA.framer-i9an6z, .framer-i7DAA .framer-i9an6z { display: block; }",
	".framer-i7DAA.framer-1gr7ygb { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-i7DAA .framer-1r24chj { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: auto; padding: 0px; position: relative; width: min-content; }",
	".framer-i7DAA .framer-1h5w115 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-i7DAA .framer-32su1a { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; padding: 0px; position: relative; width: min-content; }",
	".framer-i7DAA .framer-ycpp1r-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-i7DAA.framer-v-ig8275.framer-1gr7ygb { width: 390px; }",
	".framer-i7DAA.framer-v-ig8275 .framer-1h5w115 { flex-direction: row; }",
	'.framer-i7DAA[data-hide-scrollbars="true"]::-webkit-scrollbar, .framer-i7DAA [data-hide-scrollbars="true"]::-webkit-scrollbar { width: 0px; height: 0px; }',
	'.framer-i7DAA[data-hide-scrollbars="true"]::-webkit-scrollbar-thumb, .framer-i7DAA [data-hide-scrollbars="true"]::-webkit-scrollbar-thumb { background: transparent; }',
	'.framer-i7DAA[data-hide-scrollbars="true"], .framer-i7DAA [data-hide-scrollbars="true"] { scrollbar-width: none; }',
];
var FramerVoDsESTS8 = withCSS2(Component2, css3, "framer-i7DAA");
var stdin_default3 = FramerVoDsESTS8;
FramerVoDsESTS8.displayName = "Newsroom Filters";
FramerVoDsESTS8.defaultProps = {
	height: 20,
	width: 214.5,
};
addPropertyControls2(FramerVoDsESTS8, {
	variant: {
		options: ["FfgJCjQvP", "O00jWJR0X"],
		optionTitles: ["Desktop", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	bQoqqwmV9: {
		defaultValue: "",
		title: "Active Page",
		type: ControlType2.String,
	},
});
addFonts2(
	FramerVoDsESTS8,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...FilterStatesFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:newsroom-filters
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "O00jWJR0X",
	xl: "FfgJCjQvP",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NewsroomFiltersFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var newsroom_filters_default = ComponentWithRoot;
export { newsroom_filters_default as default };
