// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0d2be16cf4ecf57c "Anker (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Mobile' // Variant
 * filterType?: 'All' | 'Blog Type' // Filter Type
 * filter?: string // Filter
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-55EBAKF4.js";
import { className, css, fonts } from "./chunks/chunk-OCTLECST.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-WJBYBRXL.js";
import { routes } from "./chunks/chunk-QR7ZKMZ2.js";

// virtual:newsroom-grid
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/7aOmHxu2BvbxG1cq5LLy/V5Zri2DTo6H8LChhsmnS/vJMhvJHxH.js
import {
	jsx as _jsx2,
	jsxs as _jsxs2,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ChildrenCanSuspend,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	PathVariablesContext,
	ResolveLinks,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useQueryData,
	useRouter,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/DPbNkOyYiRfvtcJMi2U2/3qef2jFiriY5WmUMLFtL/wl_dkBnh5.js
import {
	addPropertyControls as e5,
	ControlType as l3,
	QueryCache as t4,
	QueryEngine as r3,
} from "unframer";

// /:https://framerusercontent.com/modules/DPbNkOyYiRfvtcJMi2U2/3qef2jFiriY5WmUMLFtL/wl_dkBnh5-0.js
import { ControlType as v } from "unframer";
import { ControlType as P } from "unframer";
var t;
var e = Object.create;
var r = Object.defineProperty;
var n = Object.getOwnPropertyDescriptor;
var i = Object.getOwnPropertyNames;
var s = Object.getPrototypeOf;
var a = Object.prototype.hasOwnProperty;
var o = (t32, e42, n22) =>
	e42 in t32
		? r(t32, e42, {
				enumerable: true,
				configurable: true,
				writable: true,
				value: n22,
			})
		: (t32[e42] = n22);
var u = (t32, e42) =>
	function () {
		return (
			e42 ||
				(0, t32[i(t32)[0]])(
					(e42 = {
						exports: {},
					}).exports,
					e42,
				),
			e42.exports
		);
	};
var l = (t32, e42, s22, o22) => {
	if ((e42 && "object" == typeof e42) || "function" == typeof e42)
		for (let u22 of i(e42))
			a.call(t32, u22) ||
				u22 === s22 ||
				r(t32, u22, {
					get: () => e42[u22],
					enumerable: !(o22 = n(e42, u22)) || o22.enumerable,
				});
	return t32;
};
var h = (t32, n22, i22) => (
	(i22 = null != t32 ? e(s(t32)) : {}),
	l(
		// If the importer is in node compatibility mode or this is not an ESM
		// file that has been converted to a CommonJS file using a Babel-
		// compatible transform (i.e. "__esModule" has not been set), then set
		// "default" to the CommonJS "module.exports" for node compatibility.
		!n22 && t32 && t32.__esModule
			? i22
			: r(i22, "default", {
					value: t32,
					enumerable: true,
				}),
		t32,
	)
);
var c = (t32, e42, r22) => o(t32, "symbol" != typeof e42 ? e42 + "" : e42, r22);
var f = u({
	"../../../node_modules/dataloader/index.js"(t32, e42) {
		var r22,
			n22 = /* @__PURE__ */ (function () {
				function t42(t5, e6) {
					if ("function" != typeof t5)
						throw TypeError(
							"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but got: " +
								t5 +
								".",
						);
					(this._batchLoadFn = t5),
						(this._maxBatchSize = (function (t6) {
							if (!(!t6 || false !== t6.batch)) return 1;
							var e7 = t6 && t6.maxBatchSize;
							if (void 0 === e7) return 1 / 0;
							if ("number" != typeof e7 || e7 < 1)
								throw TypeError(
									"maxBatchSize must be a positive number: " + e7,
								);
							return e7;
						})(e6)),
						(this._batchScheduleFn = (function (t6) {
							var e7 = t6 && t6.batchScheduleFn;
							if (void 0 === e7) return i22;
							if ("function" != typeof e7)
								throw TypeError("batchScheduleFn must be a function: " + e7);
							return e7;
						})(e6)),
						(this._cacheKeyFn = (function (t6) {
							var e7 = t6 && t6.cacheKeyFn;
							if (void 0 === e7)
								return function (t7) {
									return t7;
								};
							if ("function" != typeof e7)
								throw TypeError("cacheKeyFn must be a function: " + e7);
							return e7;
						})(e6)),
						(this._cacheMap = (function (t6) {
							if (!(!t6 || false !== t6.cache)) return null;
							var e7 = t6 && t6.cacheMap;
							if (void 0 === e7) return /* @__PURE__ */ new Map();
							if (null !== e7) {
								var r32 = ["get", "set", "delete", "clear"].filter(
									function (t7) {
										return e7 && "function" != typeof e7[t7];
									},
								);
								if (0 !== r32.length)
									throw TypeError(
										"Custom cacheMap missing methods: " + r32.join(", "),
									);
							}
							return e7;
						})(e6)),
						(this._batch = null),
						(this.name = e6 && e6.name ? e6.name : null);
				}
				var e52 = t42.prototype;
				return (
					(e52.load = function (t5) {
						if (null == t5)
							throw TypeError(
								"The loader.load() function must be called with a value, but got: " +
									String(t5) +
									".",
							);
						var e6 = (function (t6) {
								var e7 = t6._batch;
								if (
									null !== e7 &&
									!e7.hasDispatched &&
									e7.keys.length < t6._maxBatchSize
								)
									return e7;
								var r4 = {
									hasDispatched: false,
									keys: [],
									callbacks: [],
								};
								return (
									(t6._batch = r4),
									t6._batchScheduleFn(function () {
										(function (t7, e8) {
											var r5;
											if (((e8.hasDispatched = true), 0 === e8.keys.length)) {
												a22(e8);
												return;
											}
											try {
												r5 = t7._batchLoadFn(e8.keys);
											} catch (r6) {
												return s22(
													t7,
													e8,
													TypeError(
														"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function errored synchronously: " +
															String(r6) +
															".",
													),
												);
											}
											if (!r5 || "function" != typeof r5.then)
												return s22(
													t7,
													e8,
													TypeError(
														"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise: " +
															String(r5) +
															".",
													),
												);
											r5.then(function (t8) {
												if (!o22(t8))
													throw TypeError(
														"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array: " +
															String(t8) +
															".",
													);
												if (t8.length !== e8.keys.length)
													throw TypeError(
														"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.\n\nKeys:\n" +
															String(e8.keys) +
															"\n\nValues:\n" +
															String(t8),
													);
												a22(e8);
												for (var r6 = 0; r6 < e8.callbacks.length; r6++) {
													var n4 = t8[r6];
													n4 instanceof Error
														? e8.callbacks[r6].reject(n4)
														: e8.callbacks[r6].resolve(n4);
												}
											}).catch(function (r6) {
												s22(t7, e8, r6);
											});
										})(t6, r4);
									}),
									r4
								);
							})(this),
							r32 = this._cacheMap,
							n3 = this._cacheKeyFn(t5);
						if (r32) {
							var i3 = r32.get(n3);
							if (i3) {
								var u22 = e6.cacheHits || (e6.cacheHits = []);
								return new Promise(function (t6) {
									u22.push(function () {
										t6(i3);
									});
								});
							}
						}
						e6.keys.push(t5);
						var l22 = new Promise(function (t6, r4) {
							e6.callbacks.push({
								resolve: t6,
								reject: r4,
							});
						});
						return r32 && r32.set(n3, l22), l22;
					}),
					(e52.loadMany = function (t5) {
						if (!o22(t5))
							throw TypeError(
								"The loader.loadMany() function must be called with Array<key> but got: " +
									t5 +
									".",
							);
						for (var e6 = [], r32 = 0; r32 < t5.length; r32++)
							e6.push(
								this.load(t5[r32]).catch(function (t6) {
									return t6;
								}),
							);
						return Promise.all(e6);
					}),
					(e52.clear = function (t5) {
						var e6 = this._cacheMap;
						if (e6) {
							var r32 = this._cacheKeyFn(t5);
							e6.delete(r32);
						}
						return this;
					}),
					(e52.clearAll = function () {
						var t5 = this._cacheMap;
						return t5 && t5.clear(), this;
					}),
					(e52.prime = function (t5, e6) {
						var r32 = this._cacheMap;
						if (r32) {
							var n3,
								i3 = this._cacheKeyFn(t5);
							void 0 === r32.get(i3) &&
								(e6 instanceof Error
									? (n3 = Promise.reject(e6)).catch(function () {})
									: (n3 = Promise.resolve(e6)),
								r32.set(i3, n3));
						}
						return this;
					}),
					t42
				);
			})(),
			i22 =
				"object" == typeof process && "function" == typeof process.nextTick
					? function (t42) {
							r22 || (r22 = Promise.resolve()),
								r22.then(function () {
									process.nextTick(t42);
								});
						}
					: "function" == typeof setImmediate
						? function (t42) {
								setImmediate(t42);
							}
						: function (t42) {
								setTimeout(t42);
							};
		function s22(t42, e52, r32) {
			a22(e52);
			for (var n3 = 0; n3 < e52.keys.length; n3++)
				t42.clear(e52.keys[n3]), e52.callbacks[n3].reject(r32);
		}
		function a22(t42) {
			if (t42.cacheHits)
				for (var e52 = 0; e52 < t42.cacheHits.length; e52++)
					t42.cacheHits[e52]();
		}
		function o22(t42) {
			return (
				"object" == typeof t42 &&
				null !== t42 &&
				"number" == typeof t42.length &&
				(0 === t42.length ||
					(t42.length > 0 &&
						Object.prototype.hasOwnProperty.call(t42, t42.length - 1)))
			);
		}
		e42.exports = n22;
	},
});
var d = h(f());
var g = {
	Uint8: 1,
	Uint16: 2,
	Uint32: 4,
	BigUint64: 8,
	Int8: 1,
	Int16: 2,
	Int32: 4,
	BigInt64: 8,
	Float32: 4,
	Float64: 8,
};
var y = class {
	getOffset() {
		return this.offset;
	}
	ensureLength(t32) {
		let e42 = this.bytes.length;
		if (!(this.offset + t32 <= e42)) throw Error("Reading out of bounds");
	}
	readUint8() {
		let t32 = g.Uint8;
		this.ensureLength(t32);
		let e42 = this.view.getUint8(this.offset);
		return (this.offset += t32), e42;
	}
	readUint16() {
		let t32 = g.Uint16;
		this.ensureLength(t32);
		let e42 = this.view.getUint16(this.offset);
		return (this.offset += t32), e42;
	}
	readUint32() {
		let t32 = g.Uint32;
		this.ensureLength(t32);
		let e42 = this.view.getUint32(this.offset);
		return (this.offset += t32), e42;
	}
	readUint64() {
		let t32 = this.readBigUint64();
		return Number(t32);
	}
	readBigUint64() {
		let t32 = g.BigUint64;
		this.ensureLength(t32);
		let e42 = this.view.getBigUint64(this.offset);
		return (this.offset += t32), e42;
	}
	readInt8() {
		let t32 = g.Int8;
		this.ensureLength(t32);
		let e42 = this.view.getInt8(this.offset);
		return (this.offset += t32), e42;
	}
	readInt16() {
		let t32 = g.Int16;
		this.ensureLength(t32);
		let e42 = this.view.getInt16(this.offset);
		return (this.offset += t32), e42;
	}
	readInt32() {
		let t32 = g.Int32;
		this.ensureLength(t32);
		let e42 = this.view.getInt32(this.offset);
		return (this.offset += t32), e42;
	}
	readInt64() {
		let t32 = this.readBigInt64();
		return Number(t32);
	}
	readBigInt64() {
		let t32 = g.BigInt64;
		this.ensureLength(t32);
		let e42 = this.view.getBigInt64(this.offset);
		return (this.offset += t32), e42;
	}
	readFloat32() {
		let t32 = g.Float32;
		this.ensureLength(t32);
		let e42 = this.view.getFloat32(this.offset);
		return (this.offset += t32), e42;
	}
	readFloat64() {
		let t32 = g.Float64;
		this.ensureLength(t32);
		let e42 = this.view.getFloat64(this.offset);
		return (this.offset += t32), e42;
	}
	readBytes(t32) {
		let e42 = this.offset,
			r22 = e42 + t32,
			n22 = this.bytes.subarray(e42, r22);
		return (this.offset = r22), n22;
	}
	readString() {
		let t32 = this.readUint32(),
			e42 = this.readBytes(t32);
		return this.decoder.decode(e42);
	}
	readJson() {
		let t32 = this.readString();
		return JSON.parse(t32);
	}
	constructor(t32) {
		(this.bytes = t32),
			c(this, "offset", 0),
			c(this, "view"),
			c(this, "decoder", new TextDecoder()),
			(this.view = p(this.bytes));
	}
};
function p(t32) {
	return new DataView(t32.buffer, t32.byteOffset, t32.byteLength);
}
var m = "undefined" != typeof window;
var w = m && "function" == typeof window.requestIdleCallback;
function I(t32, ...e42) {
	if (!t32)
		throw Error(
			"Assertion Error" + (e42.length > 0 ? ": " + e42.join(" ") : ""),
		);
}
function b(t32) {
	throw Error(`Unexpected value: ${t32}`);
}
var U = 1024;
var S = 1.5;
var k = (t32) => 2 ** t32 - 1;
var L = (t32) => -(2 ** (t32 - 1));
var B = (t32) => 2 ** (t32 - 1) - 1;
var E = {
	Uint8: 0,
	Uint16: 0,
	Uint32: 0,
	Uint64: 0,
	BigUint64: 0,
	Int8: L(8),
	Int16: L(16),
	Int32: L(32),
	Int64: Number.MIN_SAFE_INTEGER,
	BigInt64: -(BigInt(2) ** BigInt(63)),
};
var M = {
	Uint8: k(8),
	Uint16: k(16),
	Uint32: k(32),
	Uint64: Number.MAX_SAFE_INTEGER,
	BigUint64: BigInt(2) ** BigInt(64) - BigInt(1),
	Int8: B(8),
	Int16: B(16),
	Int32: B(32),
	Int64: Number.MAX_SAFE_INTEGER,
	BigInt64: BigInt(2) ** BigInt(63) - BigInt(1),
};
function T(t32, e42, r22, n22) {
	I(t32 >= e42, t32, "outside lower bound for", n22),
		I(t32 <= r22, t32, "outside upper bound for", n22);
}
var F = class {
	getOffset() {
		return this.offset;
	}
	slice(t32 = 0, e42 = this.offset) {
		return this.bytes.slice(t32, e42);
	}
	subarray(t32 = 0, e42 = this.offset) {
		return this.bytes.subarray(t32, e42);
	}
	ensureLength(t32) {
		let e42 = this.bytes.length;
		if (this.offset + t32 <= e42) return;
		let r22 = new Uint8Array(Math.ceil(e42 * S) + t32);
		r22.set(this.bytes), (this.bytes = r22), (this.view = p(r22));
	}
	writeUint8(t32) {
		T(t32, E.Uint8, M.Uint8, "Uint8");
		let e42 = g.Uint8;
		this.ensureLength(e42),
			this.view.setUint8(this.offset, t32),
			(this.offset += e42);
	}
	writeUint16(t32) {
		T(t32, E.Uint16, M.Uint16, "Uint16");
		let e42 = g.Uint16;
		this.ensureLength(e42),
			this.view.setUint16(this.offset, t32),
			(this.offset += e42);
	}
	writeUint32(t32) {
		T(t32, E.Uint32, M.Uint32, "Uint32");
		let e42 = g.Uint32;
		this.ensureLength(e42),
			this.view.setUint32(this.offset, t32),
			(this.offset += e42);
	}
	writeUint64(t32) {
		T(t32, E.Uint64, M.Uint64, "Uint64");
		let e42 = BigInt(t32);
		this.writeBigUint64(e42);
	}
	writeBigUint64(t32) {
		T(t32, E.BigUint64, M.BigUint64, "BigUint64");
		let e42 = g.BigUint64;
		this.ensureLength(e42),
			this.view.setBigUint64(this.offset, t32),
			(this.offset += e42);
	}
	writeInt8(t32) {
		T(t32, E.Int8, M.Int8, "Int8");
		let e42 = g.Int8;
		this.ensureLength(e42),
			this.view.setInt8(this.offset, t32),
			(this.offset += e42);
	}
	writeInt16(t32) {
		T(t32, E.Int16, M.Int16, "Int16");
		let e42 = g.Int16;
		this.ensureLength(e42),
			this.view.setInt16(this.offset, t32),
			(this.offset += e42);
	}
	writeInt32(t32) {
		T(t32, E.Int32, M.Int32, "Int32");
		let e42 = g.Int32;
		this.ensureLength(e42),
			this.view.setInt32(this.offset, t32),
			(this.offset += e42);
	}
	writeInt64(t32) {
		T(t32, E.Int64, M.Int64, "Int64");
		let e42 = BigInt(t32);
		this.writeBigInt64(e42);
	}
	writeBigInt64(t32) {
		T(t32, E.BigInt64, M.BigInt64, "BigInt64");
		let e42 = g.BigInt64;
		this.ensureLength(e42),
			this.view.setBigInt64(this.offset, t32),
			(this.offset += e42);
	}
	writeFloat32(t32) {
		let e42 = g.Float32;
		this.ensureLength(e42),
			this.view.setFloat32(this.offset, t32),
			(this.offset += e42);
	}
	writeFloat64(t32) {
		let e42 = g.Float64;
		this.ensureLength(e42),
			this.view.setFloat64(this.offset, t32),
			(this.offset += e42);
	}
	writeBytes(t32) {
		let e42 = t32.length;
		this.ensureLength(e42),
			this.bytes.set(t32, this.offset),
			(this.offset += e42);
	}
	encodeString(t32) {
		let e42 = this.encodedStrings.get(t32);
		if (e42) return e42;
		let r22 = this.encoder.encode(t32);
		return this.encodedStrings.set(t32, r22), r22;
	}
	writeString(t32) {
		let e42 = this.encodeString(t32),
			r22 = e42.length;
		this.writeUint32(r22), this.writeBytes(e42);
	}
	writeJson(t32) {
		let e42 = JSON.stringify(t32);
		this.writeString(e42);
	}
	constructor() {
		c(this, "offset", 0),
			c(this, "bytes", new Uint8Array(U)),
			c(this, "view", p(this.bytes)),
			c(this, "encoder", new TextEncoder()),
			c(this, "encodedStrings", /* @__PURE__ */ new Map());
	}
};
function x(t32) {
	return "string" == typeof t32;
}
function N(t32) {
	return Number.isFinite(t32);
}
function A(t32) {
	return null === t32;
}
var O = class t2 {
	static fromString(e42) {
		let [r22, n22, i22] = e42.split("/").map(Number);
		return (
			I(N(r22), "Invalid chunkId"),
			I(N(n22), "Invalid offset"),
			I(N(i22), "Invalid length"),
			new t2(r22, n22, i22)
		);
	}
	toString() {
		return `${this.chunkId}/${this.offset}/${this.length}`;
	}
	static read(e42) {
		let r22 = e42.readUint16(),
			n22 = e42.readUint32(),
			i22 = e42.readUint32();
		return new t2(r22, n22, i22);
	}
	write(t32) {
		t32.writeUint16(this.chunkId),
			t32.writeUint32(this.offset),
			t32.writeUint32(this.length);
	}
	compare(t32) {
		return this.chunkId < t32.chunkId
			? -1
			: this.chunkId > t32.chunkId
				? 1
				: this.offset < t32.offset
					? -1
					: this.offset > t32.offset
						? 1
						: (I(this.length === t32.length), 0);
	}
	constructor(t32, e42, r22) {
		(this.chunkId = t32), (this.offset = e42), (this.length = r22);
	}
};
function R(t32) {
	if (A(t32)) return 0;
	switch (t32.type) {
		case P.Array:
			return 1;
		case P.Boolean:
			return 2;
		case P.Color:
			return 3;
		case P.Date:
			return 4;
		case P.Enum:
			return 5;
		case P.File:
			return 6;
		case P.ResponsiveImage:
			return 10;
		case P.Link:
			return 7;
		case P.Number:
			return 8;
		case P.Object:
			return 9;
		case P.RichText:
			return 11;
		case P.String:
			return 12;
		case P.VectorSetItem:
			return 13;
		default:
			b(t32);
	}
}
function q(e42) {
	let r22 = e42.readUint16(),
		n22 = [];
	for (let i22 = 0; i22 < r22; i22++) {
		let r32 = t.read(e42);
		n22.push(r32);
	}
	return {
		type: P.Array,
		value: n22,
	};
}
function _(e42, r22) {
	for (let n22 of (e42.writeUint16(r22.value.length), r22.value))
		t.write(e42, n22);
}
function D(e42, r22, n22) {
	let i22 = e42.value.length,
		s22 = r22.value.length;
	if (i22 < s22) return -1;
	if (i22 > s22) return 1;
	for (let s32 = 0; s32 < i22; s32++) {
		let i3 = e42.value[s32],
			a22 = r22.value[s32],
			o22 = t.compare(i3, a22, n22);
		if (0 !== o22) return o22;
	}
	return 0;
}
function j(t32) {
	return {
		type: P.Boolean,
		value: 0 !== t32.readUint8(),
	};
}
function C(t32, e42) {
	t32.writeUint8(e42.value ? 1 : 0);
}
function J(t32, e42) {
	return t32.value < e42.value ? -1 : t32.value > e42.value ? 1 : 0;
}
function V(t32) {
	return {
		type: P.Color,
		value: t32.readString(),
	};
}
function W(t32, e42) {
	t32.writeString(e42.value);
}
function $(t32, e42) {
	return t32.value < e42.value ? -1 : t32.value > e42.value ? 1 : 0;
}
function z(t32) {
	let e42 = t32.readInt64(),
		r22 = new Date(e42);
	return {
		type: P.Date,
		value: r22.toISOString(),
	};
}
function G(t32, e42) {
	let r22 = new Date(e42.value),
		n22 = r22.getTime();
	t32.writeInt64(n22);
}
function K(t32, e42) {
	let r22 = new Date(t32.value),
		n22 = new Date(e42.value);
	return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
}
function H(t32) {
	return {
		type: P.Enum,
		value: t32.readString(),
	};
}
function X(t32, e42) {
	t32.writeString(e42.value);
}
function Q(t32, e42) {
	return t32.value < e42.value ? -1 : t32.value > e42.value ? 1 : 0;
}
function Y(t32) {
	return {
		type: P.File,
		value: t32.readString(),
	};
}
function Z(t32, e42) {
	t32.writeString(e42.value);
}
function tt(t32, e42) {
	return t32.value < e42.value ? -1 : t32.value > e42.value ? 1 : 0;
}
function te(t32) {
	return {
		type: P.Link,
		value: t32.readJson(),
	};
}
function tr(t32, e42) {
	t32.writeJson(e42.value);
}
function tn(t32, e42) {
	let r22 = JSON.stringify(t32.value),
		n22 = JSON.stringify(e42.value);
	return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
}
function ti(t32) {
	return {
		type: P.Number,
		value: t32.readFloat64(),
	};
}
function ts(t32, e42) {
	t32.writeFloat64(e42.value);
}
function ta(t32, e42) {
	return t32.value < e42.value ? -1 : t32.value > e42.value ? 1 : 0;
}
function to(e42) {
	let r22 = e42.readUint16(),
		n22 = {};
	for (let i22 = 0; i22 < r22; i22++) {
		let r32 = e42.readString();
		n22[r32] = t.read(e42);
	}
	return {
		type: P.Object,
		value: n22,
	};
}
function tu(e42, r22) {
	let n22 = Object.entries(r22.value);
	for (let [r32, i22] of (e42.writeUint16(n22.length), n22))
		e42.writeString(r32), t.write(e42, i22);
}
function tl(e42, r22, n22) {
	let i22 = Object.keys(e42.value).sort(),
		s22 = Object.keys(r22.value).sort();
	if (i22.length < s22.length) return -1;
	if (i22.length > s22.length) return 1;
	for (let a22 = 0; a22 < i22.length; a22++) {
		let o22 = i22[a22],
			u22 = s22[a22];
		if (o22 < u22) return -1;
		if (o22 > u22) return 1;
		let l22 = e42.value[o22] ?? null,
			h22 = r22.value[u22] ?? null,
			c22 = t.compare(l22, h22, n22);
		if (0 !== c22) return c22;
	}
	return 0;
}
function th(t32) {
	return {
		type: P.ResponsiveImage,
		value: t32.readJson(),
	};
}
function tc(t32, e42) {
	t32.writeJson(e42.value);
}
function tf(t32, e42) {
	let r22 = JSON.stringify(t32.value),
		n22 = JSON.stringify(e42.value);
	return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
}
function td(t32) {
	let e42 = t32.readInt8();
	if (0 === e42)
		return {
			type: P.RichText,
			value: t32.readUint32(),
		};
	if (1 === e42)
		return {
			type: P.RichText,
			value: t32.readString(),
		};
	throw Error("Invalid rich text pointer");
}
function tg(t32, e42) {
	if (N(e42.value)) {
		t32.writeInt8(0), t32.writeUint32(e42.value);
		return;
	}
	if (x(e42.value)) {
		t32.writeInt8(1), t32.writeString(e42.value);
		return;
	}
	throw Error("Invalid rich text pointer");
}
function ty(t32, e42) {
	let r22 = t32.value,
		n22 = e42.value;
	if ((N(r22) && N(n22)) || (x(r22) && x(n22)))
		return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
	throw Error("Invalid rich text pointer");
}
function tp(t32) {
	return {
		type: P.String,
		value: t32.readString(),
	};
}
function tv(t32, e42) {
	t32.writeString(e42.value);
}
function tm(t32, e42, r22) {
	let n22 = t32.value,
		i22 = e42.value;
	return (0 === r22.type &&
		((n22 = t32.value.toLowerCase()), (i22 = e42.value.toLowerCase())),
	n22 < i22)
		? -1
		: n22 > i22
			? 1
			: 0;
}
function tw(t32) {
	return {
		type: P.VectorSetItem,
		value: t32.readUint32(),
	};
}
function tI(t32, e42) {
	t32.writeUint32(e42.value);
}
function tb(t32, e42) {
	let r22 = t32.value,
		n22 = e42.value;
	return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
}
((t32) => {
	(t32.read = function (t42) {
		let e42 = t42.readUint8();
		switch (e42) {
			case 0:
				return null;
			case 1:
				return q(t42);
			case 2:
				return j(t42);
			case 3:
				return V(t42);
			case 4:
				return z(t42);
			case 5:
				return H(t42);
			case 6:
				return Y(t42);
			case 7:
				return te(t42);
			case 8:
				return ti(t42);
			case 9:
				return to(t42);
			case 10:
				return th(t42);
			case 11:
				return td(t42);
			case 12:
				return tp(t42);
			case 13:
				return tw(t42);
			default:
				b(e42);
		}
	}),
		(t32.write = function (t42, e42) {
			let r22 = R(e42);
			if ((t42.writeUint8(r22), !A(e42)))
				switch (e42.type) {
					case P.Array:
						return _(t42, e42);
					case P.Boolean:
						return C(t42, e42);
					case P.Color:
						return W(t42, e42);
					case P.Date:
						return G(t42, e42);
					case P.Enum:
						return X(t42, e42);
					case P.File:
						return Z(t42, e42);
					case P.Link:
						return tr(t42, e42);
					case P.Number:
						return ts(t42, e42);
					case P.Object:
						return tu(t42, e42);
					case P.ResponsiveImage:
						return tc(t42, e42);
					case P.RichText:
						return tg(t42, e42);
					case P.VectorSetItem:
						return tI(t42, e42);
					case P.String:
						return tv(t42, e42);
					default:
						b(e42);
				}
		}),
		(t32.compare = function (t42, e42, r22) {
			let n22 = R(t42),
				i22 = R(e42);
			if (n22 < i22) return -1;
			if (n22 > i22) return 1;
			if (A(t42) || A(e42)) return 0;
			switch (t42.type) {
				case P.Array:
					return I(e42.type === P.Array), D(t42, e42, r22);
				case P.Boolean:
					return I(e42.type === P.Boolean), J(t42, e42);
				case P.Color:
					return I(e42.type === P.Color), $(t42, e42);
				case P.Date:
					return I(e42.type === P.Date), K(t42, e42);
				case P.Enum:
					return I(e42.type === P.Enum), Q(t42, e42);
				case P.File:
					return I(e42.type === P.File), tt(t42, e42);
				case P.Link:
					return I(e42.type === P.Link), tn(t42, e42);
				case P.Number:
					return I(e42.type === P.Number), ta(t42, e42);
				case P.Object:
					return I(e42.type === P.Object), tl(t42, e42, r22);
				case P.ResponsiveImage:
					return I(e42.type === P.ResponsiveImage), tf(t42, e42);
				case P.RichText:
					return I(e42.type === P.RichText), ty(t42, e42);
				case P.VectorSetItem:
					return I(e42.type === P.VectorSetItem), tb(t42, e42);
				case P.String:
					return I(e42.type === P.String), tm(t42, e42, r22);
				default:
					b(t42);
			}
		});
})(t || (t = {}));
var tU = class e2 {
	sortEntries() {
		this.entries.sort((e42, r22) => {
			for (let n22 = 0; n22 < this.fieldNames.length; n22++) {
				let i22 = e42.values[n22],
					s22 = r22.values[n22],
					a22 = t.compare(i22, s22, this.options.collation);
				if (0 !== a22) return a22;
			}
			return e42.pointer.compare(r22.pointer);
		});
	}
	static deserialize(r22) {
		let n22 = new y(r22),
			i22 = n22.readJson(),
			s22 = n22.readUint8(),
			a22 = [];
		for (let t32 = 0; t32 < s22; t32++) {
			let t42 = n22.readString();
			a22.push(t42);
		}
		let o22 = new e2(a22, {
				collation: i22,
			}),
			u22 = n22.readUint32();
		for (let e42 = 0; e42 < u22; e42++) {
			let e52 = [];
			for (let r4 = 0; r4 < s22; r4++) {
				let r5 = t.read(n22);
				e52.push(r5);
			}
			let r32 = O.read(n22);
			o22.entries.push({
				values: e52,
				pointer: r32,
			});
		}
		return o22;
	}
	serialize() {
		let e42 = new F();
		for (let t32 of (e42.writeJson(this.options.collation),
		e42.writeUint8(this.fieldNames.length),
		this.fieldNames))
			e42.writeString(t32);
		for (let r22 of (this.sortEntries(),
		e42.writeUint32(this.entries.length),
		this.entries)) {
			let { values: n22, pointer: i22 } = r22;
			for (let r32 of n22) t.write(e42, r32);
			i22.write(e42);
		}
		return e42.subarray();
	}
	addItem(t32, e42) {
		let r22 = this.fieldNames.map((e52) => t32.getField(e52) ?? null);
		this.entries.push({
			values: r22,
			pointer: e42,
		});
	}
	constructor(t32, e42) {
		(this.fieldNames = t32), (this.options = e42), c(this, "entries", []);
	}
};
var tS = 3;
var tk = 250;
var tL = [
	408,
	// Request Timeout
	429,
	// Too Many Requests
	500,
	// Internal Server Error
	502,
	// Bad Gateway
	503,
	// Service Unavailable
	504,
];
var tB = async (t32, e42) => {
	let r22 = 0;
	for (;;) {
		try {
			let n22 = await fetch(t32, e42);
			if (!tL.includes(n22.status) || ++r22 > tS) return n22;
		} catch (t42) {
			if (e42?.signal?.aborted || ++r22 > tS) throw t42;
		}
		await tE(r22);
	}
};
async function tE(t32) {
	let e42 = Math.floor(tk * (Math.random() + 1) * 2 ** (t32 - 1));
	await new Promise((t42) => {
		setTimeout(t42, e42);
	});
}
async function tM(t32, e42) {
	let r22 = tx(e42),
		n22 = [],
		i22 = 0;
	for (let t42 of r22)
		n22.push(`${t42.from}-${t42.to - 1}`), (i22 += t42.to - t42.from);
	let s22 = new URL(t32),
		a22 = n22.join(",");
	s22.searchParams.set("range", a22);
	let o22 = await tB(s22);
	if (200 !== o22.status)
		throw Error(`Request failed: ${o22.status} ${o22.statusText}`);
	let u22 = await o22.arrayBuffer(),
		l22 = new Uint8Array(u22);
	if (l22.length !== i22)
		throw Error("Request failed: Unexpected response length");
	let h22 = new tT(),
		c22 = 0;
	for (let t42 of r22) {
		let e52 = t42.to - t42.from,
			r32 = c22 + e52,
			n3 = l22.subarray(c22, r32);
		h22.write(t42.from, n3), (c22 = r32);
	}
	return e42.map((t42) => h22.read(t42.from, t42.to - t42.from));
}
var tT = class {
	read(t32, e42) {
		for (let r22 of this.chunks) {
			if (t32 < r22.start) break;
			if (t32 > r22.end) continue;
			if (t32 + e42 > r22.end) break;
			let n22 = t32 - r22.start,
				i22 = n22 + e42;
			return r22.data.slice(n22, i22);
		}
		throw Error("Missing data");
	}
	write(t32, e42) {
		let r22 = t32,
			n22 = r22 + e42.length,
			i22 = 0,
			s22 = this.chunks.length;
		for (; i22 < s22; i22++) {
			let t42 = this.chunks[i22];
			if ((I(t42, "Missing chunk"), !(r22 > t42.end))) {
				if (r22 > t42.start) {
					let n3 = r22 - t42.start,
						i3 = t42.data.subarray(0, n3);
					(e42 = tF(i3, e42)), (r22 = t42.start);
				}
				break;
			}
		}
		for (; s22 > i22; s22--) {
			let t42 = this.chunks[s22 - 1];
			if ((I(t42, "Missing chunk"), !(n22 < t42.start))) {
				if (n22 < t42.end) {
					let r32 = n22 - t42.start,
						i3 = t42.data.subarray(r32);
					(e42 = tF(e42, i3)), (n22 = t42.end);
				}
				break;
			}
		}
		let a22 = {
				start: r22,
				end: n22,
				data: e42,
			},
			o22 = s22 - i22;
		this.chunks.splice(i22, o22, a22);
	}
	constructor() {
		c(this, "chunks", []);
	}
};
function tF(t32, e42) {
	let r22 = t32.length + e42.length,
		n22 = new Uint8Array(r22);
	return n22.set(t32, 0), n22.set(e42, t32.length), n22;
}
function tx(t32) {
	I(t32.length > 0, "Must have at least one range");
	let e42 = [...t32].sort((t42, e52) => t42.from - e52.from),
		r22 = [];
	for (let t42 of e42) {
		let e52 = r22.length - 1,
			n22 = r22[e52];
		n22 && t42.from <= n22.to
			? (r22[e52] = {
					from: n22.from,
					to: Math.max(n22.to, t42.to),
				})
			: r22.push(t42);
	}
	return r22;
}
var tN = class {
	async loadModel() {
		let [t32] = await tM(this.options.url, [this.options.range]);
		return I(t32, "Failed to load model"), tU.deserialize(t32);
	}
	async getModel() {
		return (
			(this.modelPromise ??= this.loadModel()),
			(this.model ??= await this.modelPromise),
			this.model
		);
	}
	async lookupItems(t32) {
		I(t32.length === this.fields.length, "Invalid query length");
		let e42 = await this.getModel(),
			r22 = t32.reduce(
				(t42, e52, r32) =>
					t42.flatMap((t5) => {
						switch (e52.type) {
							case "All":
								return [t5];
							case "Equals":
								return this.queryEquals(t5, e52, r32);
							case "NotEquals":
								return this.queryNotEquals(t5, e52, r32);
							case "LessThan":
								return this.queryLessThan(t5, e52, r32);
							case "GreaterThan":
								return this.queryGreaterThan(t5, e52, r32);
							case "Contains":
								return this.queryContains(t5, e52, r32);
							case "StartsWith":
								return this.queryStartsWith(t5, e52, r32);
							case "EndsWith":
								return this.queryEndsWith(t5, e52, r32);
							default:
								b(e52);
						}
					}),
				[e42.entries],
			),
			n22 = [];
		for (let t42 of r22)
			for (let e52 of t42) {
				let t5 = {};
				for (let r32 = 0; r32 < this.options.fieldNames.length; r32++) {
					let n3 = this.options.fieldNames[r32],
						i22 = e52.values[r32];
					t5[n3] = i22;
				}
				n22.push({
					pointer: e52.pointer.toString(),
					data: t5,
				});
			}
		return n22;
	}
	queryEquals(t32, e42, r22) {
		let n22 = this.getLeftMost(t32, r22, e42.value),
			i22 = this.getRightMost(t32, r22, e42.value),
			s22 = t32.slice(n22, i22 + 1);
		return s22.length > 0 ? [s22] : [];
	}
	queryNotEquals(t32, e42, r22) {
		let n22 = this.getLeftMost(t32, r22, e42.value),
			i22 = this.getRightMost(t32, r22, e42.value),
			s22 = [],
			a22 = t32.slice(0, n22);
		a22.length > 0 && s22.push(a22);
		let o22 = t32.slice(i22 + 1);
		return o22.length > 0 && s22.push(o22), s22;
	}
	queryLessThan(t32, e42, r22) {
		let n22 = this.getRightMost(t32, r22, null);
		if (((t32 = t32.slice(n22 + 1)), e42.inclusive)) {
			let n3 = this.getRightMost(t32, r22, e42.value),
				i3 = t32.slice(0, n3 + 1);
			return i3.length > 0 ? [i3] : [];
		}
		let i22 = this.getLeftMost(t32, r22, e42.value),
			s22 = t32.slice(0, i22);
		return s22.length > 0 ? [s22] : [];
	}
	queryGreaterThan(t32, e42, r22) {
		let n22 = this.getRightMost(t32, r22, null);
		if (((t32 = t32.slice(n22 + 1)), e42.inclusive)) {
			let n3 = this.getLeftMost(t32, r22, e42.value),
				i3 = t32.slice(n3);
			return i3.length > 0 ? [i3] : [];
		}
		let i22 = this.getRightMost(t32, r22, e42.value),
			s22 = t32.slice(i22 + 1);
		return s22.length > 0 ? [s22] : [];
	}
	queryContains(t32, e42, r22) {
		return this.findItems(t32, r22, (t42) => {
			if (t42?.type !== v.String || e42.value?.type !== v.String) return false;
			let r32 = t42.value,
				n22 = e42.value.value;
			return (
				0 === this.collation.type &&
					((r32 = r32.toLowerCase()), (n22 = n22.toLowerCase())),
				r32.includes(n22)
			);
		});
	}
	queryStartsWith(t32, e42, r22) {
		return this.findItems(t32, r22, (t42) => {
			if (t42?.type !== v.String || e42.value?.type !== v.String) return false;
			let r32 = t42.value,
				n22 = e42.value.value;
			return (
				0 === this.collation.type &&
					((r32 = r32.toLowerCase()), (n22 = n22.toLowerCase())),
				r32.startsWith(n22)
			);
		});
	}
	queryEndsWith(t32, e42, r22) {
		return this.findItems(t32, r22, (t42) => {
			if (t42?.type !== v.String || e42.value?.type !== v.String) return false;
			let r32 = t42.value,
				n22 = e42.value.value;
			return (
				0 === this.collation.type &&
					((r32 = r32.toLowerCase()), (n22 = n22.toLowerCase())),
				r32.endsWith(n22)
			);
		});
	}
	/**
	 * Returns the index of the left most entry that is equal to the target.
	 *
	 * ```text
	 *   Left most
	 *       ↓
	 * ┌───┬───┬───┬───┬───┬───┐
	 * │ 1 │ 2 │ 2 │ 2 │ 2 │ 3 │
	 * └───┴───┴───┴───┴───┴───┘
	 * ```
	 *
	 * @param entries The entries array to search in.
	 * @param position The position of the value in the entry.
	 * @param target The target value to search for.
	 * @returns The index of the left most entry that is equal to the target.
	 */
	getLeftMost(e42, r22, n22) {
		let i22 = 0,
			s22 = e42.length;
		for (; i22 < s22; ) {
			let a22 = (i22 + s22) >> 1,
				o22 = e42[a22],
				u22 = o22.values[r22];
			0 > t.compare(u22, n22, this.collation) ? (i22 = a22 + 1) : (s22 = a22);
		}
		return i22;
	}
	/**
	 * Returns the index of the right most entry that is equal to the target.
	 *
	 * ```text
	 *              Right most
	 *                   ↓
	 * ┌───┬───┬───┬───┬───┬───┐
	 * │ 1 │ 2 │ 2 │ 2 │ 2 │ 3 │
	 * └───┴───┴───┴───┴───┴───┘
	 * ```
	 *
	 * @param entries The entries array to search in.
	 * @param position The position of the value in the entry.
	 * @param target The target value to search for.
	 * @returns The index of the right most entry that is equal to the target.
	 */
	getRightMost(e42, r22, n22) {
		let i22 = 0,
			s22 = e42.length;
		for (; i22 < s22; ) {
			let a22 = (i22 + s22) >> 1,
				o22 = e42[a22],
				u22 = o22.values[r22];
			t.compare(u22, n22, this.collation) > 0 ? (s22 = a22) : (i22 = a22 + 1);
		}
		return s22 - 1;
	}
	/**
	 * Finds all items that are matching the predicate and groups adjacent items together.
	 *
	 * @param entries The entries array to search in.
	 * @param position The position of the value in the entry.
	 * @param predicate The predicate to match the values against.
	 * @returns An array of chunks that match the predicate.
	 */
	findItems(t32, e42, r22) {
		let n22 = [],
			i22 = 0;
		for (let s22 = 0; s22 < t32.length; s22++) {
			let a22 = t32[s22],
				o22 = a22.values[e42],
				u22 = r22(o22);
			if (!u22) {
				if (i22 < s22) {
					let e52 = t32.slice(i22, s22);
					n22.push(e52);
				}
				i22 = s22 + 1;
			}
		}
		if (i22 < t32.length) {
			let e52 = t32.slice(i22);
			n22.push(e52);
		}
		return n22;
	}
	constructor(t32) {
		(this.options = t32),
			c(this, "schema"),
			c(this, "fields"),
			c(this, "supportedLookupTypes", [
				"All",
				"Equals",
				"NotEquals",
				"LessThan",
				"GreaterThan",
				"Contains",
				"StartsWith",
				"EndsWith",
				/* EndsWith */
			]),
			c(this, "modelPromise"),
			c(this, "model"),
			c(this, "collation");
		let e42 = {},
			r22 = [];
		for (let t42 of this.options.fieldNames) {
			let n22 = this.options.collectionSchema[t42];
			I(n22, "Missing definition for field", t42),
				(e42[t42] = n22),
				r22.push({
					type: "Identifier",
					name: t42,
				});
		}
		(this.schema = e42),
			(this.fields = r22),
			(this.collation = this.options.collation);
	}
};
var tA = class e3 {
	static read(r22) {
		let n22 = new e3(),
			i22 = r22.readUint16();
		for (let e42 = 0; e42 < i22; e42++) {
			let e52 = r22.readString(),
				i3 = t.read(r22);
			n22.setField(e52, i3);
		}
		return n22;
	}
	write(e42) {
		for (let [r22, n22] of (e42.writeUint16(this.fields.size), this.fields))
			e42.writeString(r22), t.write(e42, n22);
	}
	getData() {
		let t32 = {};
		for (let [e42, r22] of this.fields) t32[e42] = r22;
		return t32;
	}
	setField(t32, e42) {
		this.fields.set(t32, e42);
	}
	getField(t32) {
		return this.fields.get(t32);
	}
	constructor() {
		c(this, "fields", /* @__PURE__ */ new Map());
	}
};
var tO = class {
	scanItems() {
		return (
			(this.itemsPromise ??= tB(this.url).then(async (t32) => {
				if (!t32.ok)
					throw Error(`Request failed: ${t32.status} ${t32.statusText}`);
				let e42 = await t32.arrayBuffer(),
					r22 = new Uint8Array(e42),
					n22 = new y(r22),
					i22 = [],
					s22 = n22.readUint32();
				for (let t42 = 0; t42 < s22; t42++) {
					let t5 = n22.getOffset(),
						e52 = tA.read(n22),
						r32 = n22.getOffset() - t5,
						s32 = new O(this.id, t5, r32),
						a22 = s32.toString(),
						o22 = {
							pointer: a22,
							data: e52.getData(),
						};
					this.itemLoader.prime(a22, o22), i22.push(o22);
				}
				return i22;
			})),
			this.itemsPromise
		);
	}
	resolveItem(t32) {
		return this.itemLoader.load(t32);
	}
	constructor(t32, e42) {
		(this.id = t32),
			(this.url = e42),
			c(this, "itemsPromise"),
			c(
				this,
				"itemLoader",
				new d.default(async (t42) => {
					let e52 = t42.map((t5) => {
							let e6 = O.fromString(t5);
							return {
								from: e6.offset,
								to: e6.offset + e6.length,
							};
						}),
						r22 = await tM(this.url, e52);
					return r22.map((e6, r32) => {
						let n22 = new y(e6),
							i22 = tA.read(n22),
							s22 = t42[r32];
						return (
							I(s22, "Missing pointer"),
							{
								pointer: s22,
								data: i22.getData(),
							}
						);
					});
				}),
			);
	}
};
var tP = class {
	async scanItems() {
		let t32 = await Promise.all(
			this.chunks.map(async (t42) => t42.scanItems()),
		);
		return t32.flat();
	}
	async resolveItems(t32) {
		return Promise.all(
			t32.map((t42) => {
				let e42 = O.fromString(t42),
					r22 = this.chunks[e42.chunkId];
				return I(r22, "Missing chunk"), r22.resolveItem(t42);
			}),
		);
	}
	compareItems(t32, e42) {
		let r22 = O.fromString(t32.pointer),
			n22 = O.fromString(e42.pointer);
		return r22.compare(n22);
	}
	compareValues(e42, r22, n22) {
		return t.compare(e42, r22, n22);
	}
	constructor(t32) {
		(this.options = t32),
			c(this, "schema"),
			c(this, "indexes"),
			c(this, "resolveRichText"),
			c(this, "resolveVectorSetItem"),
			c(this, "chunks"),
			(this.chunks = this.options.chunks.map((t42, e42) => new tO(e42, t42))),
			(this.schema = t32.schema),
			(this.indexes = t32.indexes),
			(this.resolveRichText = t32.resolveRichText),
			(this.resolveVectorSetItem = t32.resolveVectorSetItem);
	}
};

// /:https://framerusercontent.com/modules/DPbNkOyYiRfvtcJMi2U2/3qef2jFiriY5WmUMLFtL/wl_dkBnh5-1.js
import { jsx as e4 } from "react/jsx-runtime";
import {
	ComponentPresetsConsumer as r2,
	Link as t3,
	motion as n2,
} from "unframer";
import { isValidElement as o2 } from "react";
import { Fragment as c2, createElement as l2 } from "react";
var a2;
var i2 = "preload";
function u2(e22) {
	return (
		"object" == typeof e22 &&
		null !== e22 &&
		!(/* @__PURE__ */ o2(e22)) &&
		i2 in e22
	);
}
function m2(e22, ...r22) {
	if (!e22)
		throw Error(
			"Assertion Error" + (r22.length > 0 ? ": " + r22.join(" ") : ""),
		);
}
var s2 =
	(((a2 = s2 || {})[(a2.Fragment = 1)] = "Fragment"),
	(a2[(a2.Link = 2)] = "Link"),
	(a2[(a2.Module = 3)] = "Module"),
	(a2[(a2.Tag = 4)] = "Tag"),
	(a2[(a2.Text = 5)] = "Text"),
	a2);
function f2(o22) {
	let a22 = /* @__PURE__ */ new Map();
	return (i22) => {
		let s22 = a22.get(i22);
		if (s22) return s22;
		let f22 = JSON.parse(i22),
			p3 = (function a3(i3) {
				switch (i3[0]) {
					case 1: {
						let [, ...e22] = i3,
							r22 = e22.map(a3);
						return l2(c2, void 0, ...r22);
					}
					case 2: {
						let [, e22, ...r22] = i3,
							n22 = r22.map(a3);
						return l2(t3, e22, ...n22);
					}
					case 3: {
						let [, t22, n22] = i3,
							a4 = o22[t22];
						return (
							m2(a4, "Module not found"),
							u2(a4) && a4.preload(),
							e4(r2, {
								componentIdentifier: t22,
								children: (r22) =>
									e4(a4, {
										...r22,
										...n22,
									}),
							})
						);
					}
					case 4: {
						let [, e22, r22, ...t22] = i3,
							o32 = t22.map(a3);
						if ("a" === e22) return <n2.a />;
						return l2(e22, r22, ...o32);
					}
					case 5: {
						let [, e22] = i3;
						return e22;
					}
				}
			})(f22);
		return a22.set(i22, p3), p3;
	};
}

// /:https://framerusercontent.com/modules/DPbNkOyYiRfvtcJMi2U2/3qef2jFiriY5WmUMLFtL/wl_dkBnh5.js
var m3 = {
	b5Re5U5zy: {
		isNullable: true,
		type: l3.String,
	},
	chxBwxKwb: {
		isNullable: true,
		type: l3.String,
	},
	createdAt: {
		isNullable: true,
		type: l3.Date,
	},
	id: {
		isNullable: false,
		type: l3.String,
	},
	j5QY6LesN: {
		isNullable: true,
		type: l3.String,
	},
	JPC2lXnyU: {
		isNullable: true,
		type: l3.RichText,
	},
	nextItemId: {
		isNullable: true,
		type: l3.String,
	},
	nJmEl3Kht: {
		isNullable: true,
		type: l3.String,
	},
	Nv5nBwGix: {
		isNullable: true,
		type: l3.String,
	},
	previousItemId: {
		isNullable: true,
		type: l3.String,
	},
	uMH75oH07: {
		isNullable: true,
		type: l3.ResponsiveImage,
	},
	updatedAt: {
		isNullable: true,
		type: l3.Date,
	},
	xnF_MDm4Z: {
		isNullable: true,
		type: l3.String,
	},
};
var o3 = ["id"];
var c3 = {
	type: 1,
};
var d2 = ["previousItemId"];
var u3 = ["nextItemId"];
var s3 = ["id", "chxBwxKwb"];
var f3 = ["chxBwxKwb", "id"];
var p2 = ["xnF_MDm4Z"];
var w2 = {
	type: 0,
};
var h2 = ["chxBwxKwb"];
var y2 = ["j5QY6LesN"];
var x2 = ["uMH75oH07"];
var g2 = ["b5Re5U5zy"];
var B2 = ["nJmEl3Kht"];
var N2 = ["Nv5nBwGix"];
var S2 = ["JPC2lXnyU"];
var I2 = [];
var R2 = (e22) => {
	let l22 = I2[e22];
	if (l22) return l22().then((e32) => e32.default);
};
var b2 = {};
var L2 = f2(b2);
var U2 = new r3();
var _2 = new t4(U2);
var k2 = {
	collectionByLocaleId: {
		default: new tP({
			chunks: [
				new URL(
					"./wl_dkBnh5-chunk-default-0.framercms",
					"https://framerusercontent.com/modules/DPbNkOyYiRfvtcJMi2U2/3qef2jFiriY5WmUMLFtL/wl_dkBnh5.js",
				).href.replace("/modules/", "/cms/"),
			],
			indexes: [
				new tN({
					collation: c3,
					collectionSchema: m3,
					fieldNames: o3,
					range: {
						from: 0,
						to: 217,
					},
					url: new URL(
						"./wl_dkBnh5-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/DPbNkOyYiRfvtcJMi2U2/3qef2jFiriY5WmUMLFtL/wl_dkBnh5.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: c3,
					collectionSchema: m3,
					fieldNames: d2,
					range: {
						from: 217,
						to: 433,
					},
					url: new URL(
						"./wl_dkBnh5-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/DPbNkOyYiRfvtcJMi2U2/3qef2jFiriY5WmUMLFtL/wl_dkBnh5.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: c3,
					collectionSchema: m3,
					fieldNames: u3,
					range: {
						from: 433,
						to: 645,
					},
					url: new URL(
						"./wl_dkBnh5-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/DPbNkOyYiRfvtcJMi2U2/3qef2jFiriY5WmUMLFtL/wl_dkBnh5.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: c3,
					collectionSchema: m3,
					fieldNames: s3,
					range: {
						from: 645,
						to: 1285,
					},
					url: new URL(
						"./wl_dkBnh5-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/DPbNkOyYiRfvtcJMi2U2/3qef2jFiriY5WmUMLFtL/wl_dkBnh5.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: c3,
					collectionSchema: m3,
					fieldNames: f3,
					range: {
						from: 1285,
						to: 1925,
					},
					url: new URL(
						"./wl_dkBnh5-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/DPbNkOyYiRfvtcJMi2U2/3qef2jFiriY5WmUMLFtL/wl_dkBnh5.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: w2,
					collectionSchema: m3,
					fieldNames: p2,
					range: {
						from: 1925,
						to: 2452,
					},
					url: new URL(
						"./wl_dkBnh5-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/DPbNkOyYiRfvtcJMi2U2/3qef2jFiriY5WmUMLFtL/wl_dkBnh5.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: w2,
					collectionSchema: m3,
					fieldNames: h2,
					range: {
						from: 2452,
						to: 2974,
					},
					url: new URL(
						"./wl_dkBnh5-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/DPbNkOyYiRfvtcJMi2U2/3qef2jFiriY5WmUMLFtL/wl_dkBnh5.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: w2,
					collectionSchema: m3,
					fieldNames: y2,
					range: {
						from: 2974,
						to: 3206,
					},
					url: new URL(
						"./wl_dkBnh5-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/DPbNkOyYiRfvtcJMi2U2/3qef2jFiriY5WmUMLFtL/wl_dkBnh5.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: w2,
					collectionSchema: m3,
					fieldNames: x2,
					range: {
						from: 3206,
						to: 7746,
					},
					url: new URL(
						"./wl_dkBnh5-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/DPbNkOyYiRfvtcJMi2U2/3qef2jFiriY5WmUMLFtL/wl_dkBnh5.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: w2,
					collectionSchema: m3,
					fieldNames: g2,
					range: {
						from: 7746,
						to: 8436,
					},
					url: new URL(
						"./wl_dkBnh5-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/DPbNkOyYiRfvtcJMi2U2/3qef2jFiriY5WmUMLFtL/wl_dkBnh5.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: w2,
					collectionSchema: m3,
					fieldNames: B2,
					range: {
						from: 8436,
						to: 8642,
					},
					url: new URL(
						"./wl_dkBnh5-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/DPbNkOyYiRfvtcJMi2U2/3qef2jFiriY5WmUMLFtL/wl_dkBnh5.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: w2,
					collectionSchema: m3,
					fieldNames: N2,
					range: {
						from: 8642,
						to: 8897,
					},
					url: new URL(
						"./wl_dkBnh5-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/DPbNkOyYiRfvtcJMi2U2/3qef2jFiriY5WmUMLFtL/wl_dkBnh5.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: w2,
					collectionSchema: m3,
					fieldNames: S2,
					range: {
						from: 8897,
						to: 32163,
					},
					url: new URL(
						"./wl_dkBnh5-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/DPbNkOyYiRfvtcJMi2U2/3qef2jFiriY5WmUMLFtL/wl_dkBnh5.js",
					).href.replace("/modules/", "/cms/"),
				}),
			],
			resolveRichText: L2,
			resolveVectorSetItem: R2,
			schema: m3,
		}),
	},
	displayName: "Newsroom",
};
var stdin_default = k2;
e5(k2, {
	xnF_MDm4Z: {
		defaultValue: "",
		title: "Title",
		type: l3.String,
	},
	chxBwxKwb: {
		title: "Slug",
		type: l3.String,
	},
	j5QY6LesN: {
		defaultValue: "",
		title: "Date",
		type: l3.String,
	},
	uMH75oH07: {
		title: "Image",
		type: l3.ResponsiveImage,
	},
	b5Re5U5zy: {
		defaultValue: "",
		title: "Intro",
		type: l3.String,
	},
	nJmEl3Kht: {
		defaultValue: "",
		title: "Blog Type",
		type: l3.String,
	},
	Nv5nBwGix: {
		defaultValue: "",
		title: "Author",
		type: l3.String,
	},
	JPC2lXnyU: {
		defaultValue: "",
		title: "Content",
		type: l3.RichText,
	},
	createdAt: {
		title: "Created",
		type: l3.Date,
	},
	updatedAt: {
		title: "Updated",
		type: l3.Date,
	},
	previousItemId: {
		dataIdentifier: "local-module:collection/wl_dkBnh5:default",
		title: "Previous",
		type: l3.CollectionReference,
	},
	nextItemId: {
		dataIdentifier: "local-module:collection/wl_dkBnh5:default",
		title: "Next",
		type: l3.CollectionReference,
	},
});

// /:https://framerusercontent.com/modules/lFqh1wzqpY6Birdpdazf/UZAo0e4Xec3MQclXOd7x/EpVFhcy8b.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	uToUMNg3y: {
		hover: true,
	},
};
var cycleOrder = ["uToUMNg3y", "fKoc4jxqS"];
var serializationHash = "framer-NpiRD";
var variantClassNames = {
	fKoc4jxqS: "framer-v-w8kkpg",
	uToUMNg3y: "framer-v-tgtc04",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.4,
	ease: [0.09, 0.55, 0.35, 1],
	type: "tween",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "uToUMNg3y",
	Mobile: "fKoc4jxqS",
};
var getProps = ({
	date,
	height,
	id,
	image,
	label,
	link,
	text,
	width,
	...props
}) => {
	return {
		...props,
		DoELK3oP8:
			text ?? props.DoELK3oP8 ?? "Lorem Ipsum News Blog Lorem Ipsum News Blog",
		eW_riBZ21: label ?? props.eW_riBZ21 ?? "Guides",
		HJorRaZNl: image ??
			props.HJorRaZNl ?? {
				alt: "",
				pixelHeight: 4032,
				pixelWidth: 3024,
				src: "https://framerusercontent.com/images/cVI3IOmIcZKEGZ8a45nbHrH0GM.jpg?scale-down-to=512&width=3024&height=4032",
				srcSet:
					"https://framerusercontent.com/images/cVI3IOmIcZKEGZ8a45nbHrH0GM.jpg?scale-down-to=1024&width=3024&height=4032 768w,https://framerusercontent.com/images/cVI3IOmIcZKEGZ8a45nbHrH0GM.jpg?scale-down-to=2048&width=3024&height=4032 1536w,https://framerusercontent.com/images/cVI3IOmIcZKEGZ8a45nbHrH0GM.jpg?width=3024&height=4032 3024w",
			},
		KbXUsFj2Y: date ?? props.KbXUsFj2Y ?? "10.01.25",
		txGDSPAmo: link ?? props.txGDSPAmo,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "uToUMNg3y",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		HJorRaZNl,
		DoELK3oP8,
		KbXUsFj2Y,
		txGDSPAmo,
		eW_riBZ21,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "uToUMNg3y",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className3, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={txGDSPAmo}
						motionChild={true}
						nodeId={"uToUMNg3y"}
						openInNewTab={false}
						scopeId={"EpVFhcy8b"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-tgtc04", className4, classNames)} framer-1u0nlsb`}
							data-framer-name={"Desktop"}
							layoutDependency={layoutDependency}
							layoutId={"uToUMNg3y"}
							ref={refBinding}
							style={{
								"--border-bottom-width": "0px",
								"--border-color": "rgba(0, 0, 0, 0)",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "solid",
								"--border-top-width": "0px",
								backgroundColor:
									"var(--token-0cdad307-f7d4-4932-883c-e1621a2e3092, rgb(18, 18, 18))",
								borderBottomLeftRadius: 8,
								borderBottomRightRadius: 8,
								borderTopLeftRadius: 8,
								borderTopRightRadius: 8,
								...style,
							}}
							variants={{
								"uToUMNg3y-hover": {
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-2af2796e-c98f-415f-bfdd-4cf975fb4b80, rgb(51, 51, 51))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
								},
							}}
							{...addPropertyOverrides(
								{
									"uToUMNg3y-hover": {
										"data-border": true,
										"data-framer-name": void 0,
									},
									fKoc4jxqS: {
										"data-framer-name": "Mobile",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-1531i8v"}
								data-framer-name={"Image Wrap"}
								layoutDependency={layoutDependency}
								layoutId={"iAPoRhg5D"}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) + 0 + 0 + 0,
										),
										pixelHeight: 4032,
										pixelWidth: 3024,
										sizes: componentViewport?.width || "100vw",
										...toResponsiveImage(HJorRaZNl),
									}}
									className={"framer-1msk8qg"}
									layoutDependency={layoutDependency}
									layoutId={"ydyrXrtKk"}
									style={{
										filter: "none",
										scale: 1,
										WebkitFilter: "none",
									}}
									variants={{
										"uToUMNg3y-hover": {
											filter: "brightness(0.6) blur(4px)",
											scale: 1.1,
											WebkitFilter: "brightness(0.6) blur(4px)",
										},
									}}
								/>
								<motion.div
									className={"framer-1vp4ps8"}
									data-border={true}
									data-framer-name={"Label"}
									layoutDependency={layoutDependency}
									layoutId={"hNLSYgV_t"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color": "rgba(255, 255, 255, 0.1)",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										backdropFilter: "blur(4px)",
										backgroundColor: "rgba(48, 48, 48, 0.3)",
										borderBottomLeftRadius: 4,
										borderBottomRightRadius: 4,
										borderTopLeftRadius: 4,
										borderTopRightRadius: 4,
										WebkitBackdropFilter: "blur(4px)",
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1vlwmjg"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"k0dGxWSp7"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={eW_riBZ21}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-g8iro9"}
												data-styles-preset={"Ck1ubvtuS"}
											>
												{"Guides"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-yqemug"}
								data-framer-name={"Wrap"}
								layoutDependency={layoutDependency}
								layoutId={"rsqiplahM"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1bdyqux"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"n3O7n9Wna"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={KbXUsFj2Y}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-labdxo"}
											data-styles-preset={"CRmxFdPaP"}
										>
											{"10.01.25"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-uqn93y"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"UssjD3c_H"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={DoELK3oP8}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h5
											className={"framer-styles-preset-v2uh97"}
											data-styles-preset={"hgRR2OlAI"}
											style={{
												"--framer-text-alignment": "left",
											}}
										>
											{"Lorem Ipsum News Blog Lorem Ipsum News Blog"}
										</motion.h5>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-1pmg8jf"}
								data-border={true}
								data-framer-name={"Button Wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"sG08zD3To"}
								style={{
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-af1ab411-d3d7-4fef-86fb-cdfbfe2b260b, rgb(224, 224, 224))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									borderBottomLeftRadius: "100%",
									borderBottomRightRadius: "100%",
									borderTopLeftRadius: "100%",
									borderTopRightRadius: "100%",
									opacity: 0,
									rotate: 0,
								}}
								variants={{
									"uToUMNg3y-hover": {
										opacity: 1,
										rotate: -45,
									},
									fKoc4jxqS: {
										opacity: 1,
										rotate: -45,
									},
								}}
							>
								<SVG
									className={"framer-gslsw6"}
									data-framer-name={"Icon"}
									layout={"position"}
									layoutDependency={layoutDependency}
									layoutId={"Tu8lip1QZ"}
									opacity={1}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 14 15"><path d="M 1.288 6.678 L 0.563 6.678 L 0.563 8.126 L 1.288 8.126 Z M 12.552 8.126 C 12.952 8.126 13.276 7.802 13.276 7.402 C 13.276 7.002 12.952 6.678 12.552 6.678 Z M 1.288 8.126 L 12.552 8.126 L 12.552 6.678 L 1.288 6.678 Z" fill="var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255))"></path><path d="M 6.919 1.77 L 12.552 7.402 L 6.919 13.034" fill="transparent" stroke-width="1.45" stroke="var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255))" stroke-linecap="square" stroke-linejoin="round" stroke-dasharray=""></path></svg>'
									}
									svgContentId={9064997395}
									withExternalLayout={true}
								/>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-NpiRD.framer-1u0nlsb, .framer-NpiRD .framer-1u0nlsb { display: block; }",
	".framer-NpiRD.framer-tgtc04 { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 350px; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; text-decoration: none; width: 253px; will-change: var(--framer-will-change-override, transform); }",
	".framer-NpiRD .framer-1531i8v { flex: 1 0 0px; height: 1px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 100%; }",
	".framer-NpiRD .framer-1msk8qg { bottom: 0px; flex: none; left: 0px; overflow: var(--overflow-clip-fallback, clip); position: absolute; right: 0px; top: 0px; }",
	".framer-NpiRD .framer-1vp4ps8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; left: 12px; overflow: visible; padding: 4px 8px 4px 8px; position: absolute; top: 12px; width: min-content; }",
	".framer-NpiRD .framer-1vlwmjg, .framer-NpiRD .framer-1bdyqux { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-NpiRD .framer-yqemug { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 48px 16px 48px 16px; position: relative; width: 100%; }",
	".framer-NpiRD .framer-uqn93y { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-NpiRD .framer-1pmg8jf { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 24px; position: absolute; right: 16px; top: 24px; width: min-content; z-index: 1; }",
	".framer-NpiRD .framer-gslsw6 { flex: none; height: 15px; position: relative; width: 14px; }",
	".framer-NpiRD.framer-v-w8kkpg.framer-tgtc04 { cursor: unset; }",
	".framer-NpiRD.framer-v-tgtc04.hover .framer-1pmg8jf { top: 16px; }",
	...css2,
	...css3,
	...css,
	'.framer-NpiRD[data-border="true"]::after, .framer-NpiRD [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerEpVFhcy8b = withCSS(Component, css4, "framer-NpiRD");
var stdin_default2 = FramerEpVFhcy8b;
FramerEpVFhcy8b.displayName = "News Card";
FramerEpVFhcy8b.defaultProps = {
	height: 350,
	width: 253,
};
addPropertyControls(FramerEpVFhcy8b, {
	variant: {
		options: ["uToUMNg3y", "fKoc4jxqS"],
		optionTitles: ["Desktop", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	HJorRaZNl: {
		__defaultAssetReference:
			"data:framer/asset-reference,cVI3IOmIcZKEGZ8a45nbHrH0GM.jpg?originalFilename=han-wei-sheng-GI8yg0ZNMXs-unsplash.jpg&preferredSize=auto&width=3024&height=4032",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,cVI3IOmIcZKEGZ8a45nbHrH0GM.jpg?originalFilename=han-wei-sheng-GI8yg0ZNMXs-unsplash.jpg&preferredSize=auto&width=3024&height=4032",
		},
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	DoELK3oP8: {
		defaultValue: "Lorem Ipsum News Blog Lorem Ipsum News Blog",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	KbXUsFj2Y: {
		defaultValue: "10.01.25",
		displayTextArea: false,
		title: "Date",
		type: ControlType.String,
	},
	txGDSPAmo: {
		title: "Link",
		type: ControlType.Link,
	},
	eW_riBZ21: {
		defaultValue: "Guides",
		displayTextArea: false,
		title: "Label",
		type: ControlType.String,
	},
});
addFonts(
	FramerEpVFhcy8b,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/7aOmHxu2BvbxG1cq5LLy/V5Zri2DTo6H8LChhsmnS/vJMhvJHxH.js
var NewsCardFonts = getFonts(stdin_default2);
var cycleOrder2 = ["R2eFK9WCU", "GuOGyBaST", "Z0KJNaq34"];
var serializationHash2 = "framer-h8znd";
var variantClassNames2 = {
	GuOGyBaST: "framer-v-1g2i2kh",
	R2eFK9WCU: "framer-v-1wrfidh",
	Z0KJNaq34: "framer-v-1owbadc",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var equals = (a3, b3) => {
	return typeof a3 === "string" && typeof b3 === "string"
		? a3.toLowerCase() === b3.toLowerCase()
		: a3 === b3;
};
var toResponsiveImage2 = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var QueryData = ({ query: query2, pageSize, children }) => {
	const data = useQueryData(query2);
	return children(data);
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableEnumMap = {
	"Blog Type": "d5wt0i8lE",
	All: "lhAZHtkO3",
};
var humanReadableVariantMap2 = {
	Desktop: "R2eFK9WCU",
	Mobile: "Z0KJNaq34",
	Tablet: "GuOGyBaST",
};
var getProps2 = ({ filter, filterType, height, id, width, ...props }) => {
	return {
		...props,
		eCugK7yZm:
			humanReadableEnumMap[filterType] ??
			filterType ??
			props.eCugK7yZm ??
			"lhAZHtkO3",
		SBX4pGyjX: filter ?? props.SBX4pGyjX,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "R2eFK9WCU",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		eCugK7yZm,
		SBX4pGyjX,
		uMH75oH07leflzsSDJ,
		xnF_MDm4ZleflzsSDJ,
		j5QY6LesNleflzsSDJ,
		chxBwxKwbleflzsSDJ,
		nJmEl3KhtleflzsSDJ,
		idleflzsSDJ,
		uMH75oH07esmhZO1wt,
		xnF_MDm4ZesmhZO1wt,
		j5QY6LesNesmhZO1wt,
		chxBwxKwbesmhZO1wt,
		nJmEl3KhtesmhZO1wt,
		idesmhZO1wt,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "R2eFK9WCU",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const visible = equals(eCugK7yZm, "lhAZHtkO3");
	const router = useRouter();
	const visible1 = equals(eCugK7yZm, "d5wt0i8lE");
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1wrfidh",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"R2eFK9WCU"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								GuOGyBaST: {
									"data-framer-name": "Tablet",
								},
								Z0KJNaq34: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{visible && (
							<motion2.div
								className={"framer-18ls3a"}
								data-framer-name={"All"}
								layoutDependency={layoutDependency}
								layoutId={"leflzsSDJ"}
							>
								<ChildrenCanSuspend>
									<QueryData
										query={{
											from: {
												alias: "leflzsSDJ",
												data: stdin_default,
												type: "Collection",
											},
											limit: {
												type: "LiteralValue",
												value: 10,
											},
											select: [
												{
													collection: "leflzsSDJ",
													name: "uMH75oH07",
													type: "Identifier",
												},
												{
													collection: "leflzsSDJ",
													name: "xnF_MDm4Z",
													type: "Identifier",
												},
												{
													collection: "leflzsSDJ",
													name: "j5QY6LesN",
													type: "Identifier",
												},
												{
													collection: "leflzsSDJ",
													name: "chxBwxKwb",
													type: "Identifier",
												},
												{
													collection: "leflzsSDJ",
													name: "nJmEl3Kht",
													type: "Identifier",
												},
												{
													collection: "leflzsSDJ",
													name: "id",
													type: "Identifier",
												},
											],
										}}
									>
										{(collection, paginationInfo, loadMore) => (
											<_Fragment>
												{collection?.map(
													(
														{
															chxBwxKwb: chxBwxKwbleflzsSDJ2,
															id: idleflzsSDJ2,
															j5QY6LesN: j5QY6LesNleflzsSDJ2,
															nJmEl3Kht: nJmEl3KhtleflzsSDJ2,
															uMH75oH07: uMH75oH07leflzsSDJ2,
															xnF_MDm4Z: xnF_MDm4ZleflzsSDJ2,
														},
														index,
													) => {
														xnF_MDm4ZleflzsSDJ2 ??= "";
														j5QY6LesNleflzsSDJ2 ??= "";
														chxBwxKwbleflzsSDJ2 ??= "";
														nJmEl3KhtleflzsSDJ2 ??= "";
														return (
															<LayoutGroup2 id={`leflzsSDJ-${idleflzsSDJ2}`}>
																<PathVariablesContext.Provider
																	value={{
																		chxBwxKwb: chxBwxKwbleflzsSDJ2,
																	}}
																>
																	<ResolveLinks
																		links={[
																			{
																				href: {
																					pathVariables: {
																						chxBwxKwb: chxBwxKwbleflzsSDJ2,
																					},
																					webPageId: "OpsqIwTZx",
																				},
																				implicitPathVariables: void 0,
																			},
																			{
																				href: {
																					pathVariables: {
																						chxBwxKwb: chxBwxKwbleflzsSDJ2,
																					},
																					webPageId: "OpsqIwTZx",
																				},
																				implicitPathVariables: void 0,
																			},
																			{
																				href: {
																					pathVariables: {
																						chxBwxKwb: chxBwxKwbleflzsSDJ2,
																					},
																					webPageId: "OpsqIwTZx",
																				},
																				implicitPathVariables: void 0,
																			},
																		]}
																	>
																		{(resolvedLinks) => (
																			<ComponentViewportProvider
																				height={350}
																				width={`max((max((${componentViewport?.width || "100vw"} + 10px) / 0, 1px) - 40px) / 3, 50px)`}
																				y={
																					(componentViewport?.y || 0) +
																					(0 +
																						((componentViewport?.height ||
																							1090) -
																							0 -
																							370) /
																							2) +
																					0 +
																					0
																				}
																				{...addPropertyOverrides2(
																					{
																						GuOGyBaST: {
																							width: `max((max((${componentViewport?.width || "100vw"} + 10px) / 0, 1px) - 20px) / 2, 50px)`,
																							y:
																								(componentViewport?.y || 0) +
																								(0 +
																									((componentViewport?.height ||
																										200) -
																										0 -
																										370) /
																										2) +
																								0 +
																								0,
																						},
																						Z0KJNaq34: {
																							width: `max(max((${componentViewport?.width || "100vw"} + 10px) / 0, 1px), 50px)`,
																							y:
																								(componentViewport?.y || 0) +
																								(0 +
																									((componentViewport?.height ||
																										200) -
																										0 -
																										370) /
																										2) +
																								0 +
																								0,
																						},
																					},
																					baseVariant,
																					gestureVariant,
																				)}
																			>
																				<SmartComponentScopedContainer
																					className={"framer-1mmjusz-container"}
																					layoutDependency={layoutDependency}
																					layoutId={"pvQpFk5i0-container"}
																					nodeId={"pvQpFk5i0"}
																					rendersWithMotion={true}
																					scopeId={"vJMhvJHxH"}
																				>
																					{_jsx2(stdin_default2, {
																						DoELK3oP8: xnF_MDm4ZleflzsSDJ2,
																						eW_riBZ21: nJmEl3KhtleflzsSDJ2,
																						height: "100%",
																						HJorRaZNl:
																							toResponsiveImage2(
																								uMH75oH07leflzsSDJ2,
																							),
																						id: "pvQpFk5i0",
																						KbXUsFj2Y: j5QY6LesNleflzsSDJ2,
																						layoutId: "pvQpFk5i0",
																						style: {
																							height: "100%",
																							width: "100%",
																						},
																						txGDSPAmo: resolvedLinks[0],
																						variant: "uToUMNg3y",
																						width: "100%",
																						...addPropertyOverrides2(
																							{
																								GuOGyBaST: {
																									txGDSPAmo: resolvedLinks[1],
																								},
																								Z0KJNaq34: {
																									txGDSPAmo: resolvedLinks[2],
																									variant: "fKoc4jxqS",
																								},
																							},
																							baseVariant,
																							gestureVariant,
																						),
																					})}
																				</SmartComponentScopedContainer>
																			</ComponentViewportProvider>
																		)}
																	</ResolveLinks>
																</PathVariablesContext.Provider>
															</LayoutGroup2>
														);
													},
												)}
											</_Fragment>
										)}
									</QueryData>
								</ChildrenCanSuspend>
							</motion2.div>
						)}
						{visible1 && (
							<motion2.div
								className={"framer-1ny7s4f"}
								data-framer-name={"Blog Type"}
								layoutDependency={layoutDependency}
								layoutId={"esmhZO1wt"}
							>
								<ChildrenCanSuspend>
									<QueryData
										query={{
											from: {
												alias: "esmhZO1wt",
												data: stdin_default,
												type: "Collection",
											},
											limit: {
												type: "LiteralValue",
												value: 10,
											},
											select: [
												{
													collection: "esmhZO1wt",
													name: "uMH75oH07",
													type: "Identifier",
												},
												{
													collection: "esmhZO1wt",
													name: "xnF_MDm4Z",
													type: "Identifier",
												},
												{
													collection: "esmhZO1wt",
													name: "j5QY6LesN",
													type: "Identifier",
												},
												{
													collection: "esmhZO1wt",
													name: "chxBwxKwb",
													type: "Identifier",
												},
												{
													collection: "esmhZO1wt",
													name: "nJmEl3Kht",
													type: "Identifier",
												},
												{
													collection: "esmhZO1wt",
													name: "id",
													type: "Identifier",
												},
											],
											where: {
												arguments: [
													{
														collection: "esmhZO1wt",
														name: "nJmEl3Kht",
														type: "Identifier",
													},
													{
														type: "LiteralValue",
														value: SBX4pGyjX,
													},
												],
												functionName: "CONTAINS",
												type: "FunctionCall",
											},
										}}
									>
										{(collection1, paginationInfo1, loadMore1) => (
											<_Fragment>
												{collection1?.map(
													(
														{
															chxBwxKwb: chxBwxKwbesmhZO1wt2,
															id: idesmhZO1wt2,
															j5QY6LesN: j5QY6LesNesmhZO1wt2,
															nJmEl3Kht: nJmEl3KhtesmhZO1wt2,
															uMH75oH07: uMH75oH07esmhZO1wt2,
															xnF_MDm4Z: xnF_MDm4ZesmhZO1wt2,
														},
														index1,
													) => {
														xnF_MDm4ZesmhZO1wt2 ??= "";
														j5QY6LesNesmhZO1wt2 ??= "";
														chxBwxKwbesmhZO1wt2 ??= "";
														nJmEl3KhtesmhZO1wt2 ??= "";
														return (
															<LayoutGroup2 id={`esmhZO1wt-${idesmhZO1wt2}`}>
																<PathVariablesContext.Provider
																	value={{
																		chxBwxKwb: chxBwxKwbesmhZO1wt2,
																	}}
																>
																	<ResolveLinks
																		links={[
																			{
																				href: {
																					pathVariables: {
																						chxBwxKwb: chxBwxKwbesmhZO1wt2,
																					},
																					webPageId: "OpsqIwTZx",
																				},
																				implicitPathVariables: void 0,
																			},
																			{
																				href: {
																					pathVariables: {
																						chxBwxKwb: chxBwxKwbesmhZO1wt2,
																					},
																					webPageId: "OpsqIwTZx",
																				},
																				implicitPathVariables: void 0,
																			},
																			{
																				href: {
																					pathVariables: {
																						chxBwxKwb: chxBwxKwbesmhZO1wt2,
																					},
																					webPageId: "OpsqIwTZx",
																				},
																				implicitPathVariables: void 0,
																			},
																		]}
																	>
																		{(resolvedLinks1) => (
																			<ComponentViewportProvider
																				height={350}
																				width={`max((max((${componentViewport?.width || "100vw"} + 10px) / 0, 1px) - 40px) / 3, 50px)`}
																				y={
																					(componentViewport?.y || 0) +
																					(0 +
																						((componentViewport?.height ||
																							1090) -
																							0 -
																							370) /
																							2) +
																					0 +
																					0
																				}
																				{...addPropertyOverrides2(
																					{
																						GuOGyBaST: {
																							width: `max((max((${componentViewport?.width || "100vw"} + 10px) / 0, 1px) - 20px) / 2, 50px)`,
																							y:
																								(componentViewport?.y || 0) +
																								(0 +
																									((componentViewport?.height ||
																										200) -
																										0 -
																										370) /
																										2) +
																								0 +
																								0,
																						},
																						Z0KJNaq34: {
																							width: `max(max((${componentViewport?.width || "100vw"} + 10px) / 0, 1px), 50px)`,
																							y:
																								(componentViewport?.y || 0) +
																								(0 +
																									((componentViewport?.height ||
																										200) -
																										0 -
																										370) /
																										2) +
																								0 +
																								0,
																						},
																					},
																					baseVariant,
																					gestureVariant,
																				)}
																			>
																				<SmartComponentScopedContainer
																					className={"framer-1qehmhc-container"}
																					layoutDependency={layoutDependency}
																					layoutId={"aQVTcaEc5-container"}
																					nodeId={"aQVTcaEc5"}
																					rendersWithMotion={true}
																					scopeId={"vJMhvJHxH"}
																				>
																					{_jsx2(stdin_default2, {
																						DoELK3oP8: xnF_MDm4ZesmhZO1wt2,
																						eW_riBZ21: nJmEl3KhtesmhZO1wt2,
																						height: "100%",
																						HJorRaZNl:
																							toResponsiveImage2(
																								uMH75oH07esmhZO1wt2,
																							),
																						id: "aQVTcaEc5",
																						KbXUsFj2Y: j5QY6LesNesmhZO1wt2,
																						layoutId: "aQVTcaEc5",
																						style: {
																							height: "100%",
																							width: "100%",
																						},
																						txGDSPAmo: resolvedLinks1[0],
																						variant: "uToUMNg3y",
																						width: "100%",
																						...addPropertyOverrides2(
																							{
																								GuOGyBaST: {
																									txGDSPAmo: resolvedLinks1[1],
																								},
																								Z0KJNaq34: {
																									txGDSPAmo: resolvedLinks1[2],
																								},
																							},
																							baseVariant,
																							gestureVariant,
																						),
																					})}
																				</SmartComponentScopedContainer>
																			</ComponentViewportProvider>
																		)}
																	</ResolveLinks>
																</PathVariablesContext.Provider>
															</LayoutGroup2>
														);
													},
												)}
											</_Fragment>
										)}
									</QueryData>
								</ChildrenCanSuspend>
							</motion2.div>
						)}
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-h8znd.framer-1b3ajmo, .framer-h8znd .framer-1b3ajmo { display: block; }",
	".framer-h8znd.framer-1wrfidh { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1136px; }",
	".framer-h8znd .framer-18ls3a, .framer-h8znd .framer-1ny7s4f { display: grid; flex: 1 0 0px; gap: 20px; grid-auto-rows: min-content; grid-template-columns: repeat(3, minmax(50px, 1fr)); height: min-content; justify-content: center; padding: 0px; position: relative; width: 1px; }",
	".framer-h8znd .framer-1mmjusz-container, .framer-h8znd .framer-1qehmhc-container { align-self: start; flex: none; height: 350px; justify-self: start; position: relative; width: 100%; }",
	".framer-h8znd.framer-v-1g2i2kh .framer-18ls3a, .framer-h8znd.framer-v-1g2i2kh .framer-1ny7s4f { grid-template-columns: repeat(2, minmax(50px, 1fr)); }",
	".framer-h8znd.framer-v-1owbadc.framer-1wrfidh { width: 375px; }",
	".framer-h8znd.framer-v-1owbadc .framer-18ls3a, .framer-h8znd.framer-v-1owbadc .framer-1ny7s4f { grid-template-columns: repeat(1, minmax(50px, 1fr)); }",
];
var FramervJMhvJHxH = withCSS2(Component2, css5, "framer-h8znd");
var stdin_default3 = FramervJMhvJHxH;
FramervJMhvJHxH.displayName = "Newsroom Grid";
FramervJMhvJHxH.defaultProps = {
	height: 1090,
	width: 1136,
};
addPropertyControls2(FramervJMhvJHxH, {
	variant: {
		options: ["R2eFK9WCU", "GuOGyBaST", "Z0KJNaq34"],
		optionTitles: ["Desktop", "Tablet", "Mobile"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	eCugK7yZm: {
		defaultValue: "lhAZHtkO3",
		options: ["lhAZHtkO3", "d5wt0i8lE"],
		optionTitles: ["All", "Blog Type"],
		title: "Filter Type",
		type: ControlType2.Enum,
	},
	SBX4pGyjX: {
		defaultValue: "",
		placeholder: "",
		title: "Filter",
		type: ControlType2.String,
	},
});
addFonts2(
	FramervJMhvJHxH,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...NewsCardFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:newsroom-grid
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "Z0KJNaq34",
	md: "GuOGyBaST",
	xl: "R2eFK9WCU",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NewsroomGridFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var newsroom_grid_default = ComponentWithRoot;
export { newsroom_grid_default as default };
