// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0d2be16cf4ecf57c "Anker (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Mobile' // Variant
 * text?: string // Text
 * link?: string // Link
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-WJBYBRXL.js";
import { routes } from "./chunks/chunk-QR7ZKMZ2.js";

// virtual:secondary
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/oUWRkuAvYfaYCiQAs9iF/xYXbSkHvfsBtJEkzJkaW/mtImaeMnm.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	LGIQ79fVb: {
		hover: true,
	},
};
var cycleOrder = ["LGIQ79fVb", "Ixy8euj5L"];
var serializationHash = "framer-8oRRz";
var variantClassNames = {
	Ixy8euj5L: "framer-v-1tdexjy",
	LGIQ79fVb: "framer-v-tnziuk",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.4,
	ease: [0.08, 0.78, 0.56, 1],
	type: "tween",
};
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "LGIQ79fVb",
	Mobile: "Ixy8euj5L",
};
var getProps = ({ height, id, link, text, width, ...props }) => {
	return {
		...props,
		jJSiQvJyC: text ?? props.jJSiQvJyC ?? "Button Text",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "LGIQ79fVb",
		xKlNh7HCe: link ?? props.xKlNh7HCe,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		jJSiQvJyC,
		xKlNh7HCe,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "LGIQ79fVb",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						motionChild={true}
						nodeId={"LGIQ79fVb"}
						scopeId={"mtImaeMnm"}
						{...addPropertyOverrides(
							{
								"LGIQ79fVb-hover": {
									href: xKlNh7HCe,
									openInNewTab: false,
								},
								Ixy8euj5L: {
									href: xKlNh7HCe,
									openInNewTab: false,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-tnziuk", className2, classNames)} framer-1o20lio`}
							data-framer-name={"Desktop"}
							layoutDependency={layoutDependency}
							layoutId={"LGIQ79fVb"}
							ref={refBinding}
							style={{
								borderBottomLeftRadius: 2,
								borderBottomRightRadius: 2,
								borderTopLeftRadius: 2,
								borderTopRightRadius: 2,
								...style,
							}}
							{...addPropertyOverrides(
								{
									"LGIQ79fVb-hover": {
										"data-framer-name": void 0,
									},
									Ixy8euj5L: {
										"data-framer-name": "Mobile",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-wsllnx"}
								data-framer-name={"Button Wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"h9KZf9OnZ"}
								style={{
									"--border-bottom-width": "0px",
									"--border-color": "rgba(0, 0, 0, 0)",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-style": "solid",
									"--border-top-width": "0px",
									backdropFilter: "blur(5px)",
									backgroundColor: "rgba(255, 255, 255, 0.25)",
									borderBottomLeftRadius: 40,
									borderBottomRightRadius: 40,
									borderTopLeftRadius: 40,
									borderTopRightRadius: 40,
									WebkitBackdropFilter: "blur(5px)",
								}}
								variants={{
									"LGIQ79fVb-hover": {
										"--border-bottom-width": "1px",
										"--border-color": "rgba(194, 194, 194, 0.5)",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										borderBottomLeftRadius: 21,
										borderBottomRightRadius: 21,
										borderTopLeftRadius: 21,
										borderTopRightRadius: 21,
									},
								}}
								{...addPropertyOverrides(
									{
										"LGIQ79fVb-hover": {
											"data-border": true,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1nogjwn"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"PmJUwwu75"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={jJSiQvJyC}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-g8iro9"}
											data-styles-preset={"Ck1ubvtuS"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255)))",
											}}
										>
											{"Button Text"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<motion.div
									className={"framer-1nuh6jr"}
									data-framer-name={"Clip"}
									layoutDependency={layoutDependency}
									layoutId={"atrCLVg9b"}
								>
									<motion.div
										className={"framer-1fz5rag"}
										data-framer-name={"Arrow Wrapper"}
										layoutDependency={layoutDependency}
										layoutId={"NlCbzwMOI"}
										transformTemplate={transformTemplate1}
									>
										<SVG
											className={"framer-18v3yqs"}
											data-framer-name={"Arrow Right"}
											fill={"black"}
											intrinsicHeight={85}
											intrinsicWidth={85}
											layoutDependency={layoutDependency}
											layoutId={"vXsVHZPt2"}
											svg={
												'<svg width="85" height="85" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="m15.031 42.969 52.544-.259M42.17 16.368 70.5 42.5 41.912 68.912" stroke="#ECECEC" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/></svg>'
											}
											withExternalLayout={true}
										/>
										<SVG
											className={"framer-s25aca"}
											data-framer-name={"Arrow Right"}
											fill={"black"}
											intrinsicHeight={85}
											intrinsicWidth={85}
											layoutDependency={layoutDependency}
											layoutId={"uH6zFgFjI"}
											svg={
												'<svg width="85" height="85" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="m15.031 42.969 52.544-.259M42.17 16.368 70.5 42.5 41.912 68.912" stroke="#ECECEC" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/></svg>'
											}
											withExternalLayout={true}
										/>
									</motion.div>
								</motion.div>
								<motion.div
									className={"framer-7us0dk"}
									data-framer-name={"Button Fill"}
									layoutDependency={layoutDependency}
									layoutId={"fMcIx80l6"}
									style={{
										backgroundColor: "rgba(255, 255, 255, 0.15)",
										borderBottomLeftRadius: 50,
										borderBottomRightRadius: 50,
										borderTopLeftRadius: 50,
										borderTopRightRadius: 50,
									}}
									variants={{
										"LGIQ79fVb-hover": {
											borderBottomLeftRadius: 0,
											borderBottomRightRadius: 0,
											borderTopLeftRadius: 0,
											borderTopRightRadius: 0,
										},
									}}
								/>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-8oRRz.framer-1o20lio, .framer-8oRRz .framer-1o20lio { display: block; }",
	".framer-8oRRz.framer-tnziuk { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 1px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-8oRRz .framer-wsllnx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; min-width: 100px; overflow: hidden; padding: 10px 16px 10px 16px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-8oRRz .framer-1nogjwn { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 2; }",
	".framer-8oRRz .framer-1nuh6jr { flex: none; gap: 10px; height: 20px; overflow: hidden; position: relative; width: 20px; z-index: 2; }",
	".framer-8oRRz .framer-1fz5rag { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: absolute; right: 2px; top: 50%; width: min-content; }",
	".framer-8oRRz .framer-18v3yqs, .framer-8oRRz .framer-s25aca { flex: none; height: 20px; position: relative; width: 20px; z-index: 1; }",
	".framer-8oRRz .framer-7us0dk { bottom: 0px; flex: none; left: -286px; overflow: visible; position: absolute; top: 0px; width: 152%; }",
	".framer-8oRRz.framer-v-1tdexjy.framer-tnziuk { cursor: unset; text-decoration: none; }",
	".framer-8oRRz.framer-v-tnziuk.hover.framer-tnziuk { text-decoration: none; }",
	".framer-8oRRz.framer-v-tnziuk.hover .framer-1fz5rag { right: -30px; }",
	".framer-8oRRz.framer-v-tnziuk.hover .framer-18v3yqs { order: 0; }",
	".framer-8oRRz.framer-v-tnziuk.hover .framer-s25aca { order: 1; }",
	".framer-8oRRz.framer-v-tnziuk.hover .framer-7us0dk { bottom: -2px; left: -20px; right: -20px; top: -2px; width: unset; }",
	...css,
	'.framer-8oRRz[data-border="true"]::after, .framer-8oRRz [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramermtImaeMnm = withCSS(Component, css2, "framer-8oRRz");
var stdin_default = FramermtImaeMnm;
FramermtImaeMnm.displayName = "Secondary";
FramermtImaeMnm.defaultProps = {
	height: 43,
	width: 135,
};
addPropertyControls(FramermtImaeMnm, {
	variant: {
		options: ["LGIQ79fVb", "Ixy8euj5L"],
		optionTitles: ["Desktop", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	jJSiQvJyC: {
		defaultValue: "Button Text",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	xKlNh7HCe: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramermtImaeMnm,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:secondary
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "Ixy8euj5L",
	xl: "LGIQ79fVb",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SecondaryFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var secondary_default = ComponentWithRoot;
export { secondary_default as default };
