// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0d2be16cf4ecf57c "Anker (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Mobile' // Variant
 * number?: string // Number
 * title?: string // Title
 * content?: string // Content
 * fill?: string // Fill
 * border?: undefined // Border
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-OCTLECST.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-BRGTNG7B.js";
import { routes } from "./chunks/chunk-QR7ZKMZ2.js";

// virtual:sticky-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/dDslF4KuCpB35osnJPfj/8MlDkJcLL3TDCdCxYS9I/VzqZS3F1U.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/VyROwEzo7CxvHAk8OJqc/yA7YhkhduUlvEiUpSNjI/ai2w3oKUT.js
import { fontStore } from "unframer";
fontStore.loadFonts(["GF;Geist-regular", "GF;Geist-700"]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Geist",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/geist/v4/gyBhhwUxId8gMGYQMKR3pzfaWI_RnOM4mJPby1QNtA.woff2",
				weight: "400",
			},
			{
				family: "Geist",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/geist/v4/gyBhhwUxId8gMGYQMKR3pzfaWI_Re-Q4mJPby1QNtA.woff2",
				weight: "700",
			},
		],
	},
];
var css3 = [
	'.framer-tev7O .framer-styles-preset-mn5npa:not(.rich-text-wrapper), .framer-tev7O .framer-styles-preset-mn5npa.rich-text-wrapper h1 { --framer-font-family: "Geist", "Geist Placeholder", sans-serif; --framer-font-family-bold: "Geist", "Geist Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: calc(var(--framer-root-font-size, 1rem) * 7); --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.04em; --framer-line-height: 0.8em; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-tev7O .framer-styles-preset-mn5npa:not(.rich-text-wrapper), .framer-tev7O .framer-styles-preset-mn5npa.rich-text-wrapper h1 { --framer-font-family: "Geist", "Geist Placeholder", sans-serif; --framer-font-family-bold: "Geist", "Geist Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: calc(var(--framer-root-font-size, 1rem) * 6.4); --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.04em; --framer-line-height: 0.8em; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-tev7O .framer-styles-preset-mn5npa:not(.rich-text-wrapper), .framer-tev7O .framer-styles-preset-mn5npa.rich-text-wrapper h1 { --framer-font-family: "Geist", "Geist Placeholder", sans-serif; --framer-font-family-bold: "Geist", "Geist Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: calc(var(--framer-root-font-size, 1rem) * 5.12); --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.04em; --framer-line-height: 0.8em; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className3 = "framer-tev7O";

// /:https://framerusercontent.com/modules/dDslF4KuCpB35osnJPfj/8MlDkJcLL3TDCdCxYS9I/VzqZS3F1U.js
var ImageWithFX = withFX(Image);
var cycleOrder = ["Bp4_w55KS", "cN4I6mB7D"];
var serializationHash = "framer-M4XKx";
var variantClassNames = {
	Bp4_w55KS: "framer-v-1kk3061",
	cN4I6mB7D: "framer-v-1r0ii87",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "Bp4_w55KS",
	Mobile: "cN4I6mB7D",
};
var getProps = ({
	border,
	content,
	fill,
	height,
	id,
	number,
	title,
	width,
	...props
}) => {
	return {
		...props,
		eXcEIiwOt: number ?? props.eXcEIiwOt ?? "1",
		KpEK0wvVZ: title ?? props.KpEK0wvVZ ?? "Strategic Guidance",
		rGWAf9IPE: border ??
			props.rGWAf9IPE ?? {
				borderBottomWidth: 0,
				borderColor:
					"var(--token-fc7799b1-5dfe-4fa1-a9e8-833f81a6959a, rgb(142, 132, 247))",
				borderLeftWidth: 0,
				borderRightWidth: 0,
				borderStyle: "solid",
				borderTopWidth: 2,
			},
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Bp4_w55KS",
		xd4M1UcQ3:
			fill ??
			props.xd4M1UcQ3 ??
			"var(--token-fc7799b1-5dfe-4fa1-a9e8-833f81a6959a, rgb(142, 132, 247))",
		YAFwJv6qL:
			content ??
			props.YAFwJv6qL ??
			"Lighthouses have stood as beacons of hope for centuries, guiding sailors safely through treacherous waters. Their glowing light and towering presence serve as a reminder of humanity\u2019s connection to the sea.",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		eXcEIiwOt,
		KpEK0wvVZ,
		YAFwJv6qL,
		xd4M1UcQ3,
		rGWAf9IPE,
		mE7nWIJGa,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Bp4_w55KS",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className3, className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<ImageWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__spring={{
							damping: 60,
							delay: 0,
							duration: 0.3,
							ease: [0.44, 0, 0.56, 1],
							mass: 1,
							stiffness: 500,
							type: "spring",
						}}
						__framer__styleTransformEffectEnabled={true}
						__framer__transformTargets={[
							{
								target: {
									opacity: 1,
									rotate: 0,
									rotateX: 0,
									rotateY: 0,
									scale: 1,
									skewX: 0,
									skewY: 0,
									x: 0,
									y: 0,
								},
							},
							{
								ref: mE7nWIJGa,
								target: {
									opacity: 1,
									rotate: 0,
									rotateX: 0,
									rotateY: 0,
									scale: 0.9,
									skewX: 0,
									skewY: 0,
									x: 0,
									y: 0,
								},
							},
						]}
						__framer__transformTrigger={"onScrollTarget"}
						__framer__transformViewportThreshold={0}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						background={{
							alt: "",
							backgroundSize: 1,
							fit: "tile",
							loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
							pixelHeight: 320,
							pixelWidth: 500,
							positionX: "left",
							positionY: "top",
							src: "https://framerusercontent.com/images/u0HKrndm7eM940oBTYLqf3SRQEc.jpg?width=500&height=320",
						}}
						className={cx(
							scopingClassNames,
							"framer-1kk3061",
							className4,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"Bp4_w55KS"}
						ref={refBinding}
						style={{
							"--border-bottom-width":
								(rGWAf9IPE.borderBottomWidth ?? rGWAf9IPE.borderWidth) + "px",
							"--border-color": rGWAf9IPE.borderColor,
							"--border-left-width":
								(rGWAf9IPE.borderLeftWidth ?? rGWAf9IPE.borderWidth) + "px",
							"--border-right-width":
								(rGWAf9IPE.borderRightWidth ?? rGWAf9IPE.borderWidth) + "px",
							"--border-style": rGWAf9IPE.borderStyle,
							"--border-top-width":
								(rGWAf9IPE.borderTopWidth ?? rGWAf9IPE.borderWidth) + "px",
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							...style,
						}}
						{...addPropertyOverrides(
							{
								cN4I6mB7D: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-16xxky2"}
							data-framer-name={"Corners Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"REmPXjN4N"}
						>
							<SVG
								className={"framer-1pqumb8"}
								data-framer-name={"Bottom Left"}
								layout={"position"}
								layoutDependency={layoutDependency}
								layoutId={"gtBkaOym9"}
								opacity={1}
								svg={
									'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 13 11"><path d="M 1 10.846 L 1 0.212 M 1.425 10.421 L 12.058 10.421" fill="transparent" stroke-width="0.849208" stroke="var(--token-aa4b05ac-cb0a-4952-a6ee-9d49e45f217d, rgb(92, 92, 92))" stroke-miterlimit="10" stroke-dasharray=""></path></svg>'
								}
								svgContentId={9893830841}
								withExternalLayout={true}
							/>
							<SVG
								className={"framer-zfo31i"}
								data-framer-name={"Bottom Right"}
								layout={"position"}
								layoutDependency={layoutDependency}
								layoutId={"RnRSYCofI"}
								opacity={1}
								svg={
									'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 11 12"><path d="M 10.846 11.058 L 0.212 11.058 M 10.421 10.633 L 10.421 0" fill="transparent" stroke-width="0.849208" stroke="var(--token-aa4b05ac-cb0a-4952-a6ee-9d49e45f217d, rgb(92, 92, 92))" stroke-miterlimit="10" stroke-dasharray=""></path></svg>'
								}
								svgContentId={8613533927}
								withExternalLayout={true}
							/>
							<SVG
								className={"framer-71pvyp"}
								data-framer-name={"Top Right"}
								layout={"position"}
								layoutDependency={layoutDependency}
								layoutId={"Tgy4koBNg"}
								opacity={1}
								svg={
									'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 13 11"><path d="M 11.846 0.212 L 11.846 10.846 M 11.421 0.637 L 0.788 0.637" fill="transparent" stroke-width="0.849208" stroke="var(--token-aa4b05ac-cb0a-4952-a6ee-9d49e45f217d, rgb(92, 92, 92))" stroke-miterlimit="10" stroke-dasharray=""></path></svg>'
								}
								svgContentId={9942974697}
								withExternalLayout={true}
							/>
							<SVG
								className={"framer-dd2xet"}
								data-framer-name={"Top Left"}
								layout={"position"}
								layoutDependency={layoutDependency}
								layoutId={"zFmta7Bvf"}
								opacity={1}
								svg={
									'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 11 12"><path d="M 0.221 0.788 L 10.854 0.788 M 0.645 1.212 L 0.645 11.846" fill="transparent" stroke-width="0.849208" stroke="var(--token-aa4b05ac-cb0a-4952-a6ee-9d49e45f217d, rgb(92, 92, 92))" stroke-miterlimit="10" stroke-dasharray=""></path></svg>'
								}
								svgContentId={9505129059}
								withExternalLayout={true}
							/>
						</motion.div>
						<motion.div
							className={"framer-1ugp7l0"}
							data-framer-name={"Overlay Full"}
							layoutDependency={layoutDependency}
							layoutId={"Fd5yLqyxL"}
							style={{
								backgroundColor: xd4M1UcQ3,
								opacity: 0.03,
							}}
						/>
						<motion.div
							className={"framer-1sjxm1y"}
							data-framer-name={"Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"YlPzwMIpH"}
						>
							<motion.div
								className={"framer-1wfygcj"}
								layoutDependency={layoutDependency}
								layoutId={"RfIDhat0j"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1vimud2"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"NVrq0pir2"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={eXcEIiwOt}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h1
											className={"framer-styles-preset-mn5npa"}
											data-styles-preset={"ai2w3oKUT"}
											style={{
												"--framer-text-alignment": "left",
											}}
										>
											{"1"}
										</motion.h1>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1igfwql"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"yYzNqC9D1"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={KpEK0wvVZ}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h5
											className={"framer-styles-preset-v2uh97"}
											data-styles-preset={"hgRR2OlAI"}
											style={{
												"--framer-text-alignment": "left",
											}}
										>
											{"Strategic Guidance"}
										</motion.h5>
									</React.Fragment>
								</RichText>
							</motion.div>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-e9bjrd"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"MX8UMtVTU"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-af1ab411-d3d7-4fef-86fb-cdfbfe2b260b, rgb(224, 224, 224))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={YAFwJv6qL}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-cpwznz"}
										data-styles-preset={"ls_KuhAAC"}
										style={{
											"--framer-text-alignment": "left",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-af1ab411-d3d7-4fef-86fb-cdfbfe2b260b, rgb(224, 224, 224)))",
										}}
									>
										{
											"Lighthouses have stood as beacons of hope for centuries, guiding sailors safely through treacherous waters. Their glowing light and towering presence serve as a reminder of humanity\u2019s connection to the sea."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</ImageWithFX>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-M4XKx.framer-13w6d4d, .framer-M4XKx .framer-13w6d4d { display: block; }",
	".framer-M4XKx.framer-1kk3061 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; max-width: 800px; overflow: hidden; padding: 64px; position: relative; width: 800px; will-change: var(--framer-will-change-override, transform); }",
	".framer-M4XKx .framer-16xxky2 { bottom: 20px; flex: none; left: 20px; overflow: hidden; position: absolute; right: 20px; top: 20px; z-index: 4; }",
	".framer-M4XKx .framer-1pqumb8 { bottom: 0px; flex: none; height: 11px; left: 0px; position: absolute; width: 13px; }",
	".framer-M4XKx .framer-zfo31i { bottom: 0px; flex: none; height: 12px; position: absolute; right: 0px; width: 11px; }",
	".framer-M4XKx .framer-71pvyp { flex: none; height: 11px; position: absolute; right: 0px; top: 0px; width: 13px; }",
	".framer-M4XKx .framer-dd2xet { flex: none; height: 12px; left: 0px; position: absolute; top: 0px; width: 11px; }",
	".framer-M4XKx .framer-1ugp7l0 { bottom: 0px; flex: none; left: 0px; overflow: hidden; pointer-events: none; position: absolute; right: 0px; top: 0px; }",
	".framer-M4XKx .framer-1sjxm1y { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-M4XKx .framer-1wfygcj { align-content: flex-end; align-items: flex-end; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1px; }",
	".framer-M4XKx .framer-1vimud2 { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 1; }",
	".framer-M4XKx .framer-1igfwql { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-M4XKx .framer-e9bjrd { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-M4XKx.framer-v-1r0ii87.framer-1kk3061 { padding: 48px; width: 294px; }",
	".framer-M4XKx.framer-v-1r0ii87 .framer-1sjxm1y { flex-direction: column; gap: 32px; }",
	".framer-M4XKx.framer-v-1r0ii87 .framer-1wfygcj { align-content: flex-start; align-items: flex-start; flex: none; flex-direction: column; width: 100%; }",
	".framer-M4XKx.framer-v-1r0ii87 .framer-e9bjrd { flex: none; width: 100%; }",
	...css3,
	...css,
	...css2,
	'.framer-M4XKx[data-border="true"]::after, .framer-M4XKx [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerVzqZS3F1U = withCSS(Component, css4, "framer-M4XKx");
var stdin_default = FramerVzqZS3F1U;
FramerVzqZS3F1U.displayName = "Sticky Card";
FramerVzqZS3F1U.defaultProps = {
	height: 232,
	width: 800,
};
addPropertyControls(FramerVzqZS3F1U, {
	variant: {
		options: ["Bp4_w55KS", "cN4I6mB7D"],
		optionTitles: ["Desktop", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	eXcEIiwOt: {
		defaultValue: "1",
		displayTextArea: false,
		title: "Number",
		type: ControlType.String,
	},
	KpEK0wvVZ: {
		defaultValue: "Strategic Guidance",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	YAFwJv6qL: {
		defaultValue:
			"Lighthouses have stood as beacons of hope for centuries, guiding sailors safely through treacherous waters. Their glowing light and towering presence serve as a reminder of humanity\u2019s connection to the sea.",
		displayTextArea: true,
		title: "Content",
		type: ControlType.String,
	},
	xd4M1UcQ3: {
		defaultValue:
			"var(--token-fc7799b1-5dfe-4fa1-a9e8-833f81a6959a, rgb(142, 132, 247))",
		title: "Fill",
		type: ControlType.Color,
	},
	rGWAf9IPE: {
		defaultValue: {
			borderBottomWidth: 0,
			borderColor:
				"var(--token-fc7799b1-5dfe-4fa1-a9e8-833f81a6959a, rgb(142, 132, 247))",
			borderLeftWidth: 0,
			borderRightWidth: 0,
			borderStyle: "solid",
			borderTopWidth: 2,
		},
		title: "Border",
		type: ControlType.Border,
	},
});
addFonts(
	FramerVzqZS3F1U,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:sticky-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "cN4I6mB7D",
	xl: "Bp4_w55KS",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders StickyCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var sticky_card_default = ComponentWithRoot;
export { sticky_card_default as default };
