// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0d2be16cf4ecf57c "Anker (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Mobile' // Variant
 * name?: string // Name
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * position?: string // Position
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-55EBAKF4.js";
import { className, css, fonts } from "./chunks/chunk-OCTLECST.js";
import { routes } from "./chunks/chunk-QR7ZKMZ2.js";

// virtual:team-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/tiDn5wCToKQI9531JoKx/G7ol8AdNGfpSqRQ9igSV/Rd1iz9T8K.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	IuF4ZbFlC: {
		hover: true,
	},
};
var cycleOrder = ["IuF4ZbFlC", "lH196V4Md"];
var serializationHash = "framer-kobZV";
var variantClassNames = {
	IuF4ZbFlC: "framer-v-1il8z4k",
	lH196V4Md: "framer-v-z2cftf",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.7,
	ease: [0.13, 1, 0.5, 1.02],
	type: "tween",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "IuF4ZbFlC",
	Mobile: "lH196V4Md",
};
var getProps = ({ height, id, image, name1, position, width, ...props }) => {
	return {
		...props,
		Oqd4514O7: position ?? props.Oqd4514O7 ?? "Position",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "IuF4ZbFlC",
		yRSCz697L: image ??
			props.yRSCz697L ?? {
				alt: "",
				pixelHeight: 1536,
				pixelWidth: 1024,
				src: "https://framerusercontent.com/images/xWzSQZqISwGMO2h5G2V7MSVJSP8.jpg?scale-down-to=512&width=1024&height=1536",
				srcSet:
					"https://framerusercontent.com/images/xWzSQZqISwGMO2h5G2V7MSVJSP8.jpg?scale-down-to=1024&width=1024&height=1536 682w,https://framerusercontent.com/images/xWzSQZqISwGMO2h5G2V7MSVJSP8.jpg?width=1024&height=1536 1024w",
			},
		zgu3YXFvA: name1 ?? props.zgu3YXFvA ?? "First Last",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		zgu3YXFvA,
		yRSCz697L,
		Oqd4514O7,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "IuF4ZbFlC",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "lH196V4Md") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1il8z4k",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"IuF4ZbFlC"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "0px",
							"--border-color": "rgba(0, 0, 0, 0)",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "0px",
							backgroundColor:
								"var(--token-0cdad307-f7d4-4932-883c-e1621a2e3092, rgb(18, 18, 18))",
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							...style,
						}}
						variants={{
							"IuF4ZbFlC-hover": {
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-2af2796e-c98f-415f-bfdd-4cf975fb4b80, rgb(51, 51, 51))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
							},
						}}
						{...addPropertyOverrides(
							{
								"IuF4ZbFlC-hover": {
									"data-border": true,
									"data-framer-name": void 0,
								},
								lH196V4Md: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1lecqnt"}
							data-framer-name={"Image Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"c7BD7On1n"}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									intrinsicHeight: 1536,
									intrinsicWidth: 1024,
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) + 0 + 0 + 0,
									),
									pixelHeight: 1536,
									pixelWidth: 1024,
									sizes: componentViewport?.width || "100vw",
									...toResponsiveImage(yRSCz697L),
									...{
										positionX: "center",
										positionY: "top",
									},
								}}
								className={"framer-qzhr2x"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"WYdN5tZIp"}
								style={{
									filter: "brightness(1.04) saturate(0)",
									scale: 1,
									WebkitFilter: "brightness(1.04) saturate(0)",
								}}
								variants={{
									"IuF4ZbFlC-hover": {
										filter: "brightness(1.04) saturate(1)",
										scale: 1.1,
										WebkitFilter: "brightness(1.04) saturate(1)",
									},
									lH196V4Md: {
										filter: "brightness(1.04) saturate(1)",
										WebkitFilter: "brightness(1.04) saturate(1)",
									},
								}}
							/>
							<motion.div
								className={"framer-15pskaa"}
								data-framer-name={"Corners Wrap"}
								layoutDependency={layoutDependency}
								layoutId={"lY8nIy75g"}
								style={{
									opacity: 0,
								}}
								variants={{
									"IuF4ZbFlC-hover": {
										opacity: 1,
									},
								}}
							>
								<SVG
									className={"framer-5mz65f"}
									data-framer-name={"Bottom Left"}
									layout={"position"}
									layoutDependency={layoutDependency}
									layoutId={"t9EA73qXV"}
									opacity={1}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 13 11"><path d="M 1 10.846 L 1 0.212 M 1.425 10.421 L 12.058 10.421" fill="transparent" stroke-width="0.849208" stroke="var(--token-aa4b05ac-cb0a-4952-a6ee-9d49e45f217d, rgb(92, 92, 92))" stroke-miterlimit="10" stroke-dasharray=""></path></svg>'
									}
									svgContentId={9893830841}
									withExternalLayout={true}
								/>
								<SVG
									className={"framer-zlsln0"}
									data-framer-name={"Bottom Right"}
									layout={"position"}
									layoutDependency={layoutDependency}
									layoutId={"eHaifqIy7"}
									opacity={1}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 11 12"><path d="M 10.846 11.058 L 0.212 11.058 M 10.421 10.633 L 10.421 0" fill="transparent" stroke-width="0.849208" stroke="var(--token-aa4b05ac-cb0a-4952-a6ee-9d49e45f217d, rgb(92, 92, 92))" stroke-miterlimit="10" stroke-dasharray=""></path></svg>'
									}
									svgContentId={8613533927}
									withExternalLayout={true}
								/>
								<SVG
									className={"framer-12ov7kf"}
									data-framer-name={"Top Right"}
									layout={"position"}
									layoutDependency={layoutDependency}
									layoutId={"DqIEiu_8l"}
									opacity={1}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 13 11"><path d="M 11.846 0.212 L 11.846 10.846 M 11.421 0.637 L 0.788 0.637" fill="transparent" stroke-width="0.849208" stroke="var(--token-aa4b05ac-cb0a-4952-a6ee-9d49e45f217d, rgb(92, 92, 92))" stroke-miterlimit="10" stroke-dasharray=""></path></svg>'
									}
									svgContentId={9942974697}
									withExternalLayout={true}
								/>
								<SVG
									className={"framer-1hf28th"}
									data-framer-name={"Top Left"}
									layout={"position"}
									layoutDependency={layoutDependency}
									layoutId={"xdLcT2wZZ"}
									opacity={1}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 11 12"><path d="M 0.221 0.788 L 10.854 0.788 M 0.645 1.212 L 0.645 11.846" fill="transparent" stroke-width="0.849208" stroke="var(--token-aa4b05ac-cb0a-4952-a6ee-9d49e45f217d, rgb(92, 92, 92))" stroke-miterlimit="10" stroke-dasharray=""></path></svg>'
									}
									svgContentId={9505129059}
									withExternalLayout={true}
								/>
							</motion.div>
						</motion.div>
						<motion.div
							className={"framer-gdr20s"}
							data-framer-name={"Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"al2jp2sQI"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-cjyr17"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"CO7m2jF21"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={zgu3YXFvA}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h5
										className={"framer-styles-preset-v2uh97"}
										data-styles-preset={"hgRR2OlAI"}
									>
										{"First Last"}
									</motion.h5>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1flmsu2"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"jBVjShcsI"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={Oqd4514O7}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-labdxo"}
										data-styles-preset={"CRmxFdPaP"}
									>
										{"Position"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						{isDisplayed() && (
							<motion.div
								className={"framer-x84twr"}
								data-border={true}
								data-framer-name={"Button Wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"JES1iQD2i"}
								style={{
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-af1ab411-d3d7-4fef-86fb-cdfbfe2b260b, rgb(224, 224, 224))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									borderBottomLeftRadius: "100%",
									borderBottomRightRadius: "100%",
									borderTopLeftRadius: "100%",
									borderTopRightRadius: "100%",
									opacity: 0.8,
									rotate: -45,
								}}
							>
								<SVG
									className={"framer-hltw66"}
									data-framer-name={"Icon"}
									layout={"position"}
									layoutDependency={layoutDependency}
									layoutId={"EbAllZWdE"}
									opacity={1}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 14 15"><path d="M 1.288 6.678 L 0.563 6.678 L 0.563 8.126 L 1.288 8.126 Z M 12.552 8.126 C 12.952 8.126 13.276 7.802 13.276 7.402 C 13.276 7.002 12.952 6.678 12.552 6.678 Z M 1.288 8.126 L 12.552 8.126 L 12.552 6.678 L 1.288 6.678 Z" fill="var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255))"></path><path d="M 6.919 1.77 L 12.552 7.402 L 6.919 13.034" fill="transparent" stroke-width="1.45" stroke="var(--token-5f03f6e3-536f-484e-82a8-ab5781b04eb8, rgb(255, 255, 255))" stroke-linecap="square" stroke-linejoin="round" stroke-dasharray=""></path></svg>'
									}
									svgContentId={9064997395}
									withExternalLayout={true}
								/>
							</motion.div>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-kobZV.framer-9vi743, .framer-kobZV .framer-9vi743 { display: block; }",
	".framer-kobZV.framer-1il8z4k { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: 448px; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 315px; will-change: var(--framer-will-change-override, transform); }",
	".framer-kobZV .framer-1lecqnt { flex: 1 0 0px; height: 1px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 100%; }",
	".framer-kobZV .framer-qzhr2x { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	".framer-kobZV .framer-15pskaa { bottom: 16px; flex: none; left: 16px; overflow: hidden; position: absolute; right: 16px; top: 16px; z-index: 2; }",
	".framer-kobZV .framer-5mz65f { bottom: 0px; flex: none; height: 11px; left: 0px; position: absolute; width: 13px; }",
	".framer-kobZV .framer-zlsln0 { bottom: 0px; flex: none; height: 12px; position: absolute; right: 0px; width: 11px; }",
	".framer-kobZV .framer-12ov7kf { flex: none; height: 11px; position: absolute; right: 0px; top: 0px; width: 13px; }",
	".framer-kobZV .framer-1hf28th { flex: none; height: 12px; left: 0px; position: absolute; top: 0px; width: 11px; }",
	".framer-kobZV .framer-gdr20s { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 24px; position: relative; width: 100%; }",
	".framer-kobZV .framer-cjyr17, .framer-kobZV .framer-1flmsu2 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-kobZV .framer-x84twr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 24px; position: absolute; right: 16px; top: 16px; width: min-content; z-index: 1; }",
	".framer-kobZV .framer-hltw66 { flex: none; height: 15px; position: relative; width: 14px; }",
	".framer-kobZV.framer-v-z2cftf.framer-1il8z4k { cursor: unset; }",
	...css,
	...css2,
	'.framer-kobZV[data-border="true"]::after, .framer-kobZV [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerRd1iz9T8K = withCSS(Component, css3, "framer-kobZV");
var stdin_default = FramerRd1iz9T8K;
FramerRd1iz9T8K.displayName = "Team Card";
FramerRd1iz9T8K.defaultProps = {
	height: 448,
	width: 315,
};
addPropertyControls(FramerRd1iz9T8K, {
	variant: {
		options: ["IuF4ZbFlC", "lH196V4Md"],
		optionTitles: ["Desktop", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	zgu3YXFvA: {
		defaultValue: "First Last",
		displayTextArea: false,
		title: "Name",
		type: ControlType.String,
	},
	yRSCz697L: {
		__defaultAssetReference:
			"data:framer/asset-reference,xWzSQZqISwGMO2h5G2V7MSVJSP8.jpg?originalFilename=FLORA-Attractive+Man+Portrait-064a0be4.jpg&preferredSize=auto&width=1024&height=1536",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,xWzSQZqISwGMO2h5G2V7MSVJSP8.jpg?originalFilename=FLORA-Attractive+Man+Portrait-064a0be4.jpg&preferredSize=auto&width=1024&height=1536",
		},
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	Oqd4514O7: {
		defaultValue: "Position",
		displayTextArea: false,
		title: "Position",
		type: ControlType.String,
	},
});
addFonts(
	FramerRd1iz9T8K,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:team-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "lH196V4Md",
	xl: "IuF4ZbFlC",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TeamCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0d2be16cf4ecf57c7d646f327de1047fa3d892120af4e82a90aa36cd500718cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var team_card_default = ComponentWithRoot;
export { team_card_default as default };
