/**
 * POST /api/outreach/campaigns/[id]/import-drafts
 *
 * Multipart upload of a previously-curated workbook (the one produced
 * by /api/outreach/campaigns/[id]/export-curated, or its standalone
 * cousin generated by the SVS curate scripts).  Pulls pre-written
 * drafts from the workbook's "Email Drafts" and "LinkedIn DMs" sheets,
 * matches each row to a campaign member by display name (normalized)
 * or LinkedIn URL, and upserts outreach_messages.
 *
 * Sheet expectations (matches the SVS curate builder):
 *   - "Email Drafts": columns "#", "Name", "LP Type", "Email", "Subject", "Body", ...
 *   - "LinkedIn DMs": columns "#", "Name", "LP Type", "LinkedIn URL", "DM (first touch)", ...
 *
 * Matching strategy:
 *   1. Try crm_entries.display_name (case-insensitive, whitespace-collapsed) within campaign
 *   2. Fall back to display_linkedin URL match (normalized: lowercase, no scheme, no trailing slash)
 *   3. Unmatched rows are returned in the response so the user can fix them upstream
 *
 * Drafts upserted as kind = 'email_intro' (channel=email, subject+body)
 * or 'dm_intro' (channel=linkedin, body).  Already-sent / delivered /
 * replied messages are left alone.
 */
import { NextRequest, NextResponse } from "next/server"
import * as XLSX from "xlsx"
import { sql } from "@/lib/db"
import { createClient } from "@/lib/supabase/server"

export const runtime = "nodejs"
export const maxDuration = 120

const MAX_BYTES = 25 * 1024 * 1024

function normName(s: string | null | undefined): string {
  return String(s ?? "").trim().toLowerCase().replace(/\s+/g, " ")
}
function normLinkedin(u: string | null | undefined): string {
  if (!u) return ""
  return String(u).trim().toLowerCase()
    .replace(/^https?:\/\//, "")
    .replace(/^www\./, "")
    .replace(/\/+$/, "")
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ id: string }> }) {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return NextResponse.json({ error: "Not signed in" }, { status: 401 })

    const { id } = await ctx.params
    const [campaign] = await sql`
      SELECT id FROM outreach_campaigns WHERE id = ${id} AND user_id = ${user.id}
    ` as any[]
    if (!campaign) return NextResponse.json({ error: "Campaign not found" }, { status: 404 })

    const form = await req.formData()
    const file = form.get("xlsx") as File | null
    if (!file) return NextResponse.json({ error: "Upload an xlsx as `xlsx`." }, { status: 400 })
    if (file.size > MAX_BYTES) {
      return NextResponse.json({ error: `File too large (max ${MAX_BYTES / 1e6}MB)` }, { status: 400 })
    }

    const ab = await file.arrayBuffer()
    const wb = XLSX.read(Buffer.from(ab), { type: "buffer" })

    // Build lookup of campaign members joined with crm display fields.
    const members = await sql`
      SELECT m.id AS member_id, m.crm_entry_id, e.display_name, e.display_linkedin, e.display_email
      FROM outreach_campaign_members m
      LEFT JOIN crm_entries e ON e.id = m.crm_entry_id AND e.user_id = m.user_id
      WHERE m.campaign_id = ${id} AND m.user_id = ${user.id}
    `
    const byName = new Map<string, any>()
    const byLinkedin = new Map<string, any>()
    for (const m of members as any[]) {
      if (m.display_name) byName.set(normName(m.display_name), m)
      if (m.display_linkedin) byLinkedin.set(normLinkedin(m.display_linkedin), m)
    }

    function findMember(name: string | null, linkedin: string | null): any | null {
      if (linkedin) {
        const n = normLinkedin(linkedin)
        if (n && byLinkedin.has(n)) return byLinkedin.get(n)
      }
      if (name) {
        const n = normName(name)
        if (n && byName.has(n)) return byName.get(n)
      }
      return null
    }

    function rowsFromSheet(sheetName: string): any[] {
      const ws = wb.Sheets[sheetName]
      if (!ws) return []
      return XLSX.utils.sheet_to_json(ws, { defval: null }) as any[]
    }

    const emailRows = rowsFromSheet("Email Drafts")
    const dmRows = rowsFromSheet("LinkedIn DMs")

    if (!emailRows.length && !dmRows.length) {
      return NextResponse.json(
        { error: "No 'Email Drafts' or 'LinkedIn DMs' sheets found in the workbook." },
        { status: 400 },
      )
    }

    const unmatched: { sheet: string; name: string; linkedin?: string }[] = []
    let emailUpserts = 0
    let dmUpserts = 0
    let skippedLocked = 0

    // ── Email drafts
    for (const r of emailRows) {
      const name = String(r.Name ?? "").trim()
      const subject = String(r.Subject ?? "").trim()
      const body = String(r.Body ?? "").trim()
      const email = String(r.Email ?? "").trim() || null
      if (!body || !subject) continue
      const match = findMember(name, null)
      if (!match) { unmatched.push({ sheet: "Email Drafts", name }); continue }

      // Check current status so we don't clobber sent/replied
      const [existing] = await sql`
        SELECT status FROM outreach_messages
        WHERE user_id = ${user.id} AND crm_entry_id = ${match.crm_entry_id} AND kind = 'email_intro'
      ` as any[]
      if (existing && ["sent", "delivered", "replied", "accepted"].includes(existing.status)) {
        skippedLocked++
        continue
      }
      await sql`
        INSERT INTO outreach_messages (
          user_id, crm_entry_id, kind, step_number, channel,
          body, subject, email_to, status, generated_by, model_notes, created_at, updated_at
        ) VALUES (
          ${user.id}, ${match.crm_entry_id}, 'email_intro', 0, 'email',
          ${body}, ${subject}, ${email ?? match.display_email ?? null}, 'draft',
          'imported:xlsx', ${`campaign:${id} import:email-drafts`}, NOW(), NOW()
        )
        ON CONFLICT (crm_entry_id, kind) DO UPDATE SET
          body = EXCLUDED.body, subject = EXCLUDED.subject, email_to = EXCLUDED.email_to,
          channel = EXCLUDED.channel,
          status = CASE WHEN outreach_messages.status IN ('sent','delivered','replied','accepted')
                        THEN outreach_messages.status ELSE 'draft' END,
          generated_by = EXCLUDED.generated_by, model_notes = EXCLUDED.model_notes, updated_at = NOW()
      `
      await sql`
        UPDATE outreach_campaign_members SET
          status = CASE WHEN status IN ('sent','replied') THEN status ELSE 'drafted' END,
          drafted_at = COALESCE(drafted_at, NOW()),
          updated_at = NOW()
        WHERE id = ${match.member_id} AND user_id = ${user.id}
      `
      emailUpserts++
    }

    // ── LinkedIn DMs
    for (const r of dmRows) {
      const name = String(r.Name ?? "").trim()
      const linkedinUrl = String(r["LinkedIn URL"] ?? "").trim() || null
      const dm = String(r["DM (first touch)"] ?? r["DM"] ?? "").trim()
      if (!dm) continue
      const match = findMember(name, linkedinUrl)
      if (!match) { unmatched.push({ sheet: "LinkedIn DMs", name, linkedin: linkedinUrl ?? undefined }); continue }

      const [existing] = await sql`
        SELECT status FROM outreach_messages
        WHERE user_id = ${user.id} AND crm_entry_id = ${match.crm_entry_id} AND kind = 'dm_intro'
      ` as any[]
      if (existing && ["sent", "delivered", "replied", "accepted"].includes(existing.status)) {
        skippedLocked++
        continue
      }
      await sql`
        INSERT INTO outreach_messages (
          user_id, crm_entry_id, kind, step_number, channel,
          body, status, generated_by, model_notes, created_at, updated_at
        ) VALUES (
          ${user.id}, ${match.crm_entry_id}, 'dm_intro', 0, 'linkedin',
          ${dm}, 'draft',
          'imported:xlsx', ${`campaign:${id} import:linkedin-dms`}, NOW(), NOW()
        )
        ON CONFLICT (crm_entry_id, kind) DO UPDATE SET
          body = EXCLUDED.body,
          status = CASE WHEN outreach_messages.status IN ('sent','delivered','replied','accepted')
                        THEN outreach_messages.status ELSE 'draft' END,
          generated_by = EXCLUDED.generated_by, model_notes = EXCLUDED.model_notes, updated_at = NOW()
      `
      await sql`
        UPDATE outreach_campaign_members SET
          status = CASE WHEN status IN ('sent','replied') THEN status ELSE 'drafted' END,
          drafted_at = COALESCE(drafted_at, NOW()),
          updated_at = NOW()
        WHERE id = ${match.member_id} AND user_id = ${user.id}
      `
      dmUpserts++
    }

    await sql`
      UPDATE outreach_campaigns SET
        status = CASE WHEN status = 'draft' AND ${emailUpserts + dmUpserts}::int > 0 THEN 'active' ELSE status END,
        updated_at = NOW()
      WHERE id = ${id} AND user_id = ${user.id}
    `

    return NextResponse.json({
      filename: file.name,
      sheets: { emailDrafts: emailRows.length, linkedinDms: dmRows.length },
      imported: { emailUpserts, dmUpserts },
      skippedLocked,
      unmatched,
    })
  } catch (e: any) {
    console.error("[import-drafts] error:", e)
    return NextResponse.json({ error: e?.message ?? "Import failed" }, { status: 500 })
  }
}
