#!/usr/bin/env bash
# Connects the Anker app on Vercel to the doc worker on Railway, and redeploys.
# Run it yourself in a terminal from the repo root (it moves a secret from Railway to Vercel; nobody else needs to see it).
#
#   bash scripts/wire-doc-worker.sh
#
# Needs: railway and vercel CLIs, both logged in. The token is generated by Railway and goes straight from
# Railway into Vercel through a pipe; it is never printed or written to a file.
set -euo pipefail

WORKER_URL="${WORKER_URL:-https://doc-worker-production.up.railway.app}"

cd "$(dirname "$0")/.."

echo "1/4 Checking the worker at $WORKER_URL"
curl -fsS "$WORKER_URL/health" | grep -q '"soffice":true' || { echo "The worker did not answer healthy. Stopping."; exit 1; }

echo "2/4 Setting DOC_WORKER_URL on Vercel (production)"
vercel env rm DOC_WORKER_URL production --yes >/dev/null 2>&1 || true
printf '%s' "$WORKER_URL" | vercel env add DOC_WORKER_URL production >/dev/null

echo "3/4 Moving the token from Railway to Vercel (production, sensitive)"
TOKEN_LINE="$(cd services/doc-worker && railway variables --service doc-worker --kv | grep '^DOC_WORKER_TOKEN=' || true)"
[ -n "$TOKEN_LINE" ] || { echo "No DOC_WORKER_TOKEN on the Railway service. Stopping."; exit 1; }
vercel env rm DOC_WORKER_TOKEN production --yes >/dev/null 2>&1 || true
printf '%s' "${TOKEN_LINE#DOC_WORKER_TOKEN=}" | vercel env add DOC_WORKER_TOKEN production --sensitive >/dev/null
unset TOKEN_LINE

echo "4/4 Redeploying production so it picks the variables up"
LATEST="$(vercel ls 2>/dev/null | grep -m1 -o 'https://[^ ]*')"
vercel redeploy "$LATEST" --target production
echo "Done. Open Tools, Word to PDF: you should now see the 'Exact layout' option."
